Edje_Edit.h File Reference
Edje_Edit.h File Reference
Functions to deal with edje internal object.
Data Structures
struct _Edje_Edit_Script_Error
struct _Edje_Part_Image_Use
struct _Edje_Edit_Limit
Typedefs
typedef enum _Edje_Edit_Image_Comp Edje_Edit_Image_Comp
Compression type for the image.
typedef enum _Edje_Edit_Select_Mode Edje_Edit_Select_Mode
Mode for a textblock part.
typedef enum _Edje_Edit_Sound_Comp Edje_Edit_Sound_Comp
Sound type compression.
typedef enum _Edje_Edit_Entry_Mode Edje_Edit_Entry_Mode
Mode for a textblock part.
typedef struct _Edje_Edit_Script_Error Edje_Edit_Script_Error
This is structure used for the list of errors that resulted from the last attempt to rebuild the Embryo script for the edited group.
typedef struct _Edje_Part_Image_Use Edje_Part_Image_Use
This is structure used for the list of group-part-state triplets where certain image is being used and pointed.
typedef struct _Edje_Edit_Limit Edje_Edit_Limit
This is structure used for list with the item names inside the limits block.
Enumerations
enum _Edje_Edit_Image_Comp {
EDJE_EDIT_IMAGE_COMP_RAW ,
EDJE_EDIT_IMAGE_COMP_USER ,
EDJE_EDIT_IMAGE_COMP_COMP ,
EDJE_EDIT_IMAGE_COMP_LOSSY ,
EDJE_EDIT_IMAGE_COMP_LOSSY_ETC1 ,
EDJE_EDIT_IMAGE_COMP_LOSSY_ETC2
}
Compression type for the image.
enum _Edje_Edit_Select_Mode {
EDJE_EDIT_SELECT_MODE_DEFAULT ,
EDJE_EDIT_SELECT_MODE_EXPLICIT
}
Mode for a textblock part.
enum _Edje_Edit_Sound_Comp {
EDJE_EDIT_SOUND_COMP_NONE ,
EDJE_EDIT_SOUND_COMP_RAW ,
EDJE_EDIT_SOUND_COMP_COMP ,
EDJE_EDIT_SOUND_COMP_LOSSY ,
EDJE_EDIT_SOUND_COMP_AS_IS
}
Sound type compression.
enum _Edje_Edit_Entry_Mode {
EDJE_EDIT_ENTRY_MODE_NONE ,
EDJE_EDIT_ENTRY_MODE_PLAIN ,
EDJE_EDIT_ENTRY_MODE_EDITABLE ,
EDJE_EDIT_ENTRY_MODE_PASSWORD
}
Mode for a textblock part.
Functions
General API
General functions that don't fit in other categories.
EAPI Evas_Object * edje_edit_object_add (Evas *e)
Adds an editable Edje object to the canvas.
EAPI void edje_edit_string_list_free (Eina_List *lst)
Frees a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
EAPI void edje_edit_string_free (const char *str)
Frees a generic string (char *) allocated by an edje_edit_*_get() function.
EAPI const char * edje_edit_compiler_get (Evas_Object *obj)
Gets the name of the program that compiled the edje file.
EAPI Eina_Bool edje_edit_save (Evas_Object *obj)
Saves the modified edje object back to his file.
EAPI Eina_Bool edje_edit_save_all (Evas_Object *obj)
Saves every group back into the file.
EAPI Eina_Bool edje_edit_clean_save_as (Evas_Object *obj, const char *new_file_name)
Saves every group into new file.
EAPI Eina_Bool edje_edit_without_source_save (Evas_Object *obj, Eina_Bool current_group)
Saves the group(s) back to the file, without generation source code.
EAPI void edje_edit_print_internal_status (Evas_Object *obj)
Prints on standard output many information about the internal status of the edje object.
Groups API
Functions to deal with groups property (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_group_add (Evas_Object *obj, const char *name)
Adds an edje (empty) group to an edje object's group set.
EAPI Eina_Bool edje_edit_group_copy (Evas_Object *obj, const char *group_name, const char *copy_name)
Copies whole group and all it's data into separate group.
EAPI Eina_Bool edje_edit_group_del (Evas_Object *obj, const char *group_name)
Deletes the specified group from the edje file.
EAPI Eina_Bool edje_edit_group_exist (Evas_Object *obj, const char *group)
Checks if a group with the given name exist in the edje.
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object *obj, const char *new_name)
Sets a new name for the current open group.
EAPI int edje_edit_group_min_w_get (Evas_Object *obj)
Gets the group minimum width.
EAPI Eina_Bool edje_edit_group_min_w_set (Evas_Object *obj, int w)
Sets the group minimum width.
EAPI int edje_edit_group_min_h_get (Evas_Object *obj)
Gets the group minimum height.
EAPI Eina_Bool edje_edit_group_min_h_set (Evas_Object *obj, int h)
Sets the group minimum height.
EAPI int edje_edit_group_max_w_get (Evas_Object *obj)
Gets the group maximum width.
EAPI Eina_Bool edje_edit_group_max_w_set (Evas_Object *obj, int w)
Sets the group maximum width.
EAPI int edje_edit_group_max_h_get (Evas_Object *obj)
Gets the group maximum height.
EAPI Eina_Bool edje_edit_group_max_h_set (Evas_Object *obj, int h)
Sets the group maximum height.
EAPI Eina_Bool edje_edit_group_broadcast_signal_get (Evas_Object *obj)
Gets the group broadcast_signal.
EAPI Eina_Bool edje_edit_group_broadcast_signal_set (Evas_Object *obj, Eina_Bool bs)
Sets the group broadcast signal.
EAPI Eina_List * edje_edit_group_limits_vertical_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the vertical limits block at the group level.
EAPI Eina_Bool edje_edit_group_limits_vertical_del (Evas_Object *obj, const char *name, int value)
Deletes given pair name-value from the vertical limits block at the group level.
EAPI Eina_Bool edje_edit_group_limits_vertical_add (Evas_Object *obj, const char *name, int value)
Adds given pair name-value to the vertical limits block at the group level.
EAPI Eina_List * edje_edit_group_limits_horizontal_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the horizontal limits block at the group level.
EAPI Eina_Bool edje_edit_group_limits_horizontal_del (Evas_Object *obj, const char *name, int value)
Deletes given pair name-value from the horizontal limits block at the group level.
EAPI Eina_Bool edje_edit_group_limits_horizontal_add (Evas_Object *obj, const char *name, int value)
Adds given pair name-value to the horizontal limits block at the group level.
EAPI void edje_edit_limits_list_free (Eina_List *lst)
Frees an Eina_List of (Edje_Edit_List *) allocated by an edje_edit_limits_vertical_list_get() or edje_edit_limits_horizontal_list_get() functions.
Alias API
Functions to deal with aliases that just another names of the group in the edje (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_group_aliases_get (Evas_Object *obj, const char *group_name)
Retrieves a list of aliases for this group.
EAPI Eina_Bool edje_edit_group_alias_is (Evas_Object *obj, const char *alias_name)
Checks if this group is an alias name.
EAPI const char * edje_edit_group_aliased_get (Evas_Object *obj, const char *alias_name)
Returns the main group name that is aliased by given alias name.
EAPI Eina_Bool edje_edit_group_alias_add (Evas_Object *obj, const char *group_name, const char *alias_name)
Adds new alias to the given group.
Data API
Functions to deal with data embedded in the edje (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block.
EAPI Eina_Bool edje_edit_data_add (Evas_Object *obj, const char *itemname, const char *value)
Creates a new global data object in the given edje file.
EAPI Eina_Bool edje_edit_data_del (Evas_Object *obj, const char *itemname)
Deletes the given data object from edje.
EAPI const char * edje_edit_data_value_get (Evas_Object *obj, const char *itemname)
Gets the data associated with the given itemname.
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object *obj, const char *itemname, const char *value)
Sets the data associated with the given itemname.
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object *obj, const char *itemname, const char *newname)
Changes the name of the given data object.
EAPI Eina_List * edje_edit_group_data_list_get (Evas_Object *obj)
Retrieves a list with the item names inside the data block at the group level.
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object *obj, const char *itemname, const char *value)
Creates a new data object in the given edje file belonging to the current group.
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object *obj, const char *itemname)
Deletes the given data object from the group.
EAPI const char * edje_edit_group_data_value_get (Evas_Object *obj, const char *itemname)
Gets the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object *obj, const char *itemname, const char *value)
Sets the data associated with the given itemname.
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object *obj, const char *itemname, const char *newname)
Changes the name of the given data object.
Size Classes API
Functions to deal with Size Classes (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_size_classes_list_get (Evas_Object *obj)
Gets the list of all the Size Classes in the given edje object.
EAPI Eina_Bool edje_edit_size_class_add (Evas_Object *obj, const char *name)
Creates a new size class object in the given edje.
EAPI Eina_Bool edje_edit_size_class_del (Evas_Object *obj, const char *name)
Deletes size class object from edje.
EAPI Eina_Bool edje_edit_size_class_name_set (Evas_Object *obj, const char *name, const char *newname)
Changes name of a size class.
EAPI Evas_Coord edje_edit_size_class_min_w_get (Evas_Object *obj, const char *class_name)
Returns width min size of specified size class.
EAPI Eina_Bool edje_edit_size_class_min_w_set (Evas_Object *obj, const char *class_name, Evas_Coord size)
Sets width min size of specified size class.
EAPI Evas_Coord edje_edit_size_class_max_w_get (Evas_Object *obj, const char *class_name)
Returns width max size of specified size class.
EAPI Eina_Bool edje_edit_size_class_max_w_set (Evas_Object *obj, const char *class_name, Evas_Coord size)
Sets width max size of specified size class.
EAPI Evas_Coord edje_edit_size_class_min_h_get (Evas_Object *obj, const char *class_name)
Returns height min size of specified size class.
EAPI Eina_Bool edje_edit_size_class_min_h_set (Evas_Object *obj, const char *class_name, Evas_Coord size)
Sets height min size of specified size class.
EAPI Evas_Coord edje_edit_size_class_max_h_get (Evas_Object *obj, const char *class_name)
Returns height max size of specified size class.
EAPI Eina_Bool edje_edit_size_class_max_h_set (Evas_Object *obj, const char *class_name, Evas_Coord size)
Sets height max size of specified size class.
Text Classes API
Functions to deal with Text Classes (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_text_classes_list_get (Evas_Object *obj)
Gets the list of all the Text Classes in the given edje object.
EAPI Eina_Bool edje_edit_text_class_add (Evas_Object *obj, const char *name)
Creates a new text class object in the given edje.
EAPI Eina_Bool edje_edit_text_class_del (Evas_Object *obj, const char *name)
Deletes text class object from edje.
EAPI Eina_Bool edje_edit_text_class_name_set (Evas_Object *obj, const char *name, const char *newname)
Changes name of a text class.
EAPI Eina_Stringshare * edje_edit_text_class_font_get (Evas_Object *obj, const char *class_name)
Returns font name of specified text class.
EAPI Eina_Bool edje_edit_text_class_font_set (Evas_Object *obj, const char *class_name, const char *font)
Sets font for the given text class.
EAPI Evas_Font_Size edje_edit_text_class_size_get (Evas_Object *obj, const char *class_name)
Returns font size of specified text class.
EAPI Eina_Bool edje_edit_text_class_size_set (Evas_Object *obj, const char *class_name, Evas_Font_Size size)
Sets font size for specified text class.
Color Classes API
Functions to deal with Color Classes (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_color_classes_list_get (Evas_Object *obj)
Gets the list of all the Color Classes in the given edje object.
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object *obj, const char *name)
Creates a new color class object in the given edje.
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object *obj, const char *name)
Deletes the given class object from edje.
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object *obj, const char *class_name, int *r, int *g, int *b, int *a, int *r2, int *g2, int *b2, int *a2, int *r3, int *g3, int *b3, int *a3)
Gets all the colors that compose the class.
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object *obj, const char *class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the colors for the given color class.
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object *obj, const char *name, const char *newname)
Changes the name of a color class.
EAPI Eina_Stringshare * edje_edit_color_class_description_get (Evas_Object *obj, const char *class_name)
Gets the description of a color class.
EAPI Eina_Bool edje_edit_color_class_description_set (Evas_Object *obj, const char *class_name, const char *desc)
Changes the description of a color class.
Text styles API
Functions to deal with text styles (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_styles_list_get (Evas_Object *obj)
Gets the list of all the text styles in the given edje object.
EAPI Eina_Bool edje_edit_style_add (Evas_Object *obj, const char *style)
Creates a new text style object in the given edje.
EAPI Eina_Bool edje_edit_style_del (Evas_Object *obj, const char *style)
Deletes the given text style and all the child tags.
EAPI Eina_List * edje_edit_style_tags_list_get (Evas_Object *obj, const char *style)
Gets the list of all the tags name in the given text style.
EAPI const char * edje_edit_style_tag_value_get (Evas_Object *obj, const char *style, const char *tag)
Gets the value of the given tag.
EAPI Eina_Bool edje_edit_style_tag_value_set (Evas_Object *obj, const char *style, const char *tag, const char *new_value)
Sets the value of the given tag.
EAPI Eina_Bool edje_edit_style_tag_name_set (Evas_Object *obj, const char *style, const char *tag, const char *new_name)
Sets the name of the given tag.
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object *obj, const char *style, const char *tag_name)
@
EAPI Eina_Bool edje_edit_style_tag_del (Evas_Object *obj, const char *style, const char *tag)
Deletes the given tag.
Externals API
Functions to deal with list of external modules (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_externals_list_get (Evas_Object *obj)
Gets the list of all the externals requested in the given edje object.
EAPI Eina_Bool edje_edit_external_add (Evas_Object *obj, const char *external)
Adds an external module to be requested on edje load.
EAPI Eina_Bool edje_edit_external_del (Evas_Object *obj, const char *external)
Deletes the given external from the list.
Parts API
Functions to deal with part objects (see Edje Data Collection reference).
EAPI Edje_Edit_Select_Mode edje_edit_part_select_mode_get (Evas_Object *obj, const char *part)
Gets the select mode for a textblock part.
EAPI Eina_Bool edje_edit_part_select_mode_set (Evas_Object *obj, const char *part, Edje_Edit_Select_Mode mode)
Sets the select mode for a textblock part.
EAPI Edje_Edit_Entry_Mode edje_edit_part_entry_mode_get (Evas_Object *obj, const char *part)
Gets the edit mode for a textblock part.
EAPI Eina_Bool edje_edit_part_entry_mode_set (Evas_Object *obj, const char *part, Edje_Edit_Entry_Mode mode)
Sets the edit mode for a textblock part.
EAPI Eina_List * edje_edit_parts_list_get (Evas_Object *obj)
Gets the list of all the parts in the given edje object.
EAPI Eina_Bool edje_edit_part_add (Evas_Object *obj, const char *name, Edje_Part_Type type)
Creates a new part in the given edje.
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object *obj, const char *name, const char *source)
Creates a new part of type EXTERNAL in the given edje.
EAPI Eina_Bool edje_edit_part_del (Evas_Object *obj, const char *part)
Deletes the given part from the edje.
EAPI Eina_Bool edje_edit_part_copy (Evas_Object *obj, const char *part, const char *new_copy)
Copies the given part in edje.
EAPI Eina_Bool edje_edit_part_exist (Evas_Object *obj, const char *part)
Checks if a part with the given name exist in the edje object.
EAPI const char * edje_edit_part_above_get (Evas_Object *obj, const char *part)
Gets the name of part stacked above the one passed.
EAPI const char * edje_edit_part_below_get (Evas_Object *obj, const char *part)
Gets the name of part stacked below the one passed.
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object *obj, const char *part)
Moves the given part below the previous one.
EAPI Eina_Bool edje_edit_part_restack_part_below (Evas_Object *obj, const char *part, const char *below)
Moves the given part below the part named below.
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object *obj, const char *part)
Moves the given part above the next one.
EAPI Eina_Bool edje_edit_part_restack_part_above (Evas_Object *obj, const char *part, const char *above)
Moves the given part above the part named above.
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object *obj, const char *part, const char *new_name)
Sets a new name for part.
EAPI const char * edje_edit_part_api_name_get (Evas_Object *obj, const char *part)
Gets api's name of a part.
EAPI const char * edje_edit_part_api_description_get (Evas_Object *obj, const char *part)
Gets api's description of a part.
EAPI Eina_Bool edje_edit_part_api_name_set (Evas_Object *obj, const char *part, const char *name)
Sets api's name of a part.
EAPI Eina_Bool edje_edit_part_api_description_set (Evas_Object *obj, const char *part, const char *description)
Sets api's description of a part.
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object *obj, const char *part)
Gets the type of a part.
EAPI const char * edje_edit_part_clip_to_get (Evas_Object *obj, const char *part)
Gets the clip_to part.
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object *obj, const char *part, const char *clip_to)
Sets a part to clip part to.
EAPI const char * edje_edit_part_source_get (Evas_Object *obj, const char *part)
Gets the source of part.
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object *obj, const char *part, const char *source)
Sets the source of part.
EAPI const char * edje_edit_part_source2_get (Evas_Object *obj, const char *part)
Gets the source2 of part.
EAPI Eina_Bool edje_edit_part_source2_set (Evas_Object *obj, const char *part, const char *source)
Sets the source2 of part.
EAPI const char * edje_edit_part_source3_get (Evas_Object *obj, const char *part)
Gets the source3 of part.
EAPI Eina_Bool edje_edit_part_source3_set (Evas_Object *obj, const char *part, const char *source)
Sets the source3 of part.
EAPI const char * edje_edit_part_source4_get (Evas_Object *obj, const char *part)
Gets the source4 of part.
EAPI Eina_Bool edje_edit_part_source4_set (Evas_Object *obj, const char *part, const char *source)
Sets the source4 of part.
EAPI const char * edje_edit_part_source5_get (Evas_Object *obj, const char *part)
Gets the source5 of part.
EAPI Eina_Bool edje_edit_part_source5_set (Evas_Object *obj, const char *part, const char *source)
Sets the source5 of part.
EAPI const char * edje_edit_part_source6_get (Evas_Object *obj, const char *part)
Gets the source6 of part.
EAPI Eina_Bool edje_edit_part_source6_set (Evas_Object *obj, const char *part, const char *source)
Sets the source6 of part.
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object *obj, const char *part)
Gets the effect for a given part.
EAPI Eina_Bool edje_edit_part_effect_set (Evas_Object *obj, const char *part, Edje_Text_Effect effect)
Sets the effect for a given part.
EAPI const char * edje_edit_part_selected_state_get (Evas_Object *obj, const char *part, double *value)
Gets the current selected state in part.
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object *obj, const char *part, const char *state, double value)
Sets the current state in part.
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object *obj, const char *part)
Gets mouse_events for part.
EAPI Eina_Bool edje_edit_part_mouse_events_set (Evas_Object *obj, const char *part, Eina_Bool mouse_events)
Sets mouse_events for part.
EAPI Eina_Bool edje_edit_part_required_get (Evas_Object *obj, const char *part)
Gets required value for part.
EAPI Eina_Bool edje_edit_part_anti_alias_get (Evas_Object *obj, const char *part)
Gets anti-aliasing for part.
EAPI Eina_Bool edje_edit_part_anti_alias_set (Evas_Object *obj, const char *part, Eina_Bool anti_alias)
Sets anti-aliasing for part.
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object *obj, const char *part)
Gets repeat_events for part.
EAPI Eina_Bool edje_edit_part_repeat_events_set (Evas_Object *obj, const char *part, Eina_Bool repeat_events)
Sets repeat_events for part.
EAPI Eina_Bool edje_edit_part_use_alternate_font_metrics_get (Evas_Object *obj, const char *part)
Gets use_alternate_font_metrics variable for part.
EAPI Eina_Bool edje_edit_part_use_alternate_font_metrics_set (Evas_Object *obj, const char *part, Eina_Bool use)
Sets use_alternate_font_metrics variable for part.
EAPI Eina_Bool edje_edit_part_multiline_get (Evas_Object *obj, const char *part)
Gets multiline for part.
EAPI Eina_Bool edje_edit_part_multiline_set (Evas_Object *obj, const char *part, Eina_Bool multiline)
Sets multiline for part.
EAPI Eina_Bool edje_edit_part_precise_is_inside_get (Evas_Object *obj, const char *part)
Gets precise_is_inside for part.
EAPI Eina_Bool edje_edit_part_precise_is_inside_set (Evas_Object *obj, const char *part, Eina_Bool precise_is_inside)
Sets precise_is_inside for part.
EAPI Eina_Bool edje_edit_part_access_get (Evas_Object *obj, const char *part)
Gets accessibility for part.
EAPI Eina_Bool edje_edit_part_access_set (Evas_Object *obj, const char *part, Eina_Bool access)
Sets accessibility for part.
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object *obj, const char *part)
Gets ignore_flags for part.
EAPI Eina_Bool edje_edit_part_ignore_flags_set (Evas_Object *obj, const char *part, Evas_Event_Flags ignore_flags)
Sets ignore_flags for part.
EAPI Evas_Event_Flags edje_edit_part_mask_flags_get (Evas_Object *obj, const char *part)
Gets mask_flags for part.
EAPI Eina_Bool edje_edit_part_mask_flags_set (Evas_Object *obj, const char *part, Evas_Event_Flags mask_flags)
Sets mask_flags for part.
EAPI Evas_Object_Pointer_Mode edje_edit_part_pointer_mode_get (Evas_Object *obj, const char *part)
Gets pointer_mode of a part.
EAPI Eina_Bool edje_edit_part_pointer_mode_set (Evas_Object *obj, const char *part, Evas_Object_Pointer_Mode pointer_mode)
Gets pointer_mode of a part.
EAPI unsigned char edje_edit_part_cursor_mode_get (Evas_Object *obj, const char *part)
Gets cursor_mode of a part.
EAPI Eina_Bool edje_edit_part_cursor_mode_set (Evas_Object *obj, const char *part, unsigned char cursor_mode)
Gets pointer_mode of a part.
EAPI Eina_Bool edje_edit_part_scale_set (Evas_Object *obj, const char *part, Eina_Bool scale)
Sets scale property for the part.
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object *obj, const char *part)
Gets scale for the part.
EAPI int edje_edit_part_drag_x_get (Evas_Object *obj, const char *part)
Gets horizontal draggable state for part.
EAPI Eina_Bool edje_edit_part_drag_x_set (Evas_Object *obj, const char *part, int drag)
Sets horizontal draggable state for part.
EAPI int edje_edit_part_drag_y_get (Evas_Object *obj, const char *part)
Gets vertical draggable state for part.
EAPI Eina_Bool edje_edit_part_drag_y_set (Evas_Object *obj, const char *part, int drag)
Sets vertical draggable state for part.
EAPI int edje_edit_part_drag_step_x_get (Evas_Object *obj, const char *part)
Gets horizontal draggable step for part.
EAPI Eina_Bool edje_edit_part_drag_step_x_set (Evas_Object *obj, const char *part, int step)
Sets horizontal draggable state for part.
EAPI int edje_edit_part_drag_step_y_get (Evas_Object *obj, const char *part)
Gets vertical draggable step for part.
EAPI Eina_Bool edje_edit_part_drag_step_y_set (Evas_Object *obj, const char *part, int step)
Sets vertical draggable state for part.
EAPI int edje_edit_part_drag_count_x_get (Evas_Object *obj, const char *part)
Gets horizontal draggable count for part.
EAPI Eina_Bool edje_edit_part_drag_count_x_set (Evas_Object *obj, const char *part, int count)
Sets horizontal draggable count for part.
EAPI int edje_edit_part_drag_count_y_get (Evas_Object *obj, const char *part)
Gets vertical draggable count for part.
EAPI Eina_Bool edje_edit_part_drag_count_y_set (Evas_Object *obj, const char *part, int count)
Sets vertical draggable count for part.
EAPI const char * edje_edit_part_drag_confine_get (Evas_Object *obj, const char *part)
Gets the name of the part that is used as 'confine' for the given draggies.
EAPI Eina_Bool edje_edit_part_drag_confine_set (Evas_Object *obj, const char *part, const char *confine)
Sets the name of the part that is used as 'confine' for the given draggies.
EAPI const char * edje_edit_part_drag_event_get (Evas_Object *obj, const char *part)
Gets the name of the part that is used as the receiver of the drag event.
EAPI Eina_Bool edje_edit_part_drag_event_set (Evas_Object *obj, const char *part, const char *event)
Sets the name of the part that will receive events from the given draggies.
EAPI const char * edje_edit_part_drag_threshold_get (Evas_Object *obj, const char *part)
Gets the name of the part that is used as 'threshold' for the given draggies.
EAPI Eina_Bool edje_edit_part_drag_threshold_set (Evas_Object *obj, const char *part, const char *threshold)
Sets the name of the part that is used as 'threshold' for the given draggies.
Box Description API
Functions to deal with box (see Edje Data Collection reference).
EAPI Eina_Stringshare * edje_edit_state_box_layout_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets primary layout of the box.
EAPI Eina_Bool edje_edit_state_box_layout_set (Evas_Object *obj, const char *part, const char *state, double value, char *layout)
Sets primary layout of the box.
EAPI Eina_Stringshare * edje_edit_state_box_alt_layout_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets fallback layout of the box.
EAPI Eina_Bool edje_edit_state_box_alt_layout_set (Evas_Object *obj, const char *part, const char *state, double value, char *layout)
Sets fallback layout of the box.
Table Description API
Functions to deal with table (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_state_table_homogeneous_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char homogeneous)
Sets homogeneous mode for TABLE part.
EAPI unsigned char edje_edit_state_table_homogeneous_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets homogeneous mode for TABLE part.
"Container" Description API
Functions to deal both with box and table (see Edje Data Collection reference).
Those functions called edje_edit_state_container_<something> because they are working both for TABLE and BOX at same time.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_min_get (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool *h, Eina_Bool *v)
Gets whether vertical or horizontal minimum size's of the box are equal to the minimum vertical or horizontal size of items (function for BOX or TABLE part. If EINA_TRUE - is equal, if EINA_FALSE - is not)
EAPI Eina_Bool edje_edit_state_container_min_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets whether horizontal min size of the container is equal to the min horizontal size of items (BOX and TABLE part functions).
EAPI Eina_Bool edje_edit_state_container_min_v_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets whether vertical min size of the container is equal to the min vertical size of items (BOX and TABLE part functions).
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_min_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool h, Eina_Bool v)
Sets whether vertical or horizontal minimum size's of the box are equal to the minimum vertical or horizontal size of items (function for BOX or TABLE part. If EINA_TRUE - is equal, if EINA_FALSE - is not)
EAPI Eina_Bool edje_edit_state_container_min_h_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool h)
Sets whether horizontal min size of the container should be equal to the min horizontal size of items (BOX and TABLE part functions).
EAPI Eina_Bool edje_edit_state_container_min_v_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool v)
Sets whether vertical min size of the container should be equal to the min vertical size of items (BOX and TABLE part functions).
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_padding_get (Evas_Object *obj, const char *part, const char *state, double value, int *x, int *y)
Gets x and y paddings for BOX or TABLE part.
EAPI int edje_edit_state_container_padding_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets x padding for BOX or TABLE part.
EAPI int edje_edit_state_container_padding_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets y padding for BOX or TABLE part.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_padding_set (Evas_Object *obj, const char *part, const char *state, double value, int x, int y)
Sets x and y paddings for BOX or TABLE part.
EAPI Eina_Bool edje_edit_state_container_padding_x_set (Evas_Object *obj, const char *part, const char *state, double value, int x)
Sets x padding for BOX or TABLE part.
EAPI Eina_Bool edje_edit_state_container_padding_y_set (Evas_Object *obj, const char *part, const char *state, double value, int y)
Sets y padding for BOX or TABLE part.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_align_set (Evas_Object *obj, const char *part, const char *state, double value, double x, double y)
Sets x and y align for BOX or TABLE part.
EAPI Eina_Bool edje_edit_state_container_align_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets x align for BOX or TABLE part.
EAPI Eina_Bool edje_edit_state_container_align_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets y align for BOX or TABLE part.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_align_get (Evas_Object *obj, const char *part, const char *state, double value, double *x, double *y)
Gets x and y align for BOX or TABLE part.
EAPI double edje_edit_state_container_align_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets x align for BOX or TABLE part.
EAPI double edje_edit_state_container_align_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets y align for BOX or TABLE part.
Items API
Functions to deal with table and box part's items (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_part_item_append (Evas_Object *obj, const char *part, const char *item_name, const char *source_group)
Appends new item to box or table part.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_insert_before (Evas_Object *obj, const char *part, const char *item_name, const char *item_before, const char *source_group)
Inserts new item to box or table part before specified existing item.
EAPI Eina_Bool edje_edit_part_item_insert_before_index (Evas_Object *obj, const char *part, const char *item_name, unsigned int index, const char *source_group)
Inserts new item to box or table part before specified existing item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_insert_after (Evas_Object *obj, const char *part, const char *item_name, const char *item_after, const char *source_group)
Inserts new item to box or table part after specified existing item.
EAPI Eina_Bool edje_edit_part_item_insert_after_index (Evas_Object *obj, const char *part, const char *item_name, unsigned int index, const char *source_group)
Inserts new item to box or table part after specified existing item.
EAPI Eina_Bool edje_edit_part_item_insert_at (Evas_Object *obj, const char *part, const char *item_name, const char *source_group, unsigned int place)
Inserts new item to box or table part directly into specified position.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_move_above (Evas_Object *obj, const char *part, const char *item_name)
Restacks existing item above.
EAPI Eina_Bool edje_edit_part_item_move_above_index (Evas_Object *obj, const char *part, unsigned int index)
Restacks existing item above.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_move_below (Evas_Object *obj, const char *part, const char *item_name)
Restacks existing item below.
EAPI Eina_Bool edje_edit_part_item_move_below_index (Evas_Object *obj, const char *part, unsigned int index)
Restacks existing item below.
EINA_DEPRECATED EAPI Eina_List * edje_edit_part_items_list_get (Evas_Object *obj, const char *part)
Gets the list of all part items in the given edje.
EAPI int edje_edit_part_items_count_get (Evas_Object *obj, const char *part)
Gets the count of part items in the given edje.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_del (Evas_Object *obj, const char *part, const char *name)
Deletes item from box or table part.
EAPI Eina_Bool edje_edit_part_item_index_del (Evas_Object *obj, const char *part, unsigned int index)
Deletes item from box or table part by index.
EAPI Eina_Bool edje_edit_part_item_index_name_set (Evas_Object *obj, const char *part, unsigned int index, const char *name)
Sets name for item from table or box items.
EAPI const char * edje_edit_part_item_index_name_get (Evas_Object *obj, const char *part, unsigned int index)
Gets name for item from table or box items.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_source_set (Evas_Object *obj, const char *part, const char *item_name, const char *source_group)
Sets source for item from table or box items.
EAPI Eina_Bool edje_edit_part_item_index_source_set (Evas_Object *obj, const char *part, unsigned int index, const char *source_group)
Sets source for item from table or box items.
EINA_DEPRECATED EAPI const char * edje_edit_part_item_source_get (Evas_Object *obj, const char *part, const char *item_name)
Gets source for item from table or box items.
EAPI const char * edje_edit_part_item_index_source_get (Evas_Object *obj, const char *part, unsigned int index)
Gets source for item from table or box items.
EINA_DEPRECATED EAPI int edje_edit_part_item_min_w_get (Evas_Object *obj, const char *part, const char *item)
Gets the minimum width value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_min_w_set (Evas_Object *obj, const char *part, const char *item, int min_w)
Sets the minimum width value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_min_h_get (Evas_Object *obj, const char *part, const char *item)
Gets the minimum height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_min_h_set (Evas_Object *obj, const char *part, const char *item, int min_h)
Sets the minimum height value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_max_w_get (Evas_Object *obj, const char *part, const char *item)
Gets the maximum width value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_max_w_set (Evas_Object *obj, const char *part, const char *item, int max_w)
Sets the maximum width value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_max_h_get (Evas_Object *obj, const char *part, const char *item)
Gets the maximum height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_max_h_set (Evas_Object *obj, const char *part, const char *item, int max_h)
Sets the maximum height value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_aspect_w_get (Evas_Object *obj, const char *part, const char *item)
Gets the aspect width value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_w_set (Evas_Object *obj, const char *part, const char *item, int aspect_w)
Sets the aspect width value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_aspect_h_get (Evas_Object *obj, const char *part, const char *item)
Gets the aspect height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_h_set (Evas_Object *obj, const char *part, const char *item, int aspect_h)
Sets the aspect height value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_prefer_w_get (Evas_Object *obj, const char *part, const char *item)
Gets the prefer width value of a part's item.
EINA_DEPRECATED EAPI Edje_Aspect_Control edje_edit_part_item_aspect_mode_get (Evas_Object *obj, const char *part, const char *item)
Gets aspect mode for an item of TABLE or BOX.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_mode_set (Evas_Object *obj, const char *part, const char *item, Edje_Aspect_Control mode)
Sets aspect mode for an item of TABLE or BOX.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_prefer_w_set (Evas_Object *obj, const char *part, const char *item, int prefer_w)
Sets the prefer width value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_prefer_h_get (Evas_Object *obj, const char *part, const char *item)
Gets the prefer height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_prefer_h_set (Evas_Object *obj, const char *part, const char *item, int prefer_h)
Sets the prefer height value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_spread_w_get (Evas_Object *obj, const char *part, const char *item)
Gets the spread width value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_spread_w_set (Evas_Object *obj, const char *part, const char *item, int spread_w)
Sets the spread width value of a part's item.
EINA_DEPRECATED EAPI int edje_edit_part_item_spread_h_get (Evas_Object *obj, const char *part, const char *item)
Gets the spread height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_spread_h_set (Evas_Object *obj, const char *part, const char *item, int spread_h)
Sets the spread height value of a part's item.
EAPI int edje_edit_part_item_index_min_w_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the minimum width value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_min_w_set (Evas_Object *obj, const char *part, unsigned int index, int min_w)
Sets the minimum width value of a part's item.
EAPI int edje_edit_part_item_index_min_h_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the minimum height value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_min_h_set (Evas_Object *obj, const char *part, unsigned int index, int min_h)
Sets the minimum height value of a part's item.
EAPI int edje_edit_part_item_index_max_w_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the maximum width value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_max_w_set (Evas_Object *obj, const char *part, unsigned int index, int max_w)
Sets the maximum width value of a part's item.
EAPI int edje_edit_part_item_index_max_h_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the maximum height value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_max_h_set (Evas_Object *obj, const char *part, unsigned int index, int max_h)
Sets the maximum height value of a part's item.
EAPI int edje_edit_part_item_index_aspect_w_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the aspect width value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_aspect_w_set (Evas_Object *obj, const char *part, unsigned int index, int aspect_w)
Sets the aspect width value of a part's item.
EAPI int edje_edit_part_item_index_aspect_h_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the aspect height value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_aspect_h_set (Evas_Object *obj, const char *part, unsigned int index, int aspect_h)
Sets the aspect height value of a part's item.
EAPI int edje_edit_part_item_index_prefer_w_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the prefer width value of a part's item.
EAPI Edje_Aspect_Control edje_edit_part_item_index_aspect_mode_get (Evas_Object *obj, const char *part, unsigned int index)
Gets aspect mode for an item of TABLE or BOX.
EAPI Eina_Bool edje_edit_part_item_index_aspect_mode_set (Evas_Object *obj, const char *part, unsigned int index, Edje_Aspect_Control mode)
Sets aspect mode for an item of TABLE or BOX.
EAPI Eina_Bool edje_edit_part_item_index_prefer_w_set (Evas_Object *obj, const char *part, unsigned int index, int prefer_w)
Sets the prefer width value of a part's item.
EAPI int edje_edit_part_item_index_prefer_h_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the prefer height value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_prefer_h_set (Evas_Object *obj, const char *part, unsigned int index, int prefer_h)
Sets the prefer height value of a part's item.
EAPI int edje_edit_part_item_index_spread_w_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the spread width value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_spread_w_set (Evas_Object *obj, const char *part, unsigned int index, int spread_w)
Sets the spread width value of a part's item.
EAPI int edje_edit_part_item_index_spread_h_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the spread height value of a part's item.
EAPI Eina_Bool edje_edit_part_item_index_spread_h_set (Evas_Object *obj, const char *part, unsigned int index, int spread_h)
Sets the spread height value of a part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_padding_get (Evas_Object *obj, const char *part, const char *item_name, int *l, int *r, int *t, int *b)
Gets paddings of the part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_padding_set (Evas_Object *obj, const char *part, const char *item_name, int l, int r, int t, int b)
Sets paddings of the part's item.
EAPI Eina_Bool edje_edit_part_item_index_padding_get (Evas_Object *obj, const char *part, unsigned int index, int *l, int *r, int *t, int *b)
Gets paddings of the part's item.
EAPI Eina_Bool edje_edit_part_item_index_padding_set (Evas_Object *obj, const char *part, unsigned int index, int l, int r, int t, int b)
Sets paddings of the part's item.
EINA_DEPRECATED EAPI double edje_edit_part_item_align_x_get (Evas_Object *obj, const char *part, const char *item)
Gets the horizontal align value of a part state.
EAPI double edje_edit_part_item_index_align_x_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the horizontal align value of a part state.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_align_x_set (Evas_Object *obj, const char *part, const char *item, double align_x)
Sets the horizontal align value of a part state.
EAPI Eina_Bool edje_edit_part_item_index_align_x_set (Evas_Object *obj, const char *part, unsigned int index, double align_x)
Sets the horizontal align value of a part state.
EINA_DEPRECATED EAPI double edje_edit_part_item_align_y_get (Evas_Object *obj, const char *part, const char *item)
Gets the vertical align value of a part state.
EAPI double edje_edit_part_item_index_align_y_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the vertical align value of a part state.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_align_y_set (Evas_Object *obj, const char *part, const char *item, double align_y)
Sets the vertical align value of a part state.
EAPI Eina_Bool edje_edit_part_item_index_align_y_set (Evas_Object *obj, const char *part, unsigned int index, double align_y)
Sets the vertical align value of a part state.
EINA_DEPRECATED EAPI double edje_edit_part_item_weight_x_get (Evas_Object *obj, const char *part, const char *item)
Gets the horizontal weight value of a part item.
EAPI double edje_edit_part_item_index_weight_x_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the horizontal weight value of a part item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_weight_x_set (Evas_Object *obj, const char *part, const char *item, double weight_x)
Sets the horizontal we value of a part item.
EAPI Eina_Bool edje_edit_part_item_index_weight_x_set (Evas_Object *obj, const char *part, unsigned int index, double weight_x)
Sets the horizontal we value of a part item.
EINA_DEPRECATED EAPI double edje_edit_part_item_weight_y_get (Evas_Object *obj, const char *part, const char *item)
Gets the vertical weight value of a part item.
EAPI double edje_edit_part_item_index_weight_y_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the vertical weight value of a part item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_weight_y_set (Evas_Object *obj, const char *part, const char *item, double weight_y)
Sets the vertical weight value of a part item.
EAPI Eina_Bool edje_edit_part_item_index_weight_y_set (Evas_Object *obj, const char *part, unsigned int index, double weight_y)
Sets the vertical weight value of a part item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_get (Evas_Object *obj, const char *part, const char *item_name, unsigned short *col, unsigned short *row)
Gets column/row position of the part's item.
EAPI double edje_edit_part_item_item_align_x_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the horizontal align value of a part state.
EAPI Eina_Bool edje_edit_part_item_item_align_x_set (Evas_Object *obj, const char *part, unsigned int index, double align_x)
Sets the horizontal align value of a part state.
EAPI double edje_edit_part_item_item_align_y_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the vertical align value of a part state.
EAPI Eina_Bool edje_edit_part_item_item_align_y_set (Evas_Object *obj, const char *part, unsigned int index, double align_y)
Sets the vertical align value of a part state.
EAPI double edje_edit_part_item_item_weight_x_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the horizontal weight value of a part item.
EAPI Eina_Bool edje_edit_part_item_item_weight_x_set (Evas_Object *obj, const char *part, unsigned int index, double weight_x)
Sets the horizontal we value of a part item.
EAPI double edje_edit_part_item_item_weight_y_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the vertical weight value of a part item.
EAPI Eina_Bool edje_edit_part_item_item_weight_y_set (Evas_Object *obj, const char *part, unsigned int index, double weight_y)
Sets the vertical weight value of a part item.
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_position_col_get (Evas_Object *obj, const char *part, const char *item_name)
Gets column position of the part's item.
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_position_row_get (Evas_Object *obj, const char *part, const char *item_name)
Gets row position of the part's item.
EAPI unsigned short edje_edit_part_item_index_position_col_get (Evas_Object *obj, const char *part, unsigned int index)
Gets column position of the part's item.
EAPI unsigned short edje_edit_part_item_index_position_row_get (Evas_Object *obj, const char *part, unsigned int index)
Gets row position of the part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_set (Evas_Object *obj, const char *part, const char *item_name, unsigned short col, unsigned short row)
Sets column/row position of a new part's item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_col_set (Evas_Object *obj, const char *part, const char *item_name, unsigned short col)
Sets column position of a part item.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_row_set (Evas_Object *obj, const char *part, const char *item_name, unsigned short row)
Sets row position of a part item.
EAPI Eina_Bool edje_edit_part_item_index_position_col_set (Evas_Object *obj, const char *part, unsigned int index, unsigned short col)
Sets column position of a part item.
EAPI Eina_Bool edje_edit_part_item_index_position_row_set (Evas_Object *obj, const char *part, unsigned int index, unsigned short row)
Sets row position of a part item.
EINA_DEPRECATED EAPI void edje_edit_part_item_span_get (Evas_Object *obj, const char *part, const char *item, unsigned char *col, unsigned char *row)
Retrieves the how many columns and rows will span for use by item.
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_span_col_get (Evas_Object *obj, const char *part, const char *item)
Gets the number of span columns.
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_span_row_get (Evas_Object *obj, const char *part, const char *item)
Gets the number of span rows.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_set (Evas_Object *obj, const char *part, const char *item, unsigned char col, unsigned char row)
Sets the count of columns and rows, which this item will spans for use.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_col_set (Evas_Object *obj, const char *part, const char *item, unsigned short col)
Sets the count of columns which this item will spans for use.
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_row_set (Evas_Object *obj, const char *part, const char *item, unsigned short row)
Sets the count of rows which this item will spans for use.
EAPI Eina_Bool edje_edit_part_item_index_span_col_set (Evas_Object *obj, const char *part, unsigned int index, unsigned short col)
Sets the count of columns which this item will spans for use.
EAPI Eina_Bool edje_edit_part_item_index_span_row_set (Evas_Object *obj, const char *part, unsigned int index, unsigned short row)
Sets the count of rows which this item will spans for use.
EAPI unsigned short edje_edit_part_item_index_span_col_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the number of span columns.
EAPI unsigned short edje_edit_part_item_index_span_row_get (Evas_Object *obj, const char *part, unsigned int index)
Gets the number of span rows.
States API
Functions to deal with part states (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_part_states_list_get (Evas_Object *obj, const char *part)
Gets the list of all the states in the given part.
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object *obj, const char *part, const char *state, double value, const char *new_name, double new_value)
Sets a new name for the given state in the given part.
EAPI Eina_Bool edje_edit_state_add (Evas_Object *obj, const char *part, const char *name, double value)
Creates a new state to the give part.
EAPI Eina_Bool edje_edit_state_del (Evas_Object *obj, const char *part, const char *state, double value)
Deletes the given part state from the edje.
EAPI Eina_Bool edje_edit_state_exist (Evas_Object *obj, const char *part, const char *state, double value)
Checks if a part state with the given name exist.
EAPI Eina_Bool edje_edit_state_copy (Evas_Object *obj, const char *part, const char *from, double val_from, const char *to, double val_to)
Copies the state from into to.
EAPI double edje_edit_state_rel1_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel1 relative X' value of state.
EAPI double edje_edit_state_rel1_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel1 relative Y' value of state.
EAPI double edje_edit_state_rel2_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel2 relative X' value of state.
EAPI double edje_edit_state_rel2_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel2 relative Y' value of state.
EAPI Eina_Bool edje_edit_state_rel1_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the 'rel1 relative X' value of state.
EAPI Eina_Bool edje_edit_state_rel1_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets the 'rel1 relative Y' value of state.
EAPI Eina_Bool edje_edit_state_rel2_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the 'rel2 relative X' value of state.
EAPI Eina_Bool edje_edit_state_rel2_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets the 'rel2 relative Y' value of state.
EAPI int edje_edit_state_rel1_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel1 offset X' value of state.
EAPI int edje_edit_state_rel1_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel1 offset Y' value of state.
EAPI int edje_edit_state_rel2_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel2 offset X' value of state.
EAPI int edje_edit_state_rel2_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the 'rel2 offset Y' value of state.
EAPI Eina_Bool edje_edit_state_rel1_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, int x)
Sets the 'rel1 offset X' value of state.
EAPI Eina_Bool edje_edit_state_rel1_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, int y)
Sets the 'rel1 offset Y' value of state.
EAPI Eina_Bool edje_edit_state_rel2_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, int x)
Sets the 'rel2 offset X' value of state.
EAPI Eina_Bool edje_edit_state_rel2_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, int y)
Sets the 'rel2 offset Y' value of state.
EAPI const char * edje_edit_state_rel1_to_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part name rel1x is relative to.
EAPI const char * edje_edit_state_rel1_to_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part name rel1y is relative to.
EAPI const char * edje_edit_state_rel2_to_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part name rel2x is relative to.
EAPI const char * edje_edit_state_rel2_to_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part name rel2y is relative to.
EAPI Eina_Bool edje_edit_state_rel1_to_x_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Sets the part rel1x is relative to.
EAPI Eina_Bool edje_edit_state_rel1_to_y_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Sets the part rel1y is relative to.
EAPI Eina_Bool edje_edit_state_rel2_to_x_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Sets the part rel2x is relative to.
EAPI Eina_Bool edje_edit_state_rel2_to_y_set (Evas_Object *obj, const char *part, const char *state, double value, const char *rel_to)
Sets the part rel2y is relative to.
EAPI void edje_edit_state_color_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Gets the color of a part state.
EAPI void edje_edit_state_color2_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Gets the color2 of a part state.
EAPI void edje_edit_state_color3_get (Evas_Object *obj, const char *part, const char *state, double value, int *r, int *g, int *b, int *a)
Gets the color3 of a part state.
EAPI Eina_Bool edje_edit_state_color_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Sets the color of a part state.
EAPI Eina_Bool edje_edit_state_color2_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Sets the color2 of a part state.
EAPI Eina_Bool edje_edit_state_color3_set (Evas_Object *obj, const char *part, const char *state, double value, int r, int g, int b, int a)
Sets the color3 of a part state.
EAPI double edje_edit_state_align_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the horizontal align value of a part state.
EAPI double edje_edit_state_align_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the vertical align value of a part state.
EAPI Eina_Bool edje_edit_state_align_x_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Sets the horizontal align value of a part state.
EAPI Eina_Bool edje_edit_state_align_y_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Sets the vertical align value of a part state.
EAPI int edje_edit_state_min_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the minimum width value of a part state.
EAPI Eina_Bool edje_edit_state_min_w_set (Evas_Object *obj, const char *part, const char *state, double value, int min_w)
Sets the minimum width value of a part state.
EAPI int edje_edit_state_min_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the minimum height value of a part state.
EAPI Eina_Bool edje_edit_state_min_h_set (Evas_Object *obj, const char *part, const char *state, double value, int min_h)
Sets the minimum height value of a part state.
EAPI int edje_edit_state_max_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the maximum width value of a part state.
EAPI Eina_Bool edje_edit_state_max_w_set (Evas_Object *obj, const char *part, const char *state, double value, int max_w)
Sets the maximum width value of a part state.
EAPI int edje_edit_state_max_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the maximum height value of a part state.
EAPI Eina_Bool edje_edit_state_max_h_set (Evas_Object *obj, const char *part, const char *state, double value, int max_h)
Sets the maximum height value of a part state.
EAPI double edje_edit_state_minmul_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the multiplier (minmul) width value of a part state.
EAPI Eina_Bool edje_edit_state_minmul_w_set (Evas_Object *obj, const char *part, const char *state, double value, double minmul_w)
Sets the multiplier (minmul) width value of a part state.
EAPI double edje_edit_state_minmul_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the multiplier (minmul) height value of a part state.
EAPI Eina_Bool edje_edit_state_minmul_h_set (Evas_Object *obj, const char *part, const char *state, double value, double minmul_h)
Sets the multiplier (minmul) height value of a part state.
EAPI Eina_Bool edje_edit_state_fixed_w_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fixed width value of a part state.
EAPI Eina_Bool edje_edit_state_fixed_w_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fixed)
Sets the fixed width value of a part state.
EAPI Eina_Bool edje_edit_state_fixed_h_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fixed height value of a part state.
EAPI Eina_Bool edje_edit_state_fixed_h_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fixed)
Sets the fixed height value of a part state.
EAPI double edje_edit_state_aspect_min_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the minimum aspect value of a part state.
EAPI double edje_edit_state_aspect_max_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the maximum aspect value of a part state.
EAPI Eina_Bool edje_edit_state_aspect_min_set (Evas_Object *obj, const char *part, const char *state, double value, double aspect)
Sets the minimum aspect value of a part state.
EAPI Eina_Bool edje_edit_state_aspect_max_set (Evas_Object *obj, const char *part, const char *state, double value, double aspect)
Sets the maximum aspect value of a part state.
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the aspect preference of a part state.
EAPI Eina_Bool edje_edit_state_aspect_pref_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char pref)
Sets the aspect preference of a part state.
EAPI Eina_Bool edje_edit_state_fill_smooth_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the smooth property for given part state.
EAPI Eina_Bool edje_edit_state_fill_smooth_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool smooth)
Sets the smooth property for given part state.
EAPI unsigned char edje_edit_state_fill_type_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill type property for given part state.
EAPI Eina_Bool edje_edit_state_fill_type_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char fill_type)
Sets the fill type property for given part state.
EAPI double edje_edit_state_fill_origin_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill horizontal origin relative value of a part state.
EAPI double edje_edit_state_fill_origin_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill vertical origin relative value of a part state.
EAPI int edje_edit_state_fill_origin_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill horizontal origin offset value of a part state.
EAPI int edje_edit_state_fill_origin_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill vertical origin offset value of a part state.
EAPI Eina_Bool edje_edit_state_fill_origin_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the fill horizontal origin relative value of a part state.
EAPI Eina_Bool edje_edit_state_fill_origin_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets the fill horizontal origin relative value of a part state.
EAPI Eina_Bool edje_edit_state_fill_origin_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the fill horizontal origin offset value of a part state.
EAPI Eina_Bool edje_edit_state_fill_origin_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets the fill vertical origin offset value of a part state.
EAPI double edje_edit_state_fill_size_relative_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill horizontal size relative value of a part state.
EAPI double edje_edit_state_fill_size_relative_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill vertical size relative value of a part state.
EAPI int edje_edit_state_fill_size_offset_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill horizontal size offset value of a part state.
EAPI int edje_edit_state_fill_size_offset_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the fill vertical size offset value of a part state.
EAPI Eina_Bool edje_edit_state_fill_size_relative_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the fill horizontal size relative value of a part state.
EAPI Eina_Bool edje_edit_state_fill_size_relative_y_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the fill vertical size relative value of a part state.
EAPI Eina_Bool edje_edit_state_fill_size_offset_x_set (Evas_Object *obj, const char *part, const char *state, double value, double x)
Sets the fill horizontal size offset value of a part state.
EAPI Eina_Bool edje_edit_state_fill_size_offset_y_set (Evas_Object *obj, const char *part, const char *state, double value, double y)
Sets the fill vertical size offset value of a part state.
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the visibility of a part state.
EAPI Eina_Bool edje_edit_state_visible_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool visible)
Sets the visibility of a part state.
EAPI const char * edje_edit_state_color_class_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the color class of the given part state.
EAPI Eina_Bool edje_edit_state_color_class_set (Evas_Object *obj, const char *part, const char *state, double value, const char *color_class)
Sets the color class of the given part state.
EAPI const Eina_List * edje_edit_state_external_params_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the list of parameters for an external part.
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type *type, void **val)
Gets the external parameter type and value.
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int *val)
Gets external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool *val)
Gets external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double *val)
Gets external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Gets external parameter of type STRING.
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char **val)
Gets external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Edje_External_Param_Type type,...)
Sets the external parameter type and value, adding it if it didn't exist before.
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, int val)
Sets external parameter of type INT.
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, Eina_Bool val)
Sets external parameter of type BOOL.
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, double val)
Sets external parameter of type DOUBLE.
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Sets external parameter of type STRING.
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object *obj, const char *part, const char *state, double value, const char *param, const char *val)
Sets external parameter of type CHOICE.
EAPI Eina_Bool edje_edit_state_step_set (Evas_Object *obj, const char *part, const char *state, double value, int step_x, int step_y)
Sets the states step parameter values.
EAPI Eina_Bool edje_edit_state_step_get (Evas_Object *obj, const char *part, const char *state, double value, int *step_x, int *step_y)
Gets the states step values.
EAPI Eina_Bool edje_edit_state_limit_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char limit)
Sets the states limit parameter value.
EAPI unsigned char edje_edit_state_limit_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the states limit value.
Map API
Functions to deal with objects with rotation properties (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_state_map_on_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the flag which enables mapping for the part.
EAPI Eina_Bool edje_edit_state_map_on_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool on)
Enables mapping for the part.
EAPI const char * edje_edit_state_map_perspective_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part's name that is used as the 'perspective point'.
EAPI Eina_Bool edje_edit_state_map_perspective_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source_part)
Sets the part's name that is used as the 'perspective point'.
EAPI const char * edje_edit_state_map_light_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part's name that is used as the 'light' for calculating the brightness.
EAPI Eina_Bool edje_edit_state_map_light_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source_part)
Sets the part that is used as the 'light'.
EAPI Eina_Bool edje_edit_state_map_backface_cull_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets backface_cull value of given part state.
EAPI Eina_Bool edje_edit_state_map_backface_cull_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool backface_cull)
Sets backface_cull value of given part state.
EAPI Eina_Bool edje_edit_state_map_perspective_on_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets perspective_on value of given part state.
EAPI Eina_Bool edje_edit_state_map_perspective_on_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool perspective_on)
Sets perspective_on value of given part state.
EAPI Eina_Bool edje_edit_state_map_alpha_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets map.alpha value of given part state.
EAPI Eina_Bool edje_edit_state_map_alpha_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool alpha)
Sets map.alpha value of given part state.
EAPI Eina_Bool edje_edit_state_map_smooth_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets map.smooth value of given part state.
EAPI Eina_Bool edje_edit_state_map_smooth_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool smooth)
Sets map.smooth value of given part state.
EAPI Eina_Bool edje_edit_state_map_rotation_get (Evas_Object *obj, const char *part, const char *state, double value, double *x, double *y, double *z)
Gets map.rotation of given part state.
EAPI Eina_Bool edje_edit_state_map_rotation_set (Evas_Object *obj, const char *part, const char *state, double value, double x, double y, double z)
Sets map.rotation of given part state.
EAPI int edje_edit_state_map_perspective_focal_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets map.perspective.focal value of given part state.
EAPI Eina_Bool edje_edit_state_map_perspective_focal_set (Evas_Object *obj, const char *part, const char *state, double value, int focal)
Sets map.perspective.focal value of given part state.
EAPI int edje_edit_state_map_perspective_zplane_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets map.perspective.zplane value of given part state.
EAPI Eina_Bool edje_edit_state_map_perspective_zplane_set (Evas_Object *obj, const char *part, const char *state, double value, int zplane)
Sets map.perspective.zplane value of given part state.
EAPI const char * edje_edit_state_map_rotation_center_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the part's name that is used as the center rotation.
EAPI Eina_Bool edje_edit_state_map_zoom_set (Evas_Object *obj, const char *part, const char *state, double value, double x, double y)
Sets map.zoom (x and y) values of given part state.
EAPI Eina_Bool edje_edit_state_map_zoom_get (Evas_Object *obj, const char *part, const char *state, double value, double *x, double *y)
Gets map.zoom (x and y) values of given part state.
EAPI Eina_Bool edje_edit_state_map_rotation_center_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source_part)
Sets the part that is used as the center of rotation when rotating the part with this description.
EAPI Eina_Bool edje_edit_state_map_point_color_set (Evas_Object *obj, const char *part, const char *state, double value, int idx, int r, int g, int b, int a)
Sets the color for vertex/point of the current part.
EAPI Eina_Bool edje_edit_state_map_point_color_get (Evas_Object *obj, const char *part, const char *state, double value, int idx, int *r, int *g, int *b, int *a)
Gets the color of given vertex/point of the current part.
EAPI Eina_Bool edje_edit_state_proxy_source_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source_name)
Sets the source part for given part state.
EAPI Eina_Stringshare * edje_edit_state_proxy_source_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the source name for given state of part.
EAPI Eina_Bool edje_edit_state_proxy_source_clip_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool clip)
Sets the source clip for given PROXY part state.
EAPI Eina_Bool edje_edit_state_proxy_source_clip_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the source clip for given PROXY part state.
EAPI Eina_Bool edje_edit_state_proxy_source_visible_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool visibility)
Sets the source visibility for given PROXY part state.
EAPI Eina_Bool edje_edit_state_proxy_source_visible_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the source visibility for given PROXY part state.
Text API
Functions to deal with text objects (see Edje Data Collection reference).
EAPI const char * edje_edit_state_text_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text of a part state.
EAPI Eina_Bool edje_edit_state_text_set (Evas_Object *obj, const char *part, const char *state, double value, const char *text)
Sets the text of a part state.
EAPI const char * edje_edit_state_font_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets font name for a given part state.
EAPI Eina_Bool edje_edit_state_font_set (Evas_Object *obj, const char *part, const char *state, double value, const char *font)
Sets font name for a given part state.
EAPI int edje_edit_state_text_size_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text size of a part state.
EAPI Eina_Bool edje_edit_state_text_size_set (Evas_Object *obj, const char *part, const char *state, double value, int size)
Sets the text size of a part state.
EAPI double edje_edit_state_text_align_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text horizontal align of a part state.
EAPI double edje_edit_state_text_align_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text vertical align of a part state.
EAPI Eina_Bool edje_edit_state_text_align_x_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Sets the text horizontal align of a part state.
EAPI Eina_Bool edje_edit_state_text_align_y_set (Evas_Object *obj, const char *part, const char *state, double value, double align)
Sets the text vertical align of a part state.
EAPI double edje_edit_state_text_elipsis_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text elipsis of a part state.
EAPI Eina_Bool edje_edit_state_text_elipsis_set (Evas_Object *obj, const char *part, const char *state, double value, double balance)
Sets the text vertical align of a part state.
EAPI Eina_Bool edje_edit_state_text_fit_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part fit it's container horizontally.
EAPI Eina_Bool edje_edit_state_text_fit_x_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fit)
Sets if the text part should fit it's container horizontally.
EAPI Eina_Bool edje_edit_state_text_fit_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part fit it's container vertically.
EAPI Eina_Bool edje_edit_state_text_fit_y_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool fit)
Sets if the text part should fit it's container vertically.
EAPI Eina_Bool edje_edit_state_text_min_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part forces the minimum horizontal size of the container to be equal to the minimum horizontal size of the text part.
EAPI Eina_Bool edje_edit_state_text_max_x_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part forces the maximum horizontal size of the container to be equal to the maximum horizontal size of the text part.
EAPI Eina_Bool edje_edit_state_text_min_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part forces the minimum vertical size of the container to be equal to the minimum vertical size of the text part.
EAPI Eina_Bool edje_edit_state_text_max_y_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the text part forces the maximum vertical size of the container to be equal to the maximum vertical size of the text part.
EAPI Eina_Bool edje_edit_state_text_min_x_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool v)
Sets if the text part forces the minimum horizontal size of the container to be equal to the minimum horizontal size of the text part.
EAPI Eina_Bool edje_edit_state_text_max_x_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool v)
Sets if the text part forces the maximum horizontal size of the container to be equal to the maximum horizontal size of the text part.
EAPI Eina_Bool edje_edit_state_text_min_y_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool v)
Sets if the text part forces the minimum vertical size of the container to be equal to the minimum vertical size of the text part.
EAPI Eina_Bool edje_edit_state_text_max_y_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool v)
Sets if the text part forces the maximum vertical size of the container to be equal to the maximum vertical size of the text part.
EAPI const char * edje_edit_state_text_style_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets style name for a given part state.
EAPI Eina_Bool edje_edit_state_text_style_set (Evas_Object *obj, const char *part, const char *state, double value, const char *style)
Sets style name for a given part state.
EAPI const char * edje_edit_state_text_text_source_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets part name, which used as text source.
EAPI Eina_Bool edje_edit_state_text_text_source_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source)
Sets the source text part for a given part.
EAPI const char * edje_edit_state_text_source_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets part name, which used as style text source.
EAPI Eina_Bool edje_edit_state_text_source_set (Evas_Object *obj, const char *part, const char *state, double value, const char *source)
Sets the source part which would be used as style for text for a given part.
EAPI const char * edje_edit_state_text_class_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the text class of the given part state.
EAPI Eina_Bool edje_edit_state_text_class_set (Evas_Object *obj, const char *part, const char *state, double value, const char *text_class)
Sets the text class of the given part state.
EAPI const char * edje_edit_state_text_repch_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the replacement character string of the given part state.
EAPI Eina_Bool edje_edit_state_text_repch_set (Evas_Object *obj, const char *part, const char *state, double value, const char *repch)
Sets the replacement character string of the given part state.
EAPI Eina_Bool edje_edit_state_text_size_range_min_max_get (Evas_Object *obj, const char *part, const char *state, double value, int *min, int *max)
Gets the min and max font size allowed for the text part.
EAPI Eina_Bool edje_edit_state_text_size_range_min_max_set (Evas_Object *obj, const char *part, const char *state, double value, int min, int max)
Sets the min and max font size allowed for the text part.
EAPI Eina_List * edje_edit_fonts_list_get (Evas_Object *obj)
Gets the list of all the fonts in the given edje.
EAPI Eina_Bool edje_edit_font_add (Evas_Object *obj, const char *path, const char *alias)
Adds a new font to the edje file.
EAPI Eina_Bool edje_edit_font_del (Evas_Object *obj, const char *alias)
Deletes font from the edje file.
EAPI const char * edje_edit_font_path_get (Evas_Object *obj, const char *alias)
Gets font path for a given font alias.
Image Set API
Functions to deal with image objects (see Edje Data Collection reference).
EAPI Eina_Bool edje_edit_image_set_exists (Evas_Object *obj, const char *image)
Checks if given image name is set of images or not.
EAPI int edje_edit_image_set_id_get (Evas_Object *obj, const char *name)
Gets id of image set.
EAPI Eina_Bool edje_edit_image_set_rename (Evas_Object *obj, const char *set, const char *new_set)
Renames image set.
EAPI Eina_List * edje_edit_image_set_list_get (Evas_Object *obj)
Gets the list of all the image sets in the given edje.
EAPI Eina_List * edje_edit_set_usage_list_get (Evas_Object *obj, const char *name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given set is used.
EAPI Eina_Bool edje_edit_image_set_add (Evas_Object *obj, const char *name)
Adds new image set.
EAPI Eina_Bool edje_edit_image_set_del (Evas_Object *obj, const char *name)
Deletes image set.
EAPI Eina_List * edje_edit_image_set_images_list_get (Evas_Object *obj, const char *name)
Gets the list of all images inside of given set in the given edje.
EAPI Eina_Bool edje_edit_image_set_image_add (Evas_Object *obj, const char *set_name, const char *name)
Adds image to set.
EAPI Eina_Bool edje_edit_image_set_image_del (Evas_Object *obj, const char *set_name, unsigned int place)
Deletes image on current position from set.
EAPI Eina_Bool edje_edit_image_set_image_min_get (Evas_Object *obj, const char *set_name, unsigned int place, int *w, int *h)
Gets min size of set's image.
EAPI Eina_Bool edje_edit_image_set_image_min_set (Evas_Object *obj, const char *set_name, unsigned int place, int w, int h)
Sets min size of set's image.
EAPI Eina_Bool edje_edit_image_set_image_max_get (Evas_Object *obj, const char *set_name, unsigned int place, int *w, int *h)
Gets max size of set's image.
EAPI Eina_Bool edje_edit_image_set_image_max_set (Evas_Object *obj, const char *set_name, unsigned int place, int w, int h)
Sets max size of set's image.
EAPI Eina_Bool edje_edit_image_set_image_border_get (Evas_Object *obj, const char *set_name, unsigned int place, int *l, int *r, int *b, int *t)
Gets border of set's image.
EAPI Eina_Bool edje_edit_image_set_image_border_set (Evas_Object *obj, const char *set_name, unsigned int place, int l, int r, int b, int t)
Sets border of set's image.
EAPI double edje_edit_image_set_image_border_scale_get (Evas_Object *obj, const char *set_name, unsigned int place)
Gets border scale of set's image.
EAPI Eina_Bool edje_edit_image_set_image_border_scale_set (Evas_Object *obj, const char *set_name, unsigned int place, double scale_by)
Sets border scale of set's image.
Images API
Functions to deal with image objects (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_images_list_get (Evas_Object *obj)
Gets the list of all the images in the given edje.
EAPI Eina_Bool edje_edit_image_add (Evas_Object *obj, const char *path)
Adds an new image to the image collection.
EAPI Eina_Bool edje_edit_image_del (Evas_Object *obj, const char *name)
Deletes an image from the image collection.
EAPI Eina_Bool edje_edit_image_replace (Evas_Object *obj, const char *name, const char *new_name)
Replaces one image in all descriptions.
EAPI Eina_Bool edje_edit_image_rename (Evas_Object *obj, const char *name, const char *new_name)
Renames image.
EAPI Eina_List * edje_edit_image_usage_list_get (Evas_Object *obj, const char *name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given image is used.
EAPI void edje_edit_image_usage_list_free (Eina_List *lst)
Frees an Eina_List of (Edje_Part_Image_Use *) allocated by an edje_edit_image_usage_list_get() or an edje_edit_vector_usage_list_get() function.
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object *obj, const char *name, int id)
Adds an image entry to the image collection.
EAPI const char * edje_edit_state_image_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets normal image name for a given part state.
EAPI Eina_Bool edje_edit_state_image_set (Evas_Object *obj, const char *part, const char *state, double value, const char *image)
Sets normal image for a given part state.
EAPI const char * edje_edit_state_vector_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets normal vector name for a given part state.
EAPI Eina_Bool edje_edit_state_vector_set (Evas_Object *obj, const char *part, const char *state, double value, const char *image)
Sets normal vector name for a given part state.
EAPI int edje_edit_image_id_get (Evas_Object *obj, const char *image_name)
Gets image id for a given image name.
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object *obj, const char *image)
Gets compression type for the given image.
EAPI Eina_Bool edje_edit_image_compression_type_set (Evas_Object *obj, const char *image, Edje_Edit_Image_Comp ic)
Sets compression type for the given image.
EAPI int edje_edit_image_compression_rate_get (Evas_Object *obj, const char *image)
Gets compression rate for the given image.
EAPI void edje_edit_state_image_border_get (Evas_Object *obj, const char *part, const char *state, double value, int *l, int *r, int *t, int *b)
Gets the image border of a part state.
EAPI Eina_Bool edje_edit_state_image_border_set (Evas_Object *obj, const char *part, const char *state, double value, int l, int r, int t, int b)
Sets the image border of a part state.
EAPI Eina_Bool edje_edit_state_image_border_scale_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the border scale value of a part state.
EAPI Eina_Bool edje_edit_state_image_border_scale_set (Evas_Object *obj, const char *part, const char *state, double value, Eina_Bool scale)
Sets the border scale value of a part state.
EAPI double edje_edit_state_image_border_scale_by_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the border scale by value of a part state.
EAPI Eina_Bool edje_edit_state_image_border_scale_by_set (Evas_Object *obj, const char *part, const char *state, double value, double scale)
Sets the border scale by value of a part state.
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets if the image center should be draw.
EAPI Eina_Bool edje_edit_state_image_border_fill_set (Evas_Object *obj, const char *part, const char *state, double value, unsigned char fill)
Sets if the image center should be draw.
EAPI Eina_List * edje_edit_state_tweens_list_get (Evas_Object *obj, const char *part, const char *state, double value)
Gets the list of all the tweens images in the given part state.
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Adds a new tween frame to the given part state.
EAPI Eina_Bool edje_edit_state_tween_insert_at (Evas_Object *obj, const char *part, const char *state, double value, const char *tween, int place)
Inserts a new tween frame to the given part state into a specific place.
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object *obj, const char *part, const char *state, double value, const char *tween)
Removes the first tween with the given name.
EAPI int edje_edit_vector_id_get (Evas_Object *obj, const char *vector_name)
Gets vector id for a given vector name.
Vectors API
Functions to deal with vector objects of images (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_vectors_list_get (Evas_Object *obj)
Gets the list of all the vectors in the given edje.
EAPI Eina_Bool edje_edit_vector_del (Evas_Object *obj, const char *name)
Deletes vector from the vector collection.
EAPI Eina_List * edje_edit_vector_usage_list_get (Evas_Object *obj, const char *name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given vector is used.
Sounds API
Functions to deal with sound objects (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_sound_samples_list_get (Evas_Object *obj)
Gets the list of all the sounds samples in the given edje.
EAPI Eina_List * edje_edit_sound_tones_list_get (Evas_Object *obj)
Gets the list of all the sounds tones in the given edje.
EAPI Eina_Bool edje_edit_sound_sample_add (Evas_Object *obj, const char *name, const char *snd_src)
Adds new sound sample to samples collection.
EAPI Eina_Bool edje_edit_sound_sample_del (Evas_Object *obj, const char *name)
Deletes sound sample from the collection.
EAPI Eina_Bool edje_edit_sound_tone_add (Evas_Object *obj, const char *name, int frequency)
Adds new tone to the collection.
EAPI Eina_Bool edje_edit_sound_tone_del (Evas_Object *obj, const char *name)
Deletes tone from the collection.
EAPI double edje_edit_sound_compression_rate_get (Evas_Object *obj, const char *sound)
Gets the sound quality compression.
EAPI Eina_Bool edje_edit_sound_compression_rate_set (Evas_Object *obj, const char *sound, double rate)
Sets the sound quality compression.
EAPI Eina_Bool edje_edit_sound_tone_frequency_set (Evas_Object *obj, const char *name, int frequency)
Sets the frequency of tone.
EAPI int edje_edit_sound_tone_frequency_get (Evas_Object *obj, const char *name)
Gets the frequency of tone.
EAPI Edje_Edit_Sound_Comp edje_edit_sound_compression_type_get (Evas_Object *obj, const char *name)
Gets the sound type compression.
EAPI Eina_Bool edje_edit_sound_compression_type_set (Evas_Object *obj, const char *name, Edje_Edit_Sound_Comp sc)
Sets the sound type compression.
EAPI Eina_Binbuf * edje_edit_sound_samplebuffer_get (Evas_Object *obj, const char *sample_name)
Gets the certain sound data from the edje object.
EAPI const char * edje_edit_sound_samplesource_get (Evas_Object *obj, const char *sample_name)
Gets the name of sample source.
Spectrum API
Functions to manage spectrum (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_spectrum_list_get (Evas_Object *obj)
Gets the list of all the spectrum in the given edje object.
EAPI Eina_Bool edje_edit_spectra_add (Evas_Object *obj, const char *name)
Adds a new spectra in the given edje object.
EAPI Eina_Bool edje_edit_spectra_del (Evas_Object *obj, const char *spectra)
Deletes the given spectra from the edje object.
EAPI Eina_Bool edje_edit_spectra_name_set (Evas_Object *obj, const char *spectra, const char *name)
Changes the name of the given spectra.
EAPI int edje_edit_spectra_stop_num_get (Evas_Object *obj, const char *spectra)
Gets the number of stops in the given spectra.
EAPI Eina_Bool edje_edit_spectra_stop_num_set (Evas_Object *obj, const char *spectra, int num)
Sets the number of stops in the given spectra.
EAPI Eina_Bool edje_edit_spectra_stop_color_get (Evas_Object *obj, const char *spectra, int stop_number, int *r, int *g, int *b, int *a, int *d)
Gets the colors of the given stop.
EAPI Eina_Bool edje_edit_spectra_stop_color_set (Evas_Object *obj, const char *spectra, int stop_number, int r, int g, int b, int a, int d)
Sets the colors of the given stop.
Programs API
Functions to deal with programs (see Edje Data Collection reference).
EAPI Eina_List * edje_edit_programs_list_get (Evas_Object *obj)
Gets the list of all the programs in the given edje object.
EAPI Eina_Bool edje_edit_program_add (Evas_Object *obj, const char *name)
Adds a new program to the edje file.
EAPI Eina_Bool edje_edit_program_del (Evas_Object *obj, const char *prog)
Removes the given program from the edje file.
EAPI Eina_Bool edje_edit_program_exist (Evas_Object *obj, const char *prog)
Checks if a program with the given name exist in the edje object.
EAPI Eina_Bool edje_edit_program_run (Evas_Object *obj, const char *prog)
Runs the given program.
EAPI Eina_Bool edje_edit_program_stop_all (Evas_Object *obj)
Stops all running programs.
EAPI Eina_Bool edje_edit_program_transition_state_set (Evas_Object *obj, const char *prog, double pos)
Sets parts into intermediate state of programs transition.
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object *obj, const char *prog, const char *new_name)
Sets a new name for the given program.
EAPI const char * edje_edit_program_source_get (Evas_Object *obj, const char *prog)
Gets source of a given program.
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object *obj, const char *prog, const char *source)
Sets source of the given program.
EAPI const char * edje_edit_program_signal_get (Evas_Object *obj, const char *prog)
Gets signal of a given program.
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object *obj, const char *prog, const char *signal)
Sets signal of the given program.
EAPI double edje_edit_program_in_from_get (Evas_Object *obj, const char *prog)
Gets in.from of a given program.
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object *obj, const char *prog, double seconds)
Sets in.from of a given program.
EAPI double edje_edit_program_in_range_get (Evas_Object *obj, const char *prog)
Gets in.range of a given program.
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object *obj, const char *prog, double seconds)
Sets in.range of a given program.
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object *obj, const char *prog)
Gets the action of a given program.
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object *obj, const char *prog, Edje_Action_Type action)
Sets the action of a given program.
EAPI Eina_List * edje_edit_program_targets_get (Evas_Object *obj, const char *prog)
Gets the list of the targets for the given program.
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object *obj, const char *prog, const char *target)
Adds a new target program to the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_target_insert_at (Evas_Object *obj, const char *prog, const char *target, int place)
Adds a new target program to certain place in list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object *obj, const char *prog, const char *target)
Deletes a target from the list of 'targets' in the given program.
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object *obj, const char *prog)
Clears the 'targets' list of the given program.
EAPI Eina_List * edje_edit_program_afters_get (Evas_Object *obj, const char *prog)
Gets the list of action that will be run after the give program.
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object *obj, const char *prog, const char *after)
Adds a new program name to the list of 'afters' in the given program.
EAPI Eina_Bool edje_edit_program_after_insert_at (Evas_Object *obj, const char *prog, const char *after, int place)
Adds a new program name into specific place in list of 'afters' in the given program.
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object *obj, const char *prog, const char *after)
Deletes the given program from the list of 'afters' of the program.
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object *obj, const char *prog)
Clears the 'afters' list of the given program.
EAPI const char * edje_edit_program_state_get (Evas_Object *obj, const char *prog)
Get the state for the given program.
EAPI const char * edje_edit_program_api_name_get (Evas_Object *obj, const char *prog)
Gets api's name of a program.
EAPI const char * edje_edit_program_api_description_get (Evas_Object *obj, const char *prog)
Gets api's description of a program.
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object *obj, const char *prog, const char *name)
Sets api's name of a program.
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object *obj, const char *prog, const char *description)
Sets api's description of a program.
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object *obj, const char *prog, const char *state)
Sets the state for the given program.
EAPI double edje_edit_program_value_get (Evas_Object *obj, const char *prog)
Gets the value of state for the given program.
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object *obj, const char *prog, double value)
Sets the value of state for the given program.
EAPI const char * edje_edit_program_state2_get (Evas_Object *obj, const char *prog)
Gets the state2 for the given program.
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object *obj, const char *prog, const char *state2)
Sets the state2 for the given program.
EAPI double edje_edit_program_value2_get (Evas_Object *obj, const char *prog)
Gets the value of state2 for the given program.
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object *obj, const char *prog, double value)
Sets the value2 of state for the given program.
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object *obj, const char *prog)
Gets the type of transition to use when apply animations.
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object *obj, const char *prog, Edje_Tween_Mode transition)
Sets the type of transition to use when apply animations.
EAPI double edje_edit_program_transition_value1_get (Evas_Object *obj, const char *prog)
Gets the interpolation value 1 of the transition.
EAPI Eina_Bool edje_edit_program_transition_value1_set (Evas_Object *obj, const char *prog, double value)
Sets the interpolation value 1 of the transition.
EAPI double edje_edit_program_transition_value2_get (Evas_Object *obj, const char *prog)
Gets the interpolation value 2 of the transition.
EAPI Eina_Bool edje_edit_program_transition_value2_set (Evas_Object *obj, const char *prog, double value)
Sets the interpolation value 2 of the transition.
EAPI double edje_edit_program_transition_value3_get (Evas_Object *obj, const char *prog)
Gets the interpolation value 3 of the transition.
EAPI Eina_Bool edje_edit_program_transition_value3_set (Evas_Object *obj, const char *prog, double value)
Sets the interpolation value 3 of the transition.
EAPI double edje_edit_program_transition_value4_get (Evas_Object *obj, const char *prog)
Gets the interpolation value 4 of the transition.
EAPI Eina_Bool edje_edit_program_transition_value4_set (Evas_Object *obj, const char *prog, double value)
Sets the interpolation value 4 of the transition.
EAPI double edje_edit_program_transition_time_get (Evas_Object *obj, const char *prog)
Gets the duration of the transition in seconds.
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object *obj, const char *prog, double seconds)
Sets the duration of the transition in seconds.
EAPI const char * edje_edit_program_sample_name_get (Evas_Object *obj, const char *prog)
Gets sample name of the program.
EAPI Eina_Bool edje_edit_program_sample_name_set (Evas_Object *obj, const char *prog, const char *name)
Sets sample name of the program.
EAPI const char * edje_edit_program_tone_name_get (Evas_Object *obj, const char *prog)
Gets tone name of the program.
EAPI Eina_Bool edje_edit_program_tone_name_set (Evas_Object *obj, const char *prog, const char *name)
Sets tone name of the program.
EAPI double edje_edit_program_sample_speed_get (Evas_Object *obj, const char *prog)
Gets sample speed of the program.
EAPI Eina_Bool edje_edit_program_sample_speed_set (Evas_Object *obj, const char *prog, double speed)
Sets sample speed of the program.
EAPI double edje_edit_program_tone_duration_get (Evas_Object *obj, const char *prog)
Gets tone duration of the program.
EAPI Eina_Bool edje_edit_program_tone_duration_set (Evas_Object *obj, const char *prog, double duration)
Sets tone duration of the program.
EAPI unsigned char edje_edit_program_channel_get (Evas_Object *obj, const char *prog)
Gets sample channel of the program.
EAPI Eina_Bool edje_edit_program_channel_set (Evas_Object *obj, const char *prog, Edje_Channel channel)
Sets sample channel of the program.
EAPI const char * edje_edit_program_filter_part_get (Evas_Object *obj, const char *prog)
Gets filter part name of the program.
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object *obj, const char *prog, const char *filter_part)
Sets filter part name of the program.
EAPI const char * edje_edit_program_filter_state_get (Evas_Object *obj, const char *prog)
Gets filter state of the program.
EAPI Eina_Bool edje_edit_program_filter_state_set (Evas_Object *obj, const char *prog, const char *filter_state)
Sets filter state of the program.
Scripts API
Functions to deal with embryo scripts (see Edje Data Collection reference).
EAPI char * edje_edit_script_get (Evas_Object *obj)
Gets the Embryo script for the group of the given object.
EAPI Eina_Bool edje_edit_script_set (Evas_Object *obj, const char *code)
Sets the code for the group script.
EAPI char * edje_edit_script_program_get (Evas_Object *obj, const char *prog)
Gets the Embryo script for the given program.
EAPI Eina_Bool edje_edit_script_program_set (Evas_Object *obj, const char *prog, const char *code)
Sets the Embryo script for the given program.
EAPI Eina_Bool edje_edit_script_compile (Evas_Object *obj)
Compiles the Embryo script for the given object.
EAPI const Eina_List * edje_edit_script_error_list_get (Evas_Object *obj)
Gets the list of errors resulting from the last script build.
EAPI const char * edje_edit_source_generate (Evas_Object *obj)
Returns source code of the current edje edit object.
EAPI const char * edje_edit_object_source_generate (Evas_Object *obj)
Returns source code of the current edje edit object.
EAPI char * edje_edit_full_source_generate (Evas_Object *obj)
Returns source code of all collections.
EAPI const char * edje_edit_data_source_generate (Evas_Object *obj)
Returns source code of global block data.
EAPI Eina_List * edje_edit_object_color_class_list_get (Evas_Object *obj)
Gets a list of color classes which given object use.
EAPI const char * edje_edit_color_classes_source_generate (Evas_Object *obj, Eina_List *color_classes)
Gets the source code for given color classes.
Error API
Functions to deal with error messages (see Edje Data Collection reference).
#define EAPI
#define EAPI
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_CURRENTLY_USED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_REFERENCED
EAPI Eina_Error EDJE_EDIT_ERROR_GROUP_DOES_NOT_EXIST
Detailed Description
Functions to deal with edje internal object.
Don't use in standard situations. The use of any of the edje_edit_* functions can break your theme ability, remember that the program must be separated from the interface!
This was intended ONLY for use in an actual edje editor program. Unless you are writing one of these, do NOT use this API here.
The API can be used to query or set every part of an edje object in real time. You can manage every aspect of parts, part states, programs, script and whatever is contained in the edje file. For a reference of what all parameter means look at the complete Edje Data Collection reference.
Don't forget to free all the strings and the lists returned by any edje_edit_*() functions using edje_edit_string_free() and edje_edit_string_list_free() when you don't need anymore.
Example: print all the part in a loaded edje_object
Eina_List *parts, *l;
char *part;
parts = edje_edit_parts_list_get(edje_object);
EINA_LIST_FOREACH(parts, l, part)
{
   printf("Part: %s\n", part);
}
edje_edit_string_list_free(parts);
Example: Change the color of a rect inside an edje file
Evas_Object *edje;
edje = edje_edit_object_add(evas);
edje_object_file_set(edje, "edj/file/name", "group to load");
edje_edit_state_color_set(edje, "MyRectName", "default", 0.00, 255, 255, 0, 255);
edje_edit_save(edje);
Typedef Documentation
Edje_Edit_Image_Comp
typedef enum _Edje_Edit_Image_Comp Edje_Edit_Image_Comp
Compression type for the image.
Edje Data Collection reference
Edje_Edit_Select_Mode
typedef enum _Edje_Edit_Select_Mode Edje_Edit_Select_Mode
Mode for a textblock part.
Edje Data Collection reference
Edje_Edit_Sound_Comp
typedef enum _Edje_Edit_Sound_Comp Edje_Edit_Sound_Comp
Sound type compression.
Edje Data Collection reference
Edje_Edit_Entry_Mode
typedef enum _Edje_Edit_Entry_Mode Edje_Edit_Entry_Mode
Mode for a textblock part.
Edje Data Collection reference
Edje_Edit_Script_Error
Edje_Edit_Script_Error
This is structure used for the list of errors that resulted from the last attempt to rebuild the Embryo script for the edited group.
See also
edje_edit_script_error_list_get()
Edje_Part_Image_Use
Edje_Part_Image_Use
This is structure used for the list of group-part-state triplets where certain image is being used and pointed.
See also
edje_edit_image_usage_list_get()
edje_edit_vector_usage_list_get()
edje_edit_image_usage_list_free()
Edje_Edit_Limit
Edje_Edit_Limit
This is structure used for list with the item names inside the limits block.
See also
edje_edit_group_limits_vertical_list_get()
edje_edit_group_limits_horizontal_list_get()
edje_edit_group_limits_vertical_del()
edje_edit_group_limits_horizontal_del()
edje_edit_group_limits_vertical_add()
edje_edit_group_limits_horizontal_add()
edje_edit_limits_list_free()
Enumeration Type Documentation
_Edje_Edit_Image_Comp
enum _Edje_Edit_Image_Comp
Compression type for the image.
Edje Data Collection reference
_Edje_Edit_Select_Mode
enum _Edje_Edit_Select_Mode
Mode for a textblock part.
Edje Data Collection reference
_Edje_Edit_Sound_Comp
enum _Edje_Edit_Sound_Comp
Sound type compression.
Edje Data Collection reference
_Edje_Edit_Entry_Mode
enum _Edje_Edit_Entry_Mode
Mode for a textblock part.
Edje Data Collection reference
Function Documentation
edje_edit_object_add()
EAPI Evas_Object* edje_edit_object_add (Evas * e)
Adds an editable Edje object to the canvas.
An Edje_Edit object is, for the most part, a standard Edje object. Only difference is you can use the Edje_Edit API on them.
Parameters
e Evas canvas where to add the object.
Returns
An Evas_Object of type Edje_Edit, or NULL if an error occurred.
References EINA_SAFETY_ON_FALSE_RETURN_VAL, and EVAS_CANVAS_CLASS.
Referenced by edje_edit_clean_save_as().
edje_edit_string_list_free()
EAPI void edje_edit_string_list_free (Eina_List * lst)
Frees a generic Eina_List of (char *) allocated by an edje_edit_*_get() function.
Parameters
lst List of strings to free.
References eina_list_data_get(), eina_list_remove(), and eina_stringshare_del().
edje_edit_string_free()
EAPI void edje_edit_string_free (const char * str)
Frees a generic string (char *) allocated by an edje_edit_*_get() function.
Parameters
str String to free.
References eina_stringshare_del().
edje_edit_compiler_get()
EAPI const char* edje_edit_compiler_get (Evas_Object * obj)
Gets the name of the program that compiled the edje file.
Can be 'edje_cc' or 'edje_edit'
Parameters
obj Object being edited.
Returns
Compiler stored in the Edje file
References eina_stringshare_add().
edje_edit_save()
EAPI Eina_Bool edje_edit_save (Evas_Object * obj)
Saves the modified edje object back to his file.
Use this function when you are done with your editing, all the change made to the current loaded group will be saved back to the original file.
Note
Source for the whole file will be auto generated and will overwrite any previously stored source.
Parameters
obj Object to save back to the file it was loaded from.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_TRUE.
edje_edit_save_all()
EAPI Eina_Bool edje_edit_save_all (Evas_Object * obj)
Saves every group back into the file.
Parameters
obj Object to save.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_save()
References EINA_TRUE.
edje_edit_clean_save_as()
EAPI Eina_Bool edje_edit_clean_save_as (Evas_Object * obj, const char * new_file_name)
Saves every group into new file.
Use this function when you need clean eet dictionary in .edj file from unnecessary text entries (e.g. names of deleted groups etc.).
Parameters
obj Object to save.
new_file_name Where to save object. File should not exist, otherwise EINA_FALSE will be returned.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_save()
References ecore_file_exists(), edje_edit_object_add(), edje_object_file_set(), eet_close(), EET_FILE_MODE_READ, EET_FILE_MODE_WRITE, eet_list(), eet_open(), eet_read(), eet_read_direct(), eet_write(), EINA_FALSE, eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), EINA_TRUE, and ERR.
edje_edit_without_source_save()
EAPI Eina_Bool edje_edit_without_source_save (Evas_Object * obj, Eina_Bool current_group)
Saves the group(s) back to the file, without generation source code.
This function saves changes in group(s) back into the edj file. Process of saving takes a bit time in compare with
See also
edje_edit_save() and
edje_edit_save_all(), because this function DOES NOT generate source code for groups.
Note
With using this function all source code will be erased. And DOES NOT generated new code. In attempt to decompile edj file, which was saved with using this functions will unpacked only resources(like fonts, images, sounds). If needed saving source code into file, please use
See also
edje_edit_save() or
edje_edit_save_all().
Parameters
obj Object to save back to the file it was loaded from.
current_group EINA_TRUE if needed save only group which loaded with obj, or EINA_FALSE for save all groups, which exists in edj file.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References eet_data_write(), EET_FILE_MODE_READ_WRITE, EINA_FALSE, EINA_TRUE, and ERR.
edje_edit_print_internal_status()
EAPI void edje_edit_print_internal_status (Evas_Object * obj)
Prints on standard output many information about the internal status of the edje object.
This is probably only useful to debug.
Parameters
obj Object being edited.
References eina_strbuf_free().
edje_edit_group_add()
EAPI Eina_Bool edje_edit_group_add (Evas_Object * obj, const char * name)
Adds an edje (empty) group to an edje object's group set.
Parameters
obj The pointer to edje object.
name The name of the group.
Returns
EINA_TRUE If it could allocate memory to the part group added or zero if not.
This function adds, at run time, one more group, which will reside in memory, to the group set found in the .edj file which obj was loaded with. This group can be manipulated by other API functions, like edje_edit_part_add(), for example. If desired, the new group can be actually committed the respective .edj by use of edje_edit_save().
References EINA_FALSE, eina_hash_direct_add(), eina_hash_find(), eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_list_prepend(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_group_copy()
EAPI Eina_Bool edje_edit_group_copy (Evas_Object * obj, const char * group_name, const char * copy_name)
Copies whole group and all it's data into separate group.
Parameters
obj The pointer to edje object.
group_name The name of the group.
copy_name The name of the new group that is a copy.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function copy, at run time, a whole group, which will reside in memory, to the group set found in the .edj file which obj was loaded with. This group can be manipulated by other API functions, like edje_edit_part_add(), for example.
You need to save everything to make sure the file won't have broken references the next time is loaded.
See also
edje_edit_save_all(), edje_edit_without_source_save().
Attention
This group will copy the whole group and this operation can't be undone as all references to the group will be added to the file. (for example all scripts will be written to the file directly)
References eet_data_read(), eet_data_write(), EET_FILE_MODE_READ_WRITE, eet_list(), eet_read(), eet_write(), EINA_FALSE, eina_hash_direct_add(), eina_hash_find(), eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_str_split(), and eina_stringshare_add().
edje_edit_group_del()
EAPI Eina_Bool edje_edit_group_del (Evas_Object * obj, const char * group_name)
Deletes the specified group from the edje file.
Parameters
obj The pointer to the edje object.
group_name Group to delete.
Returns
EINA_TRUE on success, EINA_FALSE on failure.
This function deletes the given group from the file obj is set to. This operation can't be undone as all references to the group are removed from the file. This function may fail if the group to be deleted is currently in use. You need to save everything to make sure the file won't have broken references the next time is loaded.
See also
edje_edit_save_all(), edje_edit_without_source_save().
Attention
be careful, if you deleting group, it will delete all it's aliases also, if you deleting alias, then it will delete alias only.
References eet_delete(), EET_FILE_MODE_READ_WRITE, eet_list(), EINA_FALSE, eina_hash_del(), eina_hash_find(), EINA_LIST_FOREACH, eina_list_remove_list(), and EINA_TRUE.
edje_edit_group_exist()
EAPI Eina_Bool edje_edit_group_exist (Evas_Object * obj, const char * group)
Checks if a group with the given name exist in the edje.
Parameters
obj Object being edited.
group Group name to check for.
Returns
EINA_TRUE if group exists, EINA_FALSE if not.
References EINA_FALSE, eina_hash_find(), and EINA_TRUE.
Referenced by edje_edit_group_name_set().
edje_edit_group_name_set()
EAPI Eina_Bool edje_edit_group_name_set (Evas_Object * obj, const char * new_name)
Sets a new name for the current open group.
You can only rename a group that is currently loaded Note that the relative getter function don't exist as it doesn't make sense ;)
Parameters
obj Object being edited.
new_name New name for the group.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_group_exist(), EINA_FALSE, eina_hash_find(), eina_hash_move(), eina_stringshare_add(), eina_stringshare_replace(), and EINA_TRUE.
edje_edit_group_min_w_get()
EAPI int edje_edit_group_min_w_get (Evas_Object * obj)
Gets the group minimum width.
Parameters
obj Object being edited.
Returns
The minimum width set for the group. -1 if an error occurred.
edje_edit_group_min_w_set()
EAPI Eina_Bool edje_edit_group_min_w_set (Evas_Object * obj, int w)
Sets the group minimum width.
Parameters
obj Object being edited.
w New minimum width for the group.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_group_min_h_get()
EAPI int edje_edit_group_min_h_get (Evas_Object * obj)
Gets the group minimum height.
Parameters
obj Object being edited.
Returns
The minimum height set for the group. -1 if an error occurred.
edje_edit_group_min_h_set()
EAPI Eina_Bool edje_edit_group_min_h_set (Evas_Object * obj, int h)
Sets the group minimum height.
Parameters
obj Object being edited.
h New minimum height for the group.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_group_max_w_get()
EAPI int edje_edit_group_max_w_get (Evas_Object * obj)
Gets the group maximum width.
Parameters
obj Object being edited.
Returns
The maximum width set for the group. -1 if an error occurred.
edje_edit_group_max_w_set()
EAPI Eina_Bool edje_edit_group_max_w_set (Evas_Object * obj, int w)
Sets the group maximum width.
Parameters
obj Object being edited.
w New maximum width for the group.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_group_max_h_get()
EAPI int edje_edit_group_max_h_get (Evas_Object * obj)
Gets the group maximum height.
Parameters
obj Object being edited.
Returns
The maximum height set for the group. -1 if an error occurred.
edje_edit_group_max_h_set()
EAPI Eina_Bool edje_edit_group_max_h_set (Evas_Object * obj, int h)
Sets the group maximum height.
Parameters
obj Object being edited.
h New maximum height for the group.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_group_broadcast_signal_get()
EAPI Eina_Bool edje_edit_group_broadcast_signal_get (Evas_Object * obj)
Gets the group broadcast_signal.
Parameters
obj Object being edited.
Returns
EINA_FALSE if group not accept broadcast signal, EINA_TRUE otherwise (Default to true since 1.1.).
Since
1.11
References EINA_TRUE.
edje_edit_group_broadcast_signal_set()
EAPI Eina_Bool edje_edit_group_broadcast_signal_set (Evas_Object * obj, Eina_Bool bs)
Sets the group broadcast signal.
Parameters
obj Object being edited.
bs EINA_TRUE if group will accept broadcast signal, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_group_limits_vertical_list_get()
EAPI Eina_List* edje_edit_group_limits_vertical_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the vertical limits block at the group level.
Parameters
obj Object being edited.
Returns
List of strings, each being a name of vertical limit in the limits block for the group.
edje_edit_group_limits_vertical_del()
EAPI Eina_Bool edje_edit_group_limits_vertical_del (Evas_Object * obj, const char * name, int value)
Deletes given pair name-value from the vertical limits block at the group level.
Parameters
obj Object being edited.
name Limit name.
value Limit value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_group_limits_vertical_add()
EAPI Eina_Bool edje_edit_group_limits_vertical_add (Evas_Object * obj, const char * name, int value)
Adds given pair name-value to the vertical limits block at the group level.
Parameters
obj Object being edited.
name Limit name.
value Limit value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_group_limits_horizontal_list_get()
EAPI Eina_List* edje_edit_group_limits_horizontal_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the horizontal limits block at the group level.
Parameters
obj Object being edited.
Returns
List of strings, each being a name of horizontal limit in the limits block for the group.
edje_edit_group_limits_horizontal_del()
EAPI Eina_Bool edje_edit_group_limits_horizontal_del (Evas_Object * obj, const char * name, int value)
Deletes given pair name-value from the horizontal limits block at the group level.
Parameters
obj Object being edited.
name Limit name.
value Limit value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_group_limits_horizontal_add()
EAPI Eina_Bool edje_edit_group_limits_horizontal_add (Evas_Object * obj, const char * name, int value)
Adds given pair name-value to the horizontal limits block at the group level.
Parameters
obj Object being edited.
name Limit name.
value Limit value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
edje_edit_limits_list_free()
EAPI void edje_edit_limits_list_free (Eina_List * lst)
Frees an Eina_List of (Edje_Edit_List *) allocated by an edje_edit_limits_vertical_list_get() or edje_edit_limits_horizontal_list_get() functions.
Parameters
lst List to free.
References eina_list_data_get(), EINA_LIST_FREE, eina_stringshare_del(), and _Edje_Edit_Limit::name.
edje_edit_group_aliases_get()
EAPI Eina_List* edje_edit_group_aliases_get (Evas_Object * obj, const char * group_name)
Retrieves a list of aliases for this group.
If given group name is an alias name then this function will return NULL.
Attention
After you done using returned list, please use edje_edit_string_list_free to free this list.
Parameters
obj Object being edited.
group_name Group name or alias.
Returns
List of strings, each being a name of alias of given group or alias name.
References eina_hash_find(), eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_list_append(), and eina_stringshare_add().
edje_edit_group_alias_is()
EAPI Eina_Bool edje_edit_group_alias_is (Evas_Object * obj, const char * alias_name)
Checks if this group is an alias name.
Parameters
obj Object being edited.
alias_name Group name that is alias.
Returns
EINA_TRUE if alias, EINA_FALSE otherwise.
References EINA_FALSE, and eina_hash_find().
edje_edit_group_aliased_get()
EAPI const char* edje_edit_group_aliased_get (Evas_Object * obj, const char * alias_name)
Returns the main group name that is aliased by given alias name.
Attention
After you done using this string, please use edje_edit_string_free to free this string.
Parameters
obj Object being edited.
alias_name Group name that is alias.
Returns
name of the main group that is being aliased.
References eina_hash_find(), eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), and eina_stringshare_add().
edje_edit_group_alias_add()
EAPI Eina_Bool edje_edit_group_alias_add (Evas_Object * obj, const char * group_name, const char * alias_name)
Adds new alias to the given group.
Attention
when aliasing a group, be sure that the given group_name is no an alias.
Parameters
obj Object being edited.
group_name Group name that is being aliased.
alias_name Group name that is alias.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_direct_add(), eina_hash_find(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_data_list_get()
EAPI Eina_List* edje_edit_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the global data block for the file.
References eina_hash_iterator_key_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_list_append(), and eina_stringshare_add().
edje_edit_data_add()
EAPI Eina_Bool edje_edit_data_add (Evas_Object * obj, const char * itemname, const char * value)
Creates a new global data object in the given edje file.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_add(), eina_hash_find(), eina_hash_string_small_new(), eina_stringshare_add(), eina_stringshare_del(), and EINA_TRUE.
edje_edit_data_del()
EAPI Eina_Bool edje_edit_data_del (Evas_Object * obj, const char * itemname)
Deletes the given data object from edje.
Parameters
obj Object being edited.
itemname Data entry to remove from the global data block.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_del(), eina_hash_find(), and EINA_TRUE.
edje_edit_data_value_get()
EAPI const char* edje_edit_data_value_get (Evas_Object * obj, const char * itemname)
Gets the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to fetch the value for.
Returns
Value of the given entry, or NULL if not found.
References eina_hash_find(), and eina_stringshare_add().
edje_edit_data_value_set()
EAPI Eina_Bool edje_edit_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Sets the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of data entry to change the value.
value New value for the entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_data_name_set()
EAPI Eina_Bool edje_edit_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Changes the name of the given data object.
Parameters
obj Object being edited.
itemname Data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and eina_hash_move().
edje_edit_group_data_list_get()
EAPI Eina_List* edje_edit_group_data_list_get (Evas_Object * obj)
Retrieves a list with the item names inside the data block at the group level.
Parameters
obj Object being edited.
Returns
List of strings, each being a name entry in the data block for the group.
References eina_hash_iterator_key_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_list_append(), and eina_stringshare_add().
edje_edit_group_data_add()
EAPI Eina_Bool edje_edit_group_data_add (Evas_Object * obj, const char * itemname, const char * value)
Creates a new data object in the given edje file belonging to the current group.
If another data entry with the same name exists, nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
itemname Name for the new data entry.
value Value for the new data entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_add(), eina_hash_find(), eina_hash_string_small_new(), eina_stringshare_add(), eina_stringshare_del(), and EINA_TRUE.
edje_edit_group_data_del()
EAPI Eina_Bool edje_edit_group_data_del (Evas_Object * obj, const char * itemname)
Deletes the given data object from the group.
Parameters
obj Object being edited.
itemname Name of the data entry to remove.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_del(), eina_hash_find(), and EINA_TRUE.
edje_edit_group_data_value_get()
EAPI const char* edje_edit_group_data_value_get (Evas_Object * obj, const char * itemname)
Gets the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry.
Returns
Value of the data entry or NULL if not found.
References eina_hash_find(), and eina_stringshare_add().
edje_edit_group_data_value_set()
EAPI Eina_Bool edje_edit_group_data_value_set (Evas_Object * obj, const char * itemname, const char * value)
Sets the data associated with the given itemname.
Parameters
obj Object being edited.
itemname Name of the data entry to set the value.
value Value to set for the data entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_group_data_name_set()
EAPI Eina_Bool edje_edit_group_data_name_set (Evas_Object * obj, const char * itemname, const char * newname)
Changes the name of the given data object.
Parameters
obj Object being edited.
itemname Name of the data entry to rename.
newname New name for the data entry.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and eina_hash_move().
edje_edit_size_classes_list_get()
EAPI Eina_List* edje_edit_size_classes_list_get (Evas_Object * obj)
Gets the list of all the Size Classes in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being one size class. The return value should be freed with edje_edit_string_list_free().
See also
edje_edit_string_list_free()
Since
1.18
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_size_class_add()
EAPI Eina_Bool edje_edit_size_class_add (Evas_Object * obj, const char * name)
Creates a new size class object in the given edje.
If class is already exist then nothing is created and EINA_FALSE returned.
Parameters
obj Object being edited.
name Name for the new size class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_append(), EINA_LIST_FOREACH, eina_stringshare_add(), and EINA_TRUE.
edje_edit_size_class_del()
EAPI Eina_Bool edje_edit_size_class_del (Evas_Object * obj, const char * name)
Deletes size class object from edje.
Parameters
obj Object being edited.
name Size class to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, eina_list_remove(), and EINA_TRUE.
edje_edit_size_class_name_set()
EAPI Eina_Bool edje_edit_size_class_name_set (Evas_Object * obj, const char * name, const char * newname)
Changes name of a size class.
Parameters
obj Object being edited.
name Size class to rename.
newname New name for the size class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_size_class_min_w_get()
EAPI Evas_Coord edje_edit_size_class_min_w_get (Evas_Object * obj, const char * class_name)
Returns width min size of specified size class.
Parameters
obj Object being edited.
class_name Size class to fetch values.
Returns
Evas_Coord.
Since
1.18
edje_edit_size_class_min_w_set()
EAPI Eina_Bool edje_edit_size_class_min_w_set (Evas_Object * obj, const char * class_name, Evas_Coord size)
Sets width min size of specified size class.
Parameters
obj Object being edited.
class_name Size class to set values.
size Size which is greater or equal than zero (0).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_size_class_max_w_get()
EAPI Evas_Coord edje_edit_size_class_max_w_get (Evas_Object * obj, const char * class_name)
Returns width max size of specified size class.
Parameters
obj Object being edited.
class_name Size class to fetch values.
Returns
Evas_Coord.
Since
1.18
edje_edit_size_class_max_w_set()
EAPI Eina_Bool edje_edit_size_class_max_w_set (Evas_Object * obj, const char * class_name, Evas_Coord size)
Sets width max size of specified size class.
Parameters
obj Object being edited.
class_name Size class to set values.
size Size which is greater or equal than zero (0).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_size_class_min_h_get()
EAPI Evas_Coord edje_edit_size_class_min_h_get (Evas_Object * obj, const char * class_name)
Returns height min size of specified size class.
Parameters
obj Object being edited.
class_name Size class to fetch values.
Returns
Evas_Coord.
Since
1.18
edje_edit_size_class_min_h_set()
EAPI Eina_Bool edje_edit_size_class_min_h_set (Evas_Object * obj, const char * class_name, Evas_Coord size)
Sets height min size of specified size class.
Parameters
obj Object being edited.
class_name Size class to set values.
size Size which is greater or equal than zero (0).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_size_class_max_h_get()
EAPI Evas_Coord edje_edit_size_class_max_h_get (Evas_Object * obj, const char * class_name)
Returns height max size of specified size class.
Parameters
obj Object being edited.
class_name Size class to fetch values.
Returns
Evas_Coord (-1 is default value).
Since
1.18
edje_edit_size_class_max_h_set()
EAPI Eina_Bool edje_edit_size_class_max_h_set (Evas_Object * obj, const char * class_name, Evas_Coord size)
Sets height max size of specified size class.
Parameters
obj Object being edited.
class_name Size class to set values.
size Size which is greater or equal minus one (-1, which is default value).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_text_classes_list_get()
EAPI Eina_List* edje_edit_text_classes_list_get (Evas_Object * obj)
Gets the list of all the Text Classes in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being one text class. The return value should be freed with edje_edit_string_list_free().
See also
edje_edit_string_list_free()
Since
1.18
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_text_class_add()
EAPI Eina_Bool edje_edit_text_class_add (Evas_Object * obj, const char * name)
Creates a new text class object in the given edje.
If class is already exist then nothing is created and EINA_FALSE returned.
Parameters
obj Object being edited.
name Name for the new text class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_append(), EINA_LIST_FOREACH, eina_stringshare_add(), and EINA_TRUE.
edje_edit_text_class_del()
EAPI Eina_Bool edje_edit_text_class_del (Evas_Object * obj, const char * name)
Deletes text class object from edje.
Parameters
obj Object being edited.
name Text class to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, eina_list_remove(), and EINA_TRUE.
edje_edit_text_class_name_set()
EAPI Eina_Bool edje_edit_text_class_name_set (Evas_Object * obj, const char * name, const char * newname)
Changes name of a text class.
Parameters
obj Object being edited.
name Text class to rename.
newname New name for the text class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_text_class_font_get()
EAPI Eina_Stringshare* edje_edit_text_class_font_get (Evas_Object * obj, const char * class_name)
Returns font name of specified text class.
Parameters
obj Object being edited.
class_name Text class to fetch values.
Returns
font name in case of success, NULL otherwise.
Since
1.18
References EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_text_class_font_set()
EAPI Eina_Bool edje_edit_text_class_font_set (Evas_Object * obj, const char * class_name, const char * font)
Sets font for the given text class.
NULL is possible value.
Parameters
obj Object being edited.
class_name Text class to set values.
font Name of font.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_text_class_size_get()
EAPI Evas_Font_Size edje_edit_text_class_size_get (Evas_Object * obj, const char * class_name)
Returns font size of specified text class.
Parameters
obj Object being edited.
class_name Text class to fetch values.
Returns
Evas_Font_Size.
Since
1.18
References EINA_FALSE, and EINA_LIST_FOREACH.
edje_edit_text_class_size_set()
EAPI Eina_Bool edje_edit_text_class_size_set (Evas_Object * obj, const char * class_name, Evas_Font_Size size)
Sets font size for specified text class.
Parameters
obj Object being edited.
class_name Text class to set values.
size Font size which is greater or equal than zero (0).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_color_classes_list_get()
EAPI Eina_List* edje_edit_color_classes_list_get (Evas_Object * obj)
Gets the list of all the Color Classes in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being one color class.
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_color_class_add()
EAPI Eina_Bool edje_edit_color_class_add (Evas_Object * obj, const char * name)
Creates a new color class object in the given edje.
If another class with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
name Name for the new color class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_append(), EINA_LIST_FOREACH, eina_stringshare_add(), and EINA_TRUE.
edje_edit_color_class_del()
EAPI Eina_Bool edje_edit_color_class_del (Evas_Object * obj, const char * name)
Deletes the given class object from edje.
Parameters
obj Object being edited.
name Color class to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, eina_list_remove(), and EINA_TRUE.
edje_edit_color_class_colors_get()
EAPI Eina_Bool edje_edit_color_class_colors_get (Evas_Object * obj, const char * class_name, int * r, int * g, int * b, int * a, int * r2, int * g2, int * b2, int * a2, int * r3, int * g3, int * b3, int * a3)
Gets all the colors that compose the class.
You can pass NULL to colors you are not interested in.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_color_class_colors_set()
EAPI Eina_Bool edje_edit_color_class_colors_set (Evas_Object * obj, const char * class_name, int r, int g, int b, int a, int r2, int g2, int b2, int a2, int r3, int g3, int b3, int a3)
Sets the colors for the given color class.
If you set a color to -1 it will not be touched.
Parameters
obj Object being edited.
class_name Color class to fetch values.
r Red component of main color.
g Green component of main color.
b Blue component of main color.
a Alpha component of main color.
r2 Red component of secondary color.
g2 Green component of secondary color.
b2 Blue component of secondary color.
a2 Alpha component of secondary color.
r3 Red component of tertiary color.
g3 Green component of tertiary color.
b3 Blue component of tertiary color.
a3 Alpha component of tertiary color.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_color_class_name_set()
EAPI Eina_Bool edje_edit_color_class_name_set (Evas_Object * obj, const char * name, const char * newname)
Changes the name of a color class.
Parameters
obj Object being edited.
name Color class to rename.
newname New name for the color class.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_color_class_description_get()
EAPI Eina_Stringshare* edje_edit_color_class_description_get (Evas_Object * obj, const char * class_name)
Gets the description of a color class.
Parameters
obj Object being edited.
class_name Color class to get the description of.
Returns
The description of the color class or NULL if not found
Since
1.14
References EINA_LIST_FOREACH, EINA_SAFETY_ON_NULL_RETURN_VAL, and eina_streq().
edje_edit_color_class_description_set()
EAPI Eina_Bool edje_edit_color_class_description_set (Evas_Object * obj, const char * class_name, const char * desc)
Changes the description of a color class.
Parameters
obj Object being edited.
class_name Color class to edit.
desc New description for the color class
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EINA_FALSE, EINA_LIST_FOREACH, EINA_SAFETY_ON_NULL_RETURN_VAL, eina_streq(), eina_stringshare_replace(), and EINA_TRUE.
edje_edit_styles_list_get()
EAPI Eina_List* edje_edit_styles_list_get (Evas_Object * obj)
Gets the list of all the text styles in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a text style.
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_style_add()
EAPI Eina_Bool edje_edit_style_add (Evas_Object * obj, const char * style)
Creates a new text style object in the given edje.
If another style with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Name for the new style.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_append(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_style_del()
EAPI Eina_Bool edje_edit_style_del (Evas_Object * obj, const char * style)
Deletes the given text style and all the child tags.
Parameters
obj Object being edited.
style Style to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_remove(), EINA_TRUE, and evas_textblock_style_free().
edje_edit_style_tags_list_get()
EAPI Eina_List* edje_edit_style_tags_list_get (Evas_Object * obj, const char * style)
Gets the list of all the tags name in the given text style.
Parameters
obj Object being edited.
style Style to get the tags for.
Returns
List of strings, each being one tag in the given style.
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_style_tag_value_get()
EAPI const char* edje_edit_style_tag_value_get (Evas_Object * obj, const char * style, const char * tag)
Gets the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag being.
tag Tag to get the value for.
Returns
Value of the given tag.
References eina_stringshare_add().
edje_edit_style_tag_value_set()
EAPI Eina_Bool edje_edit_style_tag_value_set (Evas_Object * obj, const char * style, const char * tag, const char * new_value)
Sets the value of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to change.
tag Name of the tag to set the value for.
new_value Value for the tag.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_style_tag_name_set()
EAPI Eina_Bool edje_edit_style_tag_name_set (Evas_Object * obj, const char * style, const char * tag, const char * new_name)
Sets the name of the given tag.
Parameters
obj Object being edited.
style Style containing the tag to rename.
tag Tag to rename.
new_name New name for the tag.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_style_tag_add()
EAPI Eina_Bool edje_edit_style_tag_add (Evas_Object * obj, const char * style, const char * tag_name)
@
Adds a new tag to the given text style.
If another tag with the same name exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
style Style where to add the new tag.
tag_name Name for the new tag.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_append(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_style_tag_del()
EAPI Eina_Bool edje_edit_style_tag_del (Evas_Object * obj, const char * style, const char * tag)
Deletes the given tag.
Parameters
obj Object being edited.
style Style from where to remove the tag.
tag Tag to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_remove(), and EINA_TRUE.
edje_edit_externals_list_get()
EAPI Eina_List* edje_edit_externals_list_get (Evas_Object * obj)
Gets the list of all the externals requested in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being an entry in the block of automatically loaded external modules.
References eina_list_append(), and eina_stringshare_add().
edje_edit_external_add()
EAPI Eina_Bool edje_edit_external_add (Evas_Object * obj, const char * external)
Adds an external module to be requested on edje load.
Parameters
obj Object being edited.
external Name of the external module to add to the list of autoload.
Returns
EINA_TRUE on success (or it was already there), EINA_FALSE otherwise.
References EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_external_del()
EAPI Eina_Bool edje_edit_external_del (Evas_Object * obj, const char * external)
Deletes the given external from the list.
Parameters
obj Object being edited.
external Name of the external module to remove from the autoload list.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_select_mode_get()
EAPI Edje_Edit_Select_Mode edje_edit_part_select_mode_get (Evas_Object * obj, const char * part)
Gets the select mode for a textblock part.
Parameters
obj Object being edited.
part Name of the part.
Returns
One of possible enum Edje_Edit_Select_Mode.
Since
1.11
References EDJE_PART_TYPE_TEXTBLOCK, and EINA_FALSE.
edje_edit_part_select_mode_set()
EAPI Eina_Bool edje_edit_part_select_mode_set (Evas_Object * obj, const char * part, Edje_Edit_Select_Mode mode)
Sets the select mode for a textblock part.
Parameters
obj Object being edited.
part Name of the part.
mode One of possible enum Edje_Edit_Select_Mode: EDJE_EDIT_SELECT_MODE_DEFAULT, EDJE_EDIT_SELECT_MODE_EXPLICIT.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_entry_mode_get()
EAPI Edje_Edit_Entry_Mode edje_edit_part_entry_mode_get (Evas_Object * obj, const char * part)
Gets the edit mode for a textblock part.
Parameters
obj Object being edited.
part Name of the part.
Returns
One of possible enum Edje_Entry_Mode.
Since
1.11
References EDJE_PART_TYPE_TEXTBLOCK, and EINA_FALSE.
edje_edit_part_entry_mode_set()
EAPI Eina_Bool edje_edit_part_entry_mode_set (Evas_Object * obj, const char * part, Edje_Edit_Entry_Mode mode)
Sets the edit mode for a textblock part.
Parameters
obj Object being edited.
part Name of the part.
mode One of possible enum Edje_Entry_Mode: EDJE_EDIT_ENTRY_MODE_NONE, EDJE_EDIT_ENTRY_MODE_PLAIN, EDJE_EDIT_ENTRY_MODE_EDITABLE, EDJE_EDIT_ENTRY_MODE_PASSWORD.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_parts_list_get()
EAPI Eina_List* edje_edit_parts_list_get (Evas_Object * obj)
Gets the list of all the parts in the given edje object.
Parameters
obj Object being edited.
Returns
List of strings, each being the name for a part in the open group. The return value should be freed with edje_edit_string_list_free().
See also
edje_edit_string_list_free()
References eina_list_append(), and eina_stringshare_add().
edje_edit_part_add()
EAPI Eina_Bool edje_edit_part_add (Evas_Object * obj, const char * name, Edje_Part_Type type)
Creates a new part in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
type Type of the new part. See Edje Data Collection reference for more info on this.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_EXTERNAL, and EINA_FALSE.
edje_edit_part_external_add()
EAPI Eina_Bool edje_edit_part_external_add (Evas_Object * obj, const char * name, const char * source)
Creates a new part of type EXTERNAL in the given edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned. Note that this function also create a default description for the part.
Parameters
obj Object being edited.
name Name for the new part.
source The registered external type to use for this part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_EXTERNAL, and EINA_FALSE.
edje_edit_part_del()
EAPI Eina_Bool edje_edit_part_del (Evas_Object * obj, const char * part)
Deletes the given part from the edje.
All the reference to this part will be zeroed.
Parameters
obj Object being edited.
part Name of part to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, eina_hash_find(), eina_mempool_free(), EINA_TRUE, evas_object_clip_set(), and evas_object_hide().
edje_edit_part_copy()
EAPI Eina_Bool edje_edit_part_copy (Evas_Object * obj, const char * part, const char * new_copy)
Copies the given part in edje.
If another part with the same name just exists nothing is created and EINA_FALSE is returned.
Parameters
obj Object being edited.
part Name of the part.
new_copy Name of the new copied part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_part_exist()
EAPI Eina_Bool edje_edit_part_exist (Evas_Object * obj, const char * part)
Checks if a part with the given name exist in the edje object.
Parameters
obj Object being edited.
part Name of part to check for its existence.
Returns
EINA_TRUE if the part exists, EINA_FALSE if not.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_above_get()
EAPI const char* edje_edit_part_above_get (Evas_Object * obj, const char * part)
Gets the name of part stacked above the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one above.
Returns
Name of the part above. NULL if an error occurred or if part is the topmost part in the group.
References eina_stringshare_add().
edje_edit_part_below_get()
EAPI const char* edje_edit_part_below_get (Evas_Object * obj, const char * part)
Gets the name of part stacked below the one passed.
Parameters
obj Object being edited.
part Name of part of which to check the one below.
Returns
Name of the part below. NULL if an error occurred or if part is the bottommost part in the group.
References eina_stringshare_add().
edje_edit_part_restack_below()
EAPI Eina_Bool edje_edit_part_restack_below (Evas_Object * obj, const char * part)
Moves the given part below the previous one.
Parameters
obj Object being edited.
part Name of part to move one step below.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, evas_object_stack_above(), and evas_object_stack_below().
edje_edit_part_restack_part_below()
EAPI Eina_Bool edje_edit_part_restack_part_below (Evas_Object * obj, const char * part, const char * below)
Moves the given part below the part named below.
Parameters
obj Object being edited.
part Name of part which will be moved.
below Name of part for which will be moved 'part'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, evas_object_stack_above(), and evas_object_stack_below().
edje_edit_part_restack_above()
EAPI Eina_Bool edje_edit_part_restack_above (Evas_Object * obj, const char * part)
Moves the given part above the next one.
Parameters
obj Object being edited.
part Name of part to move one step above.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, and evas_object_stack_above().
edje_edit_part_restack_part_above()
EAPI Eina_Bool edje_edit_part_restack_part_above (Evas_Object * obj, const char * part, const char * above)
Moves the given part above the part named above.
Parameters
obj Object being edited.
part Name of part which will be moved.
above Name of part for which will be moved 'part'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, and evas_object_stack_above().
edje_edit_part_name_set()
EAPI Eina_Bool edje_edit_part_name_set (Evas_Object * obj, const char * part, const char * new_name)
Sets a new name for part.
Note that the relative getter function don't exist as it don't make sense ;)
Parameters
obj Object being edited.
part Name of part to rename.
new_name New name for the given part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_api_name_get()
EAPI const char* edje_edit_part_api_name_get (Evas_Object * obj, const char * part)
Gets api's name of a part.
Parameters
obj Object being edited.
part Name of the part.
Returns
Name of the API if successful, NULL otherwise.
edje_edit_part_api_description_get()
EAPI const char* edje_edit_part_api_description_get (Evas_Object * obj, const char * part)
Gets api's description of a part.
Parameters
obj Object being edited.
part Name of the part.
Returns
Description of the api if successful, NULL otherwise.
edje_edit_part_api_name_set()
EAPI Eina_Bool edje_edit_part_api_name_set (Evas_Object * obj, const char * part, const char * name)
Sets api's name of a part.
Parameters
obj Object being edited.
part Name of the part.
name New name for the api property.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_api_description_set()
EAPI Eina_Bool edje_edit_part_api_description_set (Evas_Object * obj, const char * part, const char * description)
Sets api's description of a part.
Parameters
obj Object being edited.
part Name of part.
description New description for the api property.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_type_get()
EAPI Edje_Part_Type edje_edit_part_type_get (Evas_Object * obj, const char * part)
Gets the type of a part.
Parameters
obj Object being edited.
part Name of part to get the type of.
Returns
Type of the part. See Edje Data Collection reference for details.
edje_edit_part_clip_to_get()
EAPI const char* edje_edit_part_clip_to_get (Evas_Object * obj, const char * part)
Gets the clip_to part.
Parameters
obj Object being edited.
part Name of the part whose clipper to get.
Returns
Name of the part part is clipped to. NULL is returned on errors and if the part don't have a clip.
edje_edit_part_clip_to_set()
EAPI Eina_Bool edje_edit_part_clip_to_set (Evas_Object * obj, const char * part, const char * clip_to)
Sets a part to clip part to.
Parameters
obj Object being edited.
part Part to set the clipper to.
clip_to Part to use as clipper, if NULL then the clipping value will be cancelled (unset clipping).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, EINA_TRUE, evas_object_clip_get(), and evas_object_clip_set().
edje_edit_part_source_get()
EAPI const char* edje_edit_part_source_get (Evas_Object * obj, const char * part)
Gets the source of part.
The meaning of this parameter varies depending on the type of the part. For GROUP parts, it's the name of another group in the Edje file which will be autoloaded and swallowed on this part. For TEXTBLOCK parts, it's the name of a group to be used for selection display under the text. For EXTERNAL parts, it's the name of the registered external widget to load and swallow on this part.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source parameter or NULL if nothing set or an error occurred.
References eina_stringshare_add().
edje_edit_part_source_set()
EAPI Eina_Bool edje_edit_part_source_set (Evas_Object * obj, const char * part, const char * source)
Sets the source of part.
If setting source of the part will lead to recursive reference (when A source to B, and B is going to be source to A because of this function), then it will return EINA_FALSE.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source_get()
Note
You can't change the source for EXTERNAL parts, it's akin to changing the type of the part.
NOTE: This is not applied now. You must reload the edje to see the change.
References edje_object_add(), edje_object_file_set(), EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_GROUP, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALLTHROUGH, EINA_FALSE, EINA_TRUE, and evas_object_del().
edje_edit_part_source2_get()
EAPI const char* edje_edit_part_source2_get (Evas_Object * obj, const char * part)
Gets the source2 of part.
Only available to TEXTBLOCK parts. It is used for the group to be loaded and used for selection display OVER the selected text. source is used for under of the selected text, if source is specified.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source2 parameter or NULL if nothing set or an error occurred.
Since
1.11
edje_edit_part_source2_set()
EAPI Eina_Bool edje_edit_part_source2_set (Evas_Object * obj, const char * part, const char * source)
Sets the source2 of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source2_get()
Since
1.11
edje_edit_part_source3_get()
EAPI const char* edje_edit_part_source3_get (Evas_Object * obj, const char * part)
Gets the source3 of part.
Only available to TEXTBLOCK parts. It is used for the group to be loaded and used for cursor display UNDER the cursor position. source4 is used for over the cursor text, if source4 is specified.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source3 parameter or NULL if nothing set or an error occurred.
Since
1.11
edje_edit_part_source3_set()
EAPI Eina_Bool edje_edit_part_source3_set (Evas_Object * obj, const char * part, const char * source)
Sets the source3 of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source3_get()
Since
1.11
NOTE: This is not applied now. You must reload the edje to see the change.
edje_edit_part_source4_get()
EAPI const char* edje_edit_part_source4_get (Evas_Object * obj, const char * part)
Gets the source4 of part.
Only available to TEXTBLOCK parts. It is used for the group to be loaded and used for cursor display OVER the cursor position. source3 is used for under the cursor text, if source4 is specified.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source4 parameter or NULL if nothing set or an error occurred.
Since
1.11
edje_edit_part_source4_set()
EAPI Eina_Bool edje_edit_part_source4_set (Evas_Object * obj, const char * part, const char * source)
Sets the source4 of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source4_get()
Since
1.11
NOTE: This is not applied now. You must reload the edje to see the change.
edje_edit_part_source5_get()
EAPI const char* edje_edit_part_source5_get (Evas_Object * obj, const char * part)
Gets the source5 of part.
Only available to TEXTBLOCK parts. It is used for the group to be loaded and used for anchors display UNDER the anchor position. source6 is used for over the anchors text, if source6 is specified.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source5 parameter or NULL if nothing set or an error occurred.
Since
1.11
edje_edit_part_source5_set()
EAPI Eina_Bool edje_edit_part_source5_set (Evas_Object * obj, const char * part, const char * source)
Sets the source5 of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source5_get()
Since
1.11
edje_edit_part_source6_get()
EAPI const char* edje_edit_part_source6_get (Evas_Object * obj, const char * part)
Gets the source6 of part.
Only available to TEXTBLOCK parts. It is used for the group to be loaded and used for anchor display OVER the anchor position. source5 is used for under the anchor text, if source6 is specified.
Parameters
obj Object being edited.
part Part to get the source from.
Returns
Content of the source6 parameter or NULL if nothing set or an error occurred.
Since
1.11
edje_edit_part_source6_set()
EAPI Eina_Bool edje_edit_part_source6_set (Evas_Object * obj, const char * part, const char * source)
Sets the source6 of part.
Parameters
obj Object being edited.
part Part to set the source of.
source Value for the source parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_part_source6_get()
Since
1.11
edje_edit_part_effect_get()
EAPI Edje_Text_Effect edje_edit_part_effect_get (Evas_Object * obj, const char * part)
Gets the effect for a given part.
Gets the effect used for parts of type TEXT. See Edje Data Collection reference for more details.
Parameters
obj Object being edited.
part Part to get the effect of.
Returns
The effect set for the part.
edje_edit_part_effect_set()
EAPI Eina_Bool edje_edit_part_effect_set (Evas_Object * obj, const char * part, Edje_Text_Effect effect)
Sets the effect for a given part.
Effects and shadow directions can be combined.
For effect and shadow direction list please look at Edje Part Text ref page.
Parameters
obj Object being edited.
part Part to set the effect to. Only makes sense on type TEXT.
effect Effect to set for the part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
Edje Text Part
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_part_selected_state_get()
EAPI const char* edje_edit_part_selected_state_get (Evas_Object * obj, const char * part, double * value)
Gets the current selected state in part.
Parameters
obj Object being edited.
part Part to get the selected state of.
value Pointer to a double where the value of the state will be stored.
Returns
The name of the currently selected state for the part.
References eina_stringshare_add().
Referenced by edje_edit_state_external_param_set().
edje_edit_part_selected_state_set()
EAPI Eina_Bool edje_edit_part_selected_state_set (Evas_Object * obj, const char * part, const char * state, double value)
Sets the current state in part.
Parameters
obj Object being edited.
part Part to set the state of.
state Name of the state to set.
value Value of the state.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_part_mouse_events_get()
EAPI Eina_Bool edje_edit_part_mouse_events_get (Evas_Object * obj, const char * part)
Gets mouse_events for part.
Parameters
obj Object being edited.
part Part to get if the mouse events is accepted.
Returns
EINA_TRUE if part will accept mouse events, EINA_FALSE otherwise.
References EINA_FALSE.
edje_edit_part_mouse_events_set()
EAPI Eina_Bool edje_edit_part_mouse_events_set (Evas_Object * obj, const char * part, Eina_Bool mouse_events)
Sets mouse_events for part.
Parameters
obj Object being edited.
part The part to set if the mouse events is accepted.
mouse_events EINA_TRUE if part will accept mouse events, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, and evas_object_pass_events_set().
edje_edit_part_required_get()
EAPI Eina_Bool edje_edit_part_required_get (Evas_Object * obj, const char * part)
Gets required value for part.
Parameters
obj Object being edited.
part Part to get if the part is required by API.
Returns
EINA_TRUE if part is required by the object's implementation, EINA_FALSE otherwise.
Since
1.23
References EINA_FALSE.
edje_edit_part_anti_alias_get()
EAPI Eina_Bool edje_edit_part_anti_alias_get (Evas_Object * obj, const char * part)
Gets anti-aliasing for part.
Parameters
obj Object being edited.
part Part to get if the anti-aliasing is accepted.
Returns
EINA_TRUE if part will draw anti-aliased, EINA_FALSE otherwise.
References EINA_FALSE.
edje_edit_part_anti_alias_set()
EAPI Eina_Bool edje_edit_part_anti_alias_set (Evas_Object * obj, const char * part, Eina_Bool anti_alias)
Sets anti-aliasing for part.
Parameters
obj Object being edited.
part The part to set if the anti-aliasing is accepted.
anti_alias EINA_TRUE if part should be drawn anti-aliased, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, and evas_object_anti_alias_set().
edje_edit_part_repeat_events_get()
EAPI Eina_Bool edje_edit_part_repeat_events_get (Evas_Object * obj, const char * part)
Gets repeat_events for part.
Parameters
obj Object being edited.
part Part to get if it will pass all events to the other parts.
Returns
EINA_TRUE if the events received will propagate to other parts, EINA_FALSE otherwise
References EINA_FALSE.
edje_edit_part_repeat_events_set()
EAPI Eina_Bool edje_edit_part_repeat_events_set (Evas_Object * obj, const char * part, Eina_Bool repeat_events)
Sets repeat_events for part.
Parameters
obj Object being edited.
part Part to set if will repeat all the received mouse events to other parts.
repeat_events EINA_TRUE if the events received will propagate to other parts, EINA_FALSE otherwise
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_TRUE, and evas_object_repeat_events_set().
edje_edit_part_use_alternate_font_metrics_get()
EAPI Eina_Bool edje_edit_part_use_alternate_font_metrics_get (Evas_Object * obj, const char * part)
Gets use_alternate_font_metrics variable for part.
Parameters
obj Object being edited.
part Part to get use_alternate_font_metrics for text or textblock part is enabled.
Returns
EINA_TRUE if use_alternate_font_metrics, EINA_FALSE otherwise
Since
1.18
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and EINA_FALSE.
edje_edit_part_use_alternate_font_metrics_set()
EAPI Eina_Bool edje_edit_part_use_alternate_font_metrics_set (Evas_Object * obj, const char * part, Eina_Bool use)
Sets use_alternate_font_metrics variable for part.
Parameters
obj Object being edited.
part Part to set use_alternate_font_metrics for text or textblock part is enabled.
use EINA_TRUE if use_alternate_font_metrics, EINA_FALSE otherwise
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_part_multiline_get()
EAPI Eina_Bool edje_edit_part_multiline_get (Evas_Object * obj, const char * part)
Gets multiline for part.
Parameters
obj Object being edited.
part Part to get if editing multiple lines for text or textblock part is enabled.
Returns
EINA_TRUE if multiple lines for editing is enabled, EINA_FALSE otherwise
Since
1.11
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and EINA_FALSE.
edje_edit_part_multiline_set()
EAPI Eina_Bool edje_edit_part_multiline_set (Evas_Object * obj, const char * part, Eina_Bool multiline)
Sets multiline for part.
Parameters
obj Object being edited.
part Part to set if editing multiple lines for text or textblock part is enabled.
multiline EINA_TRUE if multiple lines for editing is enabled, EINA_FALSE otherwise
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_part_precise_is_inside_get()
EAPI Eina_Bool edje_edit_part_precise_is_inside_get (Evas_Object * obj, const char * part)
Gets precise_is_inside for part.
Parameters
obj Object being edited.
part Part to get if it will enable point collision detection for the part.
Returns
EINA_TRUE if point collision detection for the part is enabled, EINA_FALSE otherwise
Since
1.11
edje_edit_part_precise_is_inside_set()
EAPI Eina_Bool edje_edit_part_precise_is_inside_set (Evas_Object * obj, const char * part, Eina_Bool precise_is_inside)
Sets precise_is_inside for part.
Parameters
obj Object being edited.
part Part to set if it will enable point collision detection for the part.
precise_is_inside EINA_TRUE if point collision detection for the part is enabled, EINA_FALSE otherwise
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_access_get()
EAPI Eina_Bool edje_edit_part_access_get (Evas_Object * obj, const char * part)
Gets accessibility for part.
Parameters
obj Object being edited.
part Part to get if it uses accessibility feature.
Returns
EINA_TRUE if part uses accessibility feature, EINA_FALSE otherwise
Since
1.11
edje_edit_part_access_set()
EAPI Eina_Bool edje_edit_part_access_set (Evas_Object * obj, const char * part, Eina_Bool access)
Sets accessibility for part.
Parameters
obj Object being edited.
part Part to set if it uses accessibility feature.
access EINA_TRUE if part uses accessibility feature, EINA_FALSE otherwise
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_ignore_flags_get()
EAPI Evas_Event_Flags edje_edit_part_ignore_flags_get (Evas_Object * obj, const char * part)
Gets ignore_flags for part.
Parameters
obj Object being edited.
part Part to get which event_flags are being ignored.
Returns
The Event flags set to the part.
edje_edit_part_ignore_flags_set()
EAPI Eina_Bool edje_edit_part_ignore_flags_set (Evas_Object * obj, const char * part, Evas_Event_Flags ignore_flags)
Sets ignore_flags for part.
Parameters
obj Object being edited.
part Part to set which event flags will be ignored.
ignore_flags The Event flags to be ignored by the part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_mask_flags_get()
EAPI Evas_Event_Flags edje_edit_part_mask_flags_get (Evas_Object * obj, const char * part)
Gets mask_flags for part.
Parameters
obj Object being edited.
part Part to get which event_flags are being masked.
Returns
The Event flags set to the part.
edje_edit_part_mask_flags_set()
EAPI Eina_Bool edje_edit_part_mask_flags_set (Evas_Object * obj, const char * part, Evas_Event_Flags mask_flags)
Sets mask_flags for part.
Parameters
obj Object being edited.
part Part to set which event flags will be masked.
mask_flags The Event flags to be masked by the part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_pointer_mode_get()
EAPI Evas_Object_Pointer_Mode edje_edit_part_pointer_mode_get (Evas_Object * obj, const char * part)
Gets pointer_mode of a part.
Parameters
obj Object being edited.
part Part name to get it's pointer_mode.
Returns
Pointer Mode of the part.
Since
1.11
edje_edit_part_pointer_mode_set()
EAPI Eina_Bool edje_edit_part_pointer_mode_set (Evas_Object * obj, const char * part, Evas_Object_Pointer_Mode pointer_mode)
Gets pointer_mode of a part.
Note that Pointer Mode can be:
EVAS_OBJECT_POINTER_MODE_AUTOGRAB - default, X11-like
EVAS_OBJECT_POINTER_MODE_NOGRAB - pointer always bound to the object right below it
EVAS_OBJECT_POINTER_MODE_NOGRAB_NO_REPEAT_UPDOWN - useful on object with "repeat events" enabled,
Since
1.2
Parameters
obj Object being edited.
part Part name to get it's pointer_mode.
pointer_mode Pointer Mode.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_cursor_mode_get()
EAPI unsigned char edje_edit_part_cursor_mode_get (Evas_Object * obj, const char * part)
Gets cursor_mode of a part.
Note that Cursor Mode can be: 0 - UNDER cursor mode means the cursor will draw below the character pointed at. That's the default. 1 - BEFORE cursor mode means the cursor is drawn as a vertical line before the current character, just like many other GUI toolkits handle it.
Parameters
obj Object being edited.
part Part name to get it's cursor_mode.
Returns
Pointer Mode of the part.
Since
1.11
References EDJE_PART_TYPE_TEXT, and EDJE_PART_TYPE_TEXTBLOCK.
edje_edit_part_cursor_mode_set()
EAPI Eina_Bool edje_edit_part_cursor_mode_set (Evas_Object * obj, const char * part, unsigned char cursor_mode)
Gets pointer_mode of a part.
Note that Cursor Mode can be: 0 - UNDER cursor mode means the cursor will draw below the character pointed at. That's the default. 1 - BEFORE cursor mode means the cursor is drawn as a vertical line before the current character, just like many other GUI toolkits handle it.
Parameters
obj Object being edited.
part Part name to get it's pointer_mode.
cursor_mode Pointer Mode.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_part_scale_set()
EAPI Eina_Bool edje_edit_part_scale_set (Evas_Object * obj, const char * part, Eina_Bool scale)
Sets scale property for the part.
This property tells Edje that the given part should be scaled by the Edje scale factor.
Parameters
obj Object being edited.
part Part to set scale for.
scale Scale value to set.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_part_scale_get()
EAPI Eina_Bool edje_edit_part_scale_get (Evas_Object * obj, const char * part)
Gets scale for the part.
Parameters
obj Object being edited.
part Part to get the scale value of.
Returns
Whether scale is on (EINA_TRUE) or not.
References EINA_FALSE.
edje_edit_part_drag_x_get()
EAPI int edje_edit_part_drag_x_get (Evas_Object * obj, const char * part)
Gets horizontal draggable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged horizontally.
Returns
1 (or -1) if the part can be dragged horizontally, 0 otherwise.
edje_edit_part_drag_x_set()
EAPI Eina_Bool edje_edit_part_drag_x_set (Evas_Object * obj, const char * part, int drag)
Sets horizontal draggable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged horizontally.
drag 1 (or -1) if the part should be dragged horizontally, 0 otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_drag_y_get()
EAPI int edje_edit_part_drag_y_get (Evas_Object * obj, const char * part)
Gets vertical draggable state for part.
Parameters
obj Object being edited.
part Part to get if can be dragged vertically.
Returns
1 (or - 1) if the part can be dragged vertically, 0 otherwise.
edje_edit_part_drag_y_set()
EAPI Eina_Bool edje_edit_part_drag_y_set (Evas_Object * obj, const char * part, int drag)
Sets vertical draggable state for part.
Parameters
obj Object being edited.
part Part to set if should be dragged vertically.
drag 1 (or -1) of the part should be dragged vertically, 0 otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_drag_step_x_get()
EAPI int edje_edit_part_drag_step_x_get (Evas_Object * obj, const char * part)
Gets horizontal draggable step for part.
Parameters
obj Object being edited.
part Part to get the drag horizontal step value.
Returns
The step value.
edje_edit_part_drag_step_x_set()
EAPI Eina_Bool edje_edit_part_drag_step_x_set (Evas_Object * obj, const char * part, int step)
Sets horizontal draggable state for part.
Parameters
obj Object being edited.
part Part to set the drag horizontal step value.
step The step the will be dragged.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_step_y_get()
EAPI int edje_edit_part_drag_step_y_get (Evas_Object * obj, const char * part)
Gets vertical draggable step for part.
Parameters
obj Object being edited.
part Part to get the drag vertical step value.
Returns
The step value.
edje_edit_part_drag_step_y_set()
EAPI Eina_Bool edje_edit_part_drag_step_y_set (Evas_Object * obj, const char * part, int step)
Sets vertical draggable state for part.
Parameters
obj Object being edited.
part Part to set the drag vertical step value.
step The step the will be dragged.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_count_x_get()
EAPI int edje_edit_part_drag_count_x_get (Evas_Object * obj, const char * part)
Gets horizontal draggable count for part.
Parameters
obj Object being edited.
part Part to get the drag horizontal count value.
Returns
Horizontal draggable count value
edje_edit_part_drag_count_x_set()
EAPI Eina_Bool edje_edit_part_drag_count_x_set (Evas_Object * obj, const char * part, int count)
Sets horizontal draggable count for part.
Parameters
obj Object being edited.
part Part to set the drag horizontal count value.
count The count value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_count_y_get()
EAPI int edje_edit_part_drag_count_y_get (Evas_Object * obj, const char * part)
Gets vertical draggable count for part.
Parameters
obj Object being edited.
part Part to get the drag vertical count value.
Returns
Vertical draggable count value
edje_edit_part_drag_count_y_set()
EAPI Eina_Bool edje_edit_part_drag_count_y_set (Evas_Object * obj, const char * part, int count)
Sets vertical draggable count for part.
Parameters
obj Object being edited.
part Part to set the drag vertical count value.
count The count value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_confine_get()
EAPI const char* edje_edit_part_drag_confine_get (Evas_Object * obj, const char * part)
Gets the name of the part that is used as 'confine' for the given draggies.
Parameters
obj Object being edited.
part Part to get the name that is used as 'confine' for the given draggies.
Returns
The name of the confine part, or NULL (if unset).
edje_edit_part_drag_confine_set()
EAPI Eina_Bool edje_edit_part_drag_confine_set (Evas_Object * obj, const char * part, const char * confine)
Sets the name of the part that is used as 'confine' for the given draggies.
Parameters
obj Object being edited.
part Part to set the name that is used as 'confine' for the given draggies.
confine The name of the confine part, or NULL to unset confine.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_event_get()
EAPI const char* edje_edit_part_drag_event_get (Evas_Object * obj, const char * part)
Gets the name of the part that is used as the receiver of the drag event.
Parameters
obj Object being edited.
part Part to get the name that is used as the receiver of the drag event.
Returns
The name of the part that will receive events, or NULL (if unset).
edje_edit_part_drag_event_set()
EAPI Eina_Bool edje_edit_part_drag_event_set (Evas_Object * obj, const char * part, const char * event)
Sets the name of the part that will receive events from the given draggies.
Parameters
obj Object being edited.
part Part to set the name that will receive events from the given draggies.
event The name of the part that will receive events, or NULL to unset.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_part_drag_threshold_get()
EAPI const char* edje_edit_part_drag_threshold_get (Evas_Object * obj, const char * part)
Gets the name of the part that is used as 'threshold' for the given draggies.
Parameters
obj Object being edited.
part Part to get the name that is used as 'threshold' for the given draggies.
Returns
The name of the threshold part, or NULL (if unset).
edje_edit_part_drag_threshold_set()
EAPI Eina_Bool edje_edit_part_drag_threshold_set (Evas_Object * obj, const char * part, const char * threshold)
Sets the name of the part that is used as 'threshold' for the given draggies.
Parameters
obj Object being edited.
part Part to set the name that is used as 'threshold' for the given draggies.
threshold The name of the threshold part, or NULL to unset confine.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_box_layout_get()
EAPI Eina_Stringshare* edje_edit_state_box_layout_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets primary layout of the box.
Note
The returned string should be freed with eina_stringshare_del().
Parameters
obj Object being edited.
part Part that have BOX type.
state Name of the state.
value Value of the state.
Returns
Primary layout of a BOX part in given state.
Since
1.14
edje_edit_state_box_layout_set()
EAPI Eina_Bool edje_edit_state_box_layout_set (Evas_Object * obj, const char * part, const char * state, double value, char * layout)
Sets primary layout of the box.
When trying to set primary layout to NULL, function will use alternative layout instead.
Parameters
obj Object being edited.
part Part that have BOX type.
state Name of the state.
value Value of the state.
layout New primary layout to set name.
Possible layouts:
horizontal (default)
vertical
horizontal_homogeneous
vertical_homogeneous
horizontal_max (homogeneous to the max sized child)
vertical_max
horizontal_flow
vertical_flow
stack
some_other_custom_layout_set_by_the_application
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
edje_edit_state_box_alt_layout_get()
EAPI Eina_Stringshare* edje_edit_state_box_alt_layout_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets fallback layout of the box.
Note
The returned string should be freed with eina_stringshare_del().
Parameters
obj Object being edited.
part Part that have BOX type.
state Name of the state.
value Value of the state.
Returns
Fallback layout of a BOX part in given state.
Since
1.14
edje_edit_state_box_alt_layout_set()
EAPI Eina_Bool edje_edit_state_box_alt_layout_set (Evas_Object * obj, const char * part, const char * state, double value, char * layout)
Sets fallback layout of the box.
When trying to set fallback layout to NULL, function will use default layout ("horizontal") instead.
Parameters
obj Object being edited.
part Part that have BOX type.
state Name of the state.
value Value of the state.
layout New fallback layout to set name.
Possible layouts:
horizontal (default)
vertical
horizontal_homogeneous
vertical_homogeneous
horizontal_max (homogeneous to the max sized child)
vertical_max
horizontal_flow
vertical_flow
stack
some_other_custom_layout_set_by_the_application
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
edje_edit_state_table_homogeneous_set()
EAPI Eina_Bool edje_edit_state_table_homogeneous_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char homogeneous)
Sets homogeneous mode for TABLE part.
Parameters
obj Object being edited.
part Part that have TABLE type.
state Name of the state.
value Value of the state.
homogeneous Homogeneous mode for table.
Possible modes:
EDJE_OBJECT_TABLE_HOMOGENEOUS_NONE,
EDJE_OBJECT_TABLE_HOMOGENEOUS_TABLE,
EDJE_OBJECT_TABLE_HOMOGENEOUS_ITEM
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_table_homogeneous_get()
EAPI unsigned char edje_edit_state_table_homogeneous_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets homogeneous mode for TABLE part.
Parameters
obj Object being edited.
part Part that have TABLE type.
state Name of the state.
value Value of the state.
Possible modes:
EDJE_OBJECT_TABLE_HOMOGENEOUS_NONE,
EDJE_OBJECT_TABLE_HOMOGENEOUS_TABLE,
EDJE_OBJECT_TABLE_HOMOGENEOUS_ITEM
Returns
Table homogeneous mode on success, or 0 on any error.
Since
1.14
References EDJE_PART_TYPE_TABLE.
edje_edit_state_container_min_get()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_min_get (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool * h, Eina_Bool * v)
Gets whether vertical or horizontal minimum size's of the box are equal to the minimum vertical or horizontal size of items (function for BOX or TABLE part. If EINA_TRUE - is equal, if EINA_FALSE - is not)
Deprecated:
Use edje_edit_state_container_min_h_get() and edje_edit_state_container_min_v_get() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
h Variable to store horizontal min value.
v Variable to store vertical min value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_min_h_get()
EAPI Eina_Bool edje_edit_state_container_min_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets whether horizontal min size of the container is equal to the min horizontal size of items (BOX and TABLE part functions).
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
EINA_TRUE If the part forces container's minimal horizontal size, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_min_v_get()
EAPI Eina_Bool edje_edit_state_container_min_v_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets whether vertical min size of the container is equal to the min vertical size of items (BOX and TABLE part functions).
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
EINA_TRUE If the part forces container's minimal horizontal size, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_min_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_min_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool h, Eina_Bool v)
Sets whether vertical or horizontal minimum size's of the box are equal to the minimum vertical or horizontal size of items (function for BOX or TABLE part. If EINA_TRUE - is equal, if EINA_FALSE - is not)
Deprecated:
Use edje_edit_state_container_min_h_set() and edje_edit_state_container_min_v_set() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
h horizontal min value.
v vertical min value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_min_h_set()
EAPI Eina_Bool edje_edit_state_container_min_h_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool h)
Sets whether horizontal min size of the container should be equal to the min horizontal size of items (BOX and TABLE part functions).
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
h New horizontal min value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_min_v_set()
EAPI Eina_Bool edje_edit_state_container_min_v_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool v)
Sets whether vertical min size of the container should be equal to the min vertical size of items (BOX and TABLE part functions).
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
v New vertical min value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_padding_get()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_padding_get (Evas_Object * obj, const char * part, const char * state, double value, int * x, int * y)
Gets x and y paddings for BOX or TABLE part.
Deprecated:
Use edje_edit_state_container_padding_x_get() and edje_edit_state_container_padding_y_get() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
x Variable to store x padding.
y Variable to store y padding.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_padding_x_get()
EAPI int edje_edit_state_container_padding_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets x padding for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
The padding by x axis.
Since
1.16
edje_edit_state_container_padding_y_get()
EAPI int edje_edit_state_container_padding_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets y padding for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
The padding by y axis.
Since
1.16
edje_edit_state_container_padding_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_padding_set (Evas_Object * obj, const char * part, const char * state, double value, int x, int y)
Sets x and y paddings for BOX or TABLE part.
Deprecated:
Use edje_edit_state_container_padding_x_set() and edje_edit_state_container_padding_y_set() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
x Value for setting x padding.
y Value for setting y padding.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_padding_x_set()
EAPI Eina_Bool edje_edit_state_container_padding_x_set (Evas_Object * obj, const char * part, const char * state, double value, int x)
Sets x padding for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
x New x padding value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_padding_y_set()
EAPI Eina_Bool edje_edit_state_container_padding_y_set (Evas_Object * obj, const char * part, const char * state, double value, int y)
Sets y padding for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
y New y padding value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_align_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_align_set (Evas_Object * obj, const char * part, const char * state, double value, double x, double y)
Sets x and y align for BOX or TABLE part.
Deprecated:
Use edje_edit_state_container_align_x_set() and edje_edit_state_container_align_y_set() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
x Variable to store x value.
y Variable to store y value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_align_x_set()
EAPI Eina_Bool edje_edit_state_container_align_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets x align for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
x New x align value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_align_y_set()
EAPI Eina_Bool edje_edit_state_container_align_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets y align for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
y New y align value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.16
edje_edit_state_container_align_get()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_state_container_align_get (Evas_Object * obj, const char * part, const char * state, double value, double * x, double * y)
Gets x and y align for BOX or TABLE part.
Deprecated:
Use edje_edit_state_container_align_x_set() and edje_edit_state_container_align_y_set() instead.
Parameters
obj Object being edited.
part Part that have BOX/TABLE type.
state Name of the state.
value Value of the state.
x Value for setting x align.
y Value for setting y align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.14
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_container_align_x_get()
EAPI double edje_edit_state_container_align_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets x align for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
The align by x axis.
Since
1.16
edje_edit_state_container_align_y_get()
EAPI double edje_edit_state_container_align_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets y align for BOX or TABLE part.
Parameters
obj Object being edited.
part Part that has BOX/TABLE type.
state Name of the state.
value Value of the state.
Returns
The align by y axis.
Since
1.16
edje_edit_part_item_append()
EAPI Eina_Bool edje_edit_part_item_append (Evas_Object * obj, const char * part, const char * item_name, const char * source_group)
Appends new item to box or table part.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
source_group Source (means group name) of the new item
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_insert_before()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_insert_before (Evas_Object * obj, const char * part, const char * item_name, const char * item_before, const char * source_group)
Inserts new item to box or table part before specified existing item.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
item_before Name of repeated item that is exist in BOX or TABLE.
source_group Source (means group name) of the new item.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_insert_before_index()
EAPI Eina_Bool edje_edit_part_item_insert_before_index (Evas_Object * obj, const char * part, const char * item_name, unsigned int index, const char * source_group)
Inserts new item to box or table part before specified existing item.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
index Index of repeated item that is exist in BOX or TABLE.
source_group Source (means group name) of the new item.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_insert_after()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_insert_after (Evas_Object * obj, const char * part, const char * item_name, const char * item_after, const char * source_group)
Inserts new item to box or table part after specified existing item.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
item_after Name of repeated item that is exist in BOX or TABLE.
source_group Source (means group name) of the new item.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_insert_after_index()
EAPI Eina_Bool edje_edit_part_item_insert_after_index (Evas_Object * obj, const char * part, const char * item_name, unsigned int index, const char * source_group)
Inserts new item to box or table part after specified existing item.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
index Index of repeated item that is exist in BOX or TABLE.
source_group Source (means group name) of the new item.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_insert_at()
EAPI Eina_Bool edje_edit_part_item_insert_at (Evas_Object * obj, const char * part, const char * item_name, const char * source_group, unsigned int place)
Inserts new item to box or table part directly into specified position.
Parameters
obj Object being edited.
part Part to add a new item. This part should have BOX or TABLE type.
item_name Name of new item that is not exist in BOX or TABLE yet.
source_group Source (means group name) of the new item.
place Specified place to insert item into. Place cannot be less than 0 or greater than current number of items in BOX or TABLE.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_part_item_move_above()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_move_above (Evas_Object * obj, const char * part, const char * item_name)
Restacks existing item above.
Parameters
obj Object being edited.
part Part which contain items. This part should have BOX or TABLE type.
item_name Name of item that will be moved above.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_move_above_index()
EAPI Eina_Bool edje_edit_part_item_move_above_index (Evas_Object * obj, const char * part, unsigned int index)
Restacks existing item above.
Parameters
obj Object being edited.
part Part which contain items. This part should have BOX or TABLE type.
index Index of item that will be moved above.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_move_below()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_move_below (Evas_Object * obj, const char * part, const char * item_name)
Restacks existing item below.
Parameters
obj Object being edited.
part Part which contain items. This part should have BOX or TABLE type.
item_name Name of item that will be moved below.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_move_below_index()
EAPI Eina_Bool edje_edit_part_item_move_below_index (Evas_Object * obj, const char * part, unsigned int index)
Restacks existing item below.
Parameters
obj Object being edited.
part Part which contain items. This part should have BOX or TABLE type.
index Index of item that will be moved below.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_items_list_get()
EINA_DEPRECATED EAPI Eina_List* edje_edit_part_items_list_get (Evas_Object * obj, const char * part)
Gets the list of all part items in the given edje.
Parameters
obj Object being edited.
part Name of part which is TABLE or BOX part and contain items.
Returns
A List containing all part items names found in the edje file.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, eina_list_append(), and eina_stringshare_add().
edje_edit_part_items_count_get()
EAPI int edje_edit_part_items_count_get (Evas_Object * obj, const char * part)
Gets the count of part items in the given edje.
Parameters
obj Object being edited.
part Name of part which is TABLE or BOX part and contain items.
Returns
A count part items in case of success, and -1 otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, and EDJE_PART_TYPE_TABLE.
edje_edit_part_item_del()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_del (Evas_Object * obj, const char * part, const char * name)
Deletes item from box or table part.
Parameters
obj Object being edited.
part Part to delete exist item. This part should have BOX or TABLE type.
name Name of exist item to delete it from BOX or TABLE.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, EINA_TRUE, and WRN.
edje_edit_part_item_index_del()
EAPI Eina_Bool edje_edit_part_item_index_del (Evas_Object * obj, const char * part, unsigned int index)
Deletes item from box or table part by index.
Parameters
obj Object being edited.
part Part to delete exist item. This part should have BOX or TABLE type.
index Index of exist item to delete it from BOX or TABLE.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_index_name_set()
EAPI Eina_Bool edje_edit_part_item_index_name_set (Evas_Object * obj, const char * part, unsigned int index, const char * name)
Sets name for item from table or box items.
Parameters
obj Object being edited.
part Part to change item's source. This part should have BOX or TABLE type.
index Index of item
name New item name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_stringshare_add(), eina_stringshare_del(), and EINA_TRUE.
edje_edit_part_item_index_name_get()
EAPI const char* edje_edit_part_item_index_name_get (Evas_Object * obj, const char * part, unsigned int index)
Gets name for item from table or box items.
Parameters
obj Object being edited.
part Part to return item's source. This part should have BOX or TABLE type.
index Index of item.
Returns
name of the given item.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, and eina_stringshare_add().
edje_edit_part_item_source_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_source_set (Evas_Object * obj, const char * part, const char * item_name, const char * source_group)
Sets source for item from table or box items.
Parameters
obj Object being edited.
part Part to change item's source. This part should have BOX or TABLE type.
item_name Name of item.
source_group New group name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_part_item_index_source_set()
EAPI Eina_Bool edje_edit_part_item_index_source_set (Evas_Object * obj, const char * part, unsigned int index, const char * source_group)
Sets source for item from table or box items.
Parameters
obj Object being edited.
part Part to change item's source. This part should have BOX or TABLE type.
index Index of item
source_group New group name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, eina_hash_find(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_part_item_source_get()
EINA_DEPRECATED EAPI const char* edje_edit_part_item_source_get (Evas_Object * obj, const char * part, const char * item_name)
Gets source for item from table or box items.
Parameters
obj Object being edited.
part Part to return item's source. This part should have BOX or TABLE type.
item_name Name of item.
Returns
source of the given item.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, and eina_stringshare_add().
edje_edit_part_item_index_source_get()
EAPI const char* edje_edit_part_item_index_source_get (Evas_Object * obj, const char * part, unsigned int index)
Gets source for item from table or box items.
Parameters
obj Object being edited.
part Part to return item's source. This part should have BOX or TABLE type.
index Index of item.
Returns
source of the given item.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, and eina_stringshare_add().
edje_edit_part_item_min_w_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_min_w_get (Evas_Object * obj, const char * part, const char * item)
Gets the minimum width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get minimum width.
Returns
The minimum width value.
Since
1.11
edje_edit_part_item_min_w_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_min_w_set (Evas_Object * obj, const char * part, const char * item, int min_w)
Sets the minimum width value of a part's item.
The minimum width should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set minimum width.
min_w Minimum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_min_h_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_min_h_get (Evas_Object * obj, const char * part, const char * item)
Gets the minimum height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get minimum height.
Returns
The minimum height value.
Since
1.11
edje_edit_part_item_min_h_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_min_h_set (Evas_Object * obj, const char * part, const char * item, int min_h)
Sets the minimum height value of a part's item.
The minimum height should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set minimum height.
min_h Minimum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_max_w_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_max_w_get (Evas_Object * obj, const char * part, const char * item)
Gets the maximum width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get maximum width.
Returns
The maximum width value.
Since
1.11
edje_edit_part_item_max_w_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_max_w_set (Evas_Object * obj, const char * part, const char * item, int max_w)
Sets the maximum width value of a part's item.
The maximum width should be greater than -1. The value -1 means that state doesn't have any boundaries on width direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set maximum width.
max_w Maximum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_max_h_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_max_h_get (Evas_Object * obj, const char * part, const char * item)
Gets the maximum height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get maximum height.
Returns
The maximum height value.
Since
1.11
edje_edit_part_item_max_h_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_max_h_set (Evas_Object * obj, const char * part, const char * item, int max_h)
Sets the maximum height value of a part's item.
The maximum height should be greater than -1. The value -1 means that state doesn't have any boundaries on height direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set maximum height.
max_h Maximum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_aspect_w_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_aspect_w_get (Evas_Object * obj, const char * part, const char * item)
Gets the aspect width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get aspect width.
Returns
The aspect width value.
Since
1.11
edje_edit_part_item_aspect_w_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_w_set (Evas_Object * obj, const char * part, const char * item, int aspect_w)
Sets the aspect width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set aspect width.
aspect_w Aspect width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_aspect_h_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_aspect_h_get (Evas_Object * obj, const char * part, const char * item)
Gets the aspect height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get aspect height.
Returns
The maximum height value.
Since
1.11
edje_edit_part_item_aspect_h_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_h_set (Evas_Object * obj, const char * part, const char * item, int aspect_h)
Sets the aspect height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set aspect height.
aspect_h Aspect height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_prefer_w_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_prefer_w_get (Evas_Object * obj, const char * part, const char * item)
Gets the prefer width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get prefer width.
Returns
The prefer width value.
Since
1.11
edje_edit_part_item_aspect_mode_get()
EINA_DEPRECATED EAPI Edje_Aspect_Control edje_edit_part_item_aspect_mode_get (Evas_Object * obj, const char * part, const char * item)
Gets aspect mode for an item of TABLE or BOX.
This may return next values:
EDJE_ASPECT_CONTROL_NONE
EDJE_ASPECT_CONTROL_NEITHER
EDJE_ASPECT_CONTROL_HORIZONTAL
EDJE_ASPECT_CONTROL_VERTICAL
EDJE_ASPECT_CONTROL_BOTH
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to set aspect mode.
Returns
One of possible enum Edje_Aspect_Control.
Since
1.11
edje_edit_part_item_aspect_mode_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_aspect_mode_set (Evas_Object * obj, const char * part, const char * item, Edje_Aspect_Control mode)
Sets aspect mode for an item of TABLE or BOX.
Mode may be next:
EDJE_ASPECT_CONTROL_NONE
EDJE_ASPECT_CONTROL_NEITHER
EDJE_ASPECT_CONTROL_HORIZONTAL
EDJE_ASPECT_CONTROL_VERTICAL
EDJE_ASPECT_CONTROL_BOTH
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to set aspect mode.
mode One of possible enum from Edje_Aspect_Control:
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_prefer_w_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_prefer_w_set (Evas_Object * obj, const char * part, const char * item, int prefer_w)
Sets the prefer width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set prefer width.
prefer_w Prefer width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_prefer_h_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_prefer_h_get (Evas_Object * obj, const char * part, const char * item)
Gets the prefer height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get prefer height.
Returns
The maximum height value.
Since
1.11
edje_edit_part_item_prefer_h_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_prefer_h_set (Evas_Object * obj, const char * part, const char * item, int prefer_h)
Sets the prefer height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set prefer height.
prefer_h Prefer height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_spread_w_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_spread_w_get (Evas_Object * obj, const char * part, const char * item)
Gets the spread width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get spread width.
Returns
The spread width value.
Since
1.11
edje_edit_part_item_spread_w_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_spread_w_set (Evas_Object * obj, const char * part, const char * item, int spread_w)
Sets the spread width value of a part's item.
Attention
be careful, if you set up huge number (like 10 or 100) width and height of spread is being multiplied and you will get huge number of objects that may "eat" all of your processor performance at once... Or if you want, you may get some coffee and wait until it will recalculate all of those objects :)
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set spread width.
spread_w Maximum width value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_spread_h_get()
EINA_DEPRECATED EAPI int edje_edit_part_item_spread_h_get (Evas_Object * obj, const char * part, const char * item)
Gets the spread height value of a part's item.
Attention
be careful, if you set up huge number (like 10 or 100) width and height of spread is being multiplied and you will get huge number of objects that may "eat" all of your processor performance at once... Or if you want, you may get some coffee and wait until it will recalculate all of those objects :)
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to get spread height.
Returns
The spread height value.
Since
1.11
edje_edit_part_item_spread_h_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_spread_h_set (Evas_Object * obj, const char * part, const char * item, int spread_h)
Sets the spread height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
item The name of the item to set spread height.
spread_h spread height value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_index_min_w_get()
EAPI int edje_edit_part_item_index_min_w_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the minimum width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get minimum width.
Returns
The minimum width value.
Since
1.18
edje_edit_part_item_index_min_w_set()
EAPI Eina_Bool edje_edit_part_item_index_min_w_set (Evas_Object * obj, const char * part, unsigned int index, int min_w)
Sets the minimum width value of a part's item.
The minimum width should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set minimum width.
min_w Minimum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_min_h_get()
EAPI int edje_edit_part_item_index_min_h_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the minimum height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get minimum height.
Returns
The minimum height value.
Since
1.18
edje_edit_part_item_index_min_h_set()
EAPI Eina_Bool edje_edit_part_item_index_min_h_set (Evas_Object * obj, const char * part, unsigned int index, int min_h)
Sets the minimum height value of a part's item.
The minimum height should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set minimum height.
min_h Minimum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_max_w_get()
EAPI int edje_edit_part_item_index_max_w_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the maximum width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get maximum width.
Returns
The maximum width value.
Since
1.18
edje_edit_part_item_index_max_w_set()
EAPI Eina_Bool edje_edit_part_item_index_max_w_set (Evas_Object * obj, const char * part, unsigned int index, int max_w)
Sets the maximum width value of a part's item.
The maximum width should be greater than -1. The value -1 means that state doesn't have any boundaries on width direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set maximum width.
max_w Maximum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_max_h_get()
EAPI int edje_edit_part_item_index_max_h_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the maximum height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get maximum height.
Returns
The maximum height value.
Since
1.18
edje_edit_part_item_index_max_h_set()
EAPI Eina_Bool edje_edit_part_item_index_max_h_set (Evas_Object * obj, const char * part, unsigned int index, int max_h)
Sets the maximum height value of a part's item.
The maximum height should be greater than -1. The value -1 means that state doesn't have any boundaries on height direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set maximum height.
max_h Maximum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_aspect_w_get()
EAPI int edje_edit_part_item_index_aspect_w_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the aspect width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get aspect width.
Returns
The aspect width value.
Since
1.18
edje_edit_part_item_index_aspect_w_set()
EAPI Eina_Bool edje_edit_part_item_index_aspect_w_set (Evas_Object * obj, const char * part, unsigned int index, int aspect_w)
Sets the aspect width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set aspect width.
aspect_w Aspect width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_aspect_h_get()
EAPI int edje_edit_part_item_index_aspect_h_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the aspect height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get aspect height.
Returns
The maximum height value.
Since
1.18
edje_edit_part_item_index_aspect_h_set()
EAPI Eina_Bool edje_edit_part_item_index_aspect_h_set (Evas_Object * obj, const char * part, unsigned int index, int aspect_h)
Sets the aspect height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set aspect height.
aspect_h Aspect height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_prefer_w_get()
EAPI int edje_edit_part_item_index_prefer_w_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the prefer width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get prefer width.
Returns
The prefer width value.
Since
1.18
edje_edit_part_item_index_aspect_mode_get()
EAPI Edje_Aspect_Control edje_edit_part_item_index_aspect_mode_get (Evas_Object * obj, const char * part, unsigned int index)
Gets aspect mode for an item of TABLE or BOX.
This may return next values:
EDJE_ASPECT_CONTROL_NONE
EDJE_ASPECT_CONTROL_NEITHER
EDJE_ASPECT_CONTROL_HORIZONTAL
EDJE_ASPECT_CONTROL_VERTICAL
EDJE_ASPECT_CONTROL_BOTH
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set aspect mode.
Returns
One of possible enum Edje_Aspect_Control.
Since
1.18
edje_edit_part_item_index_aspect_mode_set()
EAPI Eina_Bool edje_edit_part_item_index_aspect_mode_set (Evas_Object * obj, const char * part, unsigned int index, Edje_Aspect_Control mode)
Sets aspect mode for an item of TABLE or BOX.
Mode may be next:
EDJE_ASPECT_CONTROL_NONE
EDJE_ASPECT_CONTROL_NEITHER
EDJE_ASPECT_CONTROL_HORIZONTAL
EDJE_ASPECT_CONTROL_VERTICAL
EDJE_ASPECT_CONTROL_BOTH
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set aspect mode.
mode One of possible enum from Edje_Aspect_Control:
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_index_prefer_w_set()
EAPI Eina_Bool edje_edit_part_item_index_prefer_w_set (Evas_Object * obj, const char * part, unsigned int index, int prefer_w)
Sets the prefer width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set prefer width.
prefer_w Prefer width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_prefer_h_get()
EAPI int edje_edit_part_item_index_prefer_h_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the prefer height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get prefer height.
Returns
The maximum height value.
Since
1.18
edje_edit_part_item_index_prefer_h_set()
EAPI Eina_Bool edje_edit_part_item_index_prefer_h_set (Evas_Object * obj, const char * part, unsigned int index, int prefer_h)
Sets the prefer height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set prefer height.
prefer_h Prefer height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_spread_w_get()
EAPI int edje_edit_part_item_index_spread_w_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the spread width value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get spread width.
Returns
The spread width value.
Since
1.18
edje_edit_part_item_index_spread_w_set()
EAPI Eina_Bool edje_edit_part_item_index_spread_w_set (Evas_Object * obj, const char * part, unsigned int index, int spread_w)
Sets the spread width value of a part's item.
Attention
be careful, if you set up huge number (like 10 or 100) width and height of spread is being multiplied and you will get huge number of objects that may "eat" all of your processor performance at once... Or if you want, you may get some coffee and wait until it will recalculate all of those objects :)
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set spread width.
spread_w Maximum width value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_spread_h_get()
EAPI int edje_edit_part_item_index_spread_h_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the spread height value of a part's item.
Attention
be careful, if you set up huge number (like 10 or 100) width and height of spread is being multiplied and you will get huge number of objects that may "eat" all of your processor performance at once... Or if you want, you may get some coffee and wait until it will recalculate all of those objects :)
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to get spread height.
Returns
The spread height value.
Since
1.18
edje_edit_part_item_index_spread_h_set()
EAPI Eina_Bool edje_edit_part_item_index_spread_h_set (Evas_Object * obj, const char * part, unsigned int index, int spread_h)
Sets the spread height value of a part's item.
Parameters
obj Object being edited.
part Part that contain state.
index Index of the item to set spread height.
spread_h spread height value.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_padding_get()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_padding_get (Evas_Object * obj, const char * part, const char * item_name, int * l, int * r, int * t, int * b)
Gets paddings of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
l A pointer to store the left padding value.
r A pointer to store the right padding value.
t A pointer to store the top padding value.
b A pointer to store the bottom padding value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_padding_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_padding_set (Evas_Object * obj, const char * part, const char * item_name, int l, int r, int t, int b)
Sets paddings of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
l Value of the left padding.
r Value of the right padding.
t Value of the top padding.
b Value of the bottom padding.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_index_padding_get()
EAPI Eina_Bool edje_edit_part_item_index_padding_get (Evas_Object * obj, const char * part, unsigned int index, int * l, int * r, int * t, int * b)
Gets paddings of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
l A pointer to store the left padding value.
r A pointer to store the right padding value.
t A pointer to store the top padding value.
b A pointer to store the bottom padding value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_index_padding_set()
EAPI Eina_Bool edje_edit_part_item_index_padding_set (Evas_Object * obj, const char * part, unsigned int index, int l, int r, int t, int b)
Sets paddings of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
l Value of the left padding.
r Value of the right padding.
t Value of the top padding.
b Value of the bottom padding.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_align_x_get()
EINA_DEPRECATED EAPI double edje_edit_part_item_align_x_get (Evas_Object * obj, const char * part, const char * item)
Gets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to get horizontal align value.
Returns
The horizontal align value for the given align (value is between -1.0 and 1.0)
Since
1.11
edje_edit_part_item_index_align_x_get()
EAPI double edje_edit_part_item_index_align_x_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get horizontal align value.
Returns
The horizontal align value for the given align (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_align_x_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_align_x_set (Evas_Object * obj, const char * part, const char * item, double align_x)
Sets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contains item
item The name of the item to set horizontal align value.
align_x New value of the horizontal align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_index_align_x_set()
EAPI Eina_Bool edje_edit_part_item_index_align_x_set (Evas_Object * obj, const char * part, unsigned int index, double align_x)
Sets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contains item
index Index of the item to set horizontal align value.
align_x New value of the horizontal align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_align_y_get()
EINA_DEPRECATED EAPI double edje_edit_part_item_align_y_get (Evas_Object * obj, const char * part, const char * item)
Gets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to get vertical align value.
Returns
The vertical align value for the given align (value is between -1.0 and 1.0)
Since
1.11
edje_edit_part_item_index_align_y_get()
EAPI double edje_edit_part_item_index_align_y_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get vertical align value.
Returns
The vertical align value for the given align (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_align_y_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_align_y_set (Evas_Object * obj, const char * part, const char * item, double align_y)
Sets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to set vertical align value.
align_y New value of the vertical align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_index_align_y_set()
EAPI Eina_Bool edje_edit_part_item_index_align_y_set (Evas_Object * obj, const char * part, unsigned int index, double align_y)
Sets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set vertical align value.
align_y New value of the vertical align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_weight_x_get()
EINA_DEPRECATED EAPI double edje_edit_part_item_weight_x_get (Evas_Object * obj, const char * part, const char * item)
Gets the horizontal weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to get horizontal weight value.
Returns
The horizontal weight value for the given item (value is between -1.0 and 1.0)
Since
1.11
edje_edit_part_item_index_weight_x_get()
EAPI double edje_edit_part_item_index_weight_x_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the horizontal weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get horizontal weight value.
Returns
The horizontal weight value for the given item (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_weight_x_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_weight_x_set (Evas_Object * obj, const char * part, const char * item, double weight_x)
Sets the horizontal we value of a part item.
Parameters
obj Object being edited.
part Part that contains item
item The name of the item to set horizontal weight value.
weight_x New value of the horizontal weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_index_weight_x_set()
EAPI Eina_Bool edje_edit_part_item_index_weight_x_set (Evas_Object * obj, const char * part, unsigned int index, double weight_x)
Sets the horizontal we value of a part item.
Parameters
obj Object being edited.
part Part that contains item
index Index of the item to set horizontal weight value.
weight_x New value of the horizontal weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_weight_y_get()
EINA_DEPRECATED EAPI double edje_edit_part_item_weight_y_get (Evas_Object * obj, const char * part, const char * item)
Gets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to get vertical weight value.
Returns
The vertical weight value for the given item (value is between -1.0 and 1.0)
Since
1.11
edje_edit_part_item_index_weight_y_get()
EAPI double edje_edit_part_item_index_weight_y_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get vertical weight value.
Returns
The vertical weight value for the given item (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_weight_y_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_weight_y_set (Evas_Object * obj, const char * part, const char * item, double weight_y)
Sets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item to set vertical weight value.
weight_y New value of the vertical weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.11
edje_edit_part_item_index_weight_y_set()
EAPI Eina_Bool edje_edit_part_item_index_weight_y_set (Evas_Object * obj, const char * part, unsigned int index, double weight_y)
Sets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set vertical weight value.
weight_y New value of the vertical weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_position_get()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_get (Evas_Object * obj, const char * part, const char * item_name, unsigned short * col, unsigned short * row)
Gets column/row position of the part's item.
Deprecated:
Use edje_edit_part_item_position_col_get() and edje_edit_part_item_position_row_get() instead.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
col Column item position.
row Row item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_item_align_x_get()
EAPI double edje_edit_part_item_item_align_x_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get horizontal align value.
Returns
The horizontal align value for the given align (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_item_align_x_set()
EAPI Eina_Bool edje_edit_part_item_item_align_x_set (Evas_Object * obj, const char * part, unsigned int index, double align_x)
Sets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain item
index Index of the item to set horizontal align value.
align_x New value of the horizontal align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_item_align_y_get()
EAPI double edje_edit_part_item_item_align_y_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get vertical align value.
Returns
The vertical align value for the given align (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_item_align_y_set()
EAPI Eina_Bool edje_edit_part_item_item_align_y_set (Evas_Object * obj, const char * part, unsigned int index, double align_y)
Sets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set vertical align value.
align_y New value of the vertical align.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_item_weight_x_get()
EAPI double edje_edit_part_item_item_weight_x_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the horizontal weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get horizontal weight value.
Returns
The horizontal weight value for the given item (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_item_weight_x_set()
EAPI Eina_Bool edje_edit_part_item_item_weight_x_set (Evas_Object * obj, const char * part, unsigned int index, double weight_x)
Sets the horizontal we value of a part item.
Parameters
obj Object being edited.
part Part that contains item
index Index of the item to set horizontal weight value.
weight_x New value of the horizontal weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_item_weight_y_get()
EAPI double edje_edit_part_item_item_weight_y_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to get vertical weight value.
Returns
The vertical weight value for the given item (value is between -1.0 and 1.0)
Since
1.18
edje_edit_part_item_item_weight_y_set()
EAPI Eina_Bool edje_edit_part_item_item_weight_y_set (Evas_Object * obj, const char * part, unsigned int index, double weight_y)
Sets the vertical weight value of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item to set vertical weight value.
weight_y New value of the vertical weight.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_position_col_get()
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_position_col_get (Evas_Object * obj, const char * part, const char * item_name)
Gets column position of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
Returns
The item column value.
Since
1.16
edje_edit_part_item_position_row_get()
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_position_row_get (Evas_Object * obj, const char * part, const char * item_name)
Gets row position of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
Returns
The item row value.
Since
1.16
edje_edit_part_item_index_position_col_get()
EAPI unsigned short edje_edit_part_item_index_position_col_get (Evas_Object * obj, const char * part, unsigned int index)
Gets column position of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
Returns
The item column value.
Since
1.18
edje_edit_part_item_index_position_row_get()
EAPI unsigned short edje_edit_part_item_index_position_row_get (Evas_Object * obj, const char * part, unsigned int index)
Gets row position of the part's item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
Returns
The item row value.
Since
1.18
edje_edit_part_item_position_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_set (Evas_Object * obj, const char * part, const char * item_name, unsigned short col, unsigned short row)
Sets column/row position of a new part's item.
Deprecated:
Use edje_edit_part_item_position_col_set() and edje_edit_part_item_position_row_set() instead.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
col Column item position.
row Row item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_position_col_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_col_set (Evas_Object * obj, const char * part, const char * item_name, unsigned short col)
Sets column position of a part item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
col Column item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.16
edje_edit_part_item_position_row_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_position_row_set (Evas_Object * obj, const char * part, const char * item_name, unsigned short row)
Sets row position of a part item.
Parameters
obj Object being edited.
part Part that contain item.
item_name The name of the item.
row Row item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.16
edje_edit_part_item_index_position_col_set()
EAPI Eina_Bool edje_edit_part_item_index_position_col_set (Evas_Object * obj, const char * part, unsigned int index, unsigned short col)
Sets column position of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
col Column item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_position_row_set()
EAPI Eina_Bool edje_edit_part_item_index_position_row_set (Evas_Object * obj, const char * part, unsigned int index, unsigned short row)
Sets row position of a part item.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
row Row item position.
Returns
EINA_TRUE If successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_span_get()
EINA_DEPRECATED EAPI void edje_edit_part_item_span_get (Evas_Object * obj, const char * part, const char * item, unsigned char * col, unsigned char * row)
Retrieves the how many columns and rows will span for use by item.
Parameters
obj object being edited.
part part that contain item.
item the name of the item of part.
col Pointer to an unsigned char in which to store the columns count.
row Pointer to an unsigned char in which to store the rows count.
Deprecated:
Use edje_edit_part_item_span_row_get() and edje_edit_part_item_span_col_get() instead.
Since
1.11
edje_edit_part_item_span_col_get()
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_span_col_get (Evas_Object * obj, const char * part, const char * item)
Gets the number of span columns.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item of part.
Returns
The count of span columns.
Since
1.16
edje_edit_part_item_span_row_get()
EINA_DEPRECATED EAPI unsigned short edje_edit_part_item_span_row_get (Evas_Object * obj, const char * part, const char * item)
Gets the number of span rows.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item of part.
Returns
The count of span rows.
Since
1.16
edje_edit_part_item_span_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_set (Evas_Object * obj, const char * part, const char * item, unsigned char col, unsigned char row)
Sets the count of columns and rows, which this item will spans for use.
Parameters
obj object being edited.
part part that contain item.
item the name of the item to set new count of columns spans.
col new count of the columns spans.
row new count of the rows spans.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.11
References EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_TABLE, EINA_FALSE, and EINA_TRUE.
edje_edit_part_item_span_col_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_col_set (Evas_Object * obj, const char * part, const char * item, unsigned short col)
Sets the count of columns which this item will spans for use.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item.
col new count of the columns spans.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.16
edje_edit_part_item_span_row_set()
EINA_DEPRECATED EAPI Eina_Bool edje_edit_part_item_span_row_set (Evas_Object * obj, const char * part, const char * item, unsigned short row)
Sets the count of rows which this item will spans for use.
Parameters
obj Object being edited.
part Part that contain item.
item The name of the item.
row new count of the rows spans.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.16
edje_edit_part_item_index_span_col_set()
EAPI Eina_Bool edje_edit_part_item_index_span_col_set (Evas_Object * obj, const char * part, unsigned int index, unsigned short col)
Sets the count of columns which this item will spans for use.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
col new count of the columns spans.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_span_row_set()
EAPI Eina_Bool edje_edit_part_item_index_span_row_set (Evas_Object * obj, const char * part, unsigned int index, unsigned short row)
Sets the count of rows which this item will spans for use.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item.
row new count of the rows spans.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
Since
1.18
edje_edit_part_item_index_span_col_get()
EAPI unsigned short edje_edit_part_item_index_span_col_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the number of span columns.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item of part.
Returns
The count of span columns.
Since
1.18
edje_edit_part_item_index_span_row_get()
EAPI unsigned short edje_edit_part_item_index_span_row_get (Evas_Object * obj, const char * part, unsigned int index)
Gets the number of span rows.
Parameters
obj Object being edited.
part Part that contain item.
index Index of the item of part.
Returns
The count of span rows.
Since
1.18
edje_edit_part_states_list_get()
EAPI Eina_List* edje_edit_part_states_list_get (Evas_Object * obj, const char * part)
Gets the list of all the states in the given part.
Parameters
obj Object being edited.
part Part to get the states names list.
Returns
An Eina_List* of string (char *)containing all the states names found in part, including the float value (ex: "default 0.00").
Use edje_edit_string_list_free() when you don't need it anymore.
edje_edit_state_name_set()
EAPI Eina_Bool edje_edit_state_name_set (Evas_Object * obj, const char * part, const char * state, double value, const char * new_name, double new_value)
Sets a new name for the given state in the given part.
Parameters
obj Object being edited.
part Part that contain state.
state Name of the state to rename.
value Value of the state to rename.
new_name The new name for the state.
new_value The new value for the state.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_count(), eina_list_data_get(), and EINA_TRUE.
edje_edit_state_add()
EAPI Eina_Bool edje_edit_state_add (Evas_Object * obj, const char * part, const char * name, double value)
Creates a new state to the give part.
Parameters
obj Object being edited.
part Part to set the name of the new state.
name Name for the new state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References _Edje_External_Param_Info::c, _Edje_External_Param_Info::d, edje_edit_state_exist(), EDJE_EXTERNAL_DOUBLE_UNSET, EDJE_EXTERNAL_INT_UNSET, edje_external_param_info_get(), EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_BOX, EDJE_PART_TYPE_EXTERNAL, EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_PROXY, EDJE_PART_TYPE_TABLE, EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, eina_list_append(), eina_stringshare_add(), EINA_TRUE, ERR, _Edje_External_Param_Info::i, _Edje_External_Param_Info::name, _Edje_External_Param_Info::s, and _Edje_External_Param_Info::type.
edje_edit_state_del()
EAPI Eina_Bool edje_edit_state_del (Evas_Object * obj, const char * part, const char * state, double value)
Deletes the given part state from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The current name of the state (not including the state value).
value The state value.
Returns
EINA_TRUE if successfully, EINA_FALSE otherwise.
References edje_edit_state_exist(), EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_state_exist()
EAPI Eina_Bool edje_edit_state_exist (Evas_Object * obj, const char * part, const char * state, double value)
Checks if a part state with the given name exist.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to check (not including the state value).
value The state value.
Returns
EINA_TRUE if the part state exist, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
Referenced by edje_edit_state_add(), and edje_edit_state_del().
edje_edit_state_copy()
EAPI Eina_Bool edje_edit_state_copy (Evas_Object * obj, const char * part, const char * from, double val_from, const char * to, double val_to)
Copies the state from into to.
If to doesn't exist it will be created.
Parameters
obj Object being edited.
part Part that contain state.
from State to copy from (not including state value).
val_from The value of the state to copy from.
to State to copy into (not including state value).
val_to The value of the state to copy into.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_relative_x_get()
EAPI double edje_edit_state_rel1_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel1 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 relative X' (not including the state value).
value The state value.
Returns
The 'rel1 relative X' value of the part state.
edje_edit_state_rel1_relative_y_get()
EAPI double edje_edit_state_rel1_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel1 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 relative Y' (not including the state value).
value The state value.
Returns
The 'rel1 relative Y' value of the part state.
edje_edit_state_rel2_relative_x_get()
EAPI double edje_edit_state_rel2_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel2 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 relative X' (not including the state value).
value The state value.
Returns
The 'rel2 relative X' value of the part state.
edje_edit_state_rel2_relative_y_get()
EAPI double edje_edit_state_rel2_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel2 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 relative Y' (not including the state value).
value The state value.
Returns
The 'rel2 relative Y' value of the part state.
edje_edit_state_rel1_relative_x_set()
EAPI Eina_Bool edje_edit_state_rel1_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the 'rel1 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 relative X' (not including the state value).
value The state value.
x The new 'rel1 relative X' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_relative_y_set()
EAPI Eina_Bool edje_edit_state_rel1_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets the 'rel1 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 relative Y' (not including the state value).
value The state value.
y The new 'rel1 relative Y' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_relative_x_set()
EAPI Eina_Bool edje_edit_state_rel2_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the 'rel2 relative X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 relative X' (not including the state value).
value The state value.
x The new 'rel2 relative X' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_relative_y_set()
EAPI Eina_Bool edje_edit_state_rel2_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets the 'rel2 relative Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 relative Y' (not including the state value).
value The state value.
y The new 'rel2 relative Y' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_offset_x_get()
EAPI int edje_edit_state_rel1_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel1 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 offset X' (not including the state value).
value The state value.
Returns
The 'rel1 offset X' value of the part state.
edje_edit_state_rel1_offset_y_get()
EAPI int edje_edit_state_rel1_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel1 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel1 offset Y' (not including the state value).
value The state value.
Returns
The 'rel1 offset Y' value of the part state.
edje_edit_state_rel2_offset_x_get()
EAPI int edje_edit_state_rel2_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel2 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 offset X' (not including the state value).
value The state value.
Returns
The 'rel2 offset X' value of the part state.
edje_edit_state_rel2_offset_y_get()
EAPI int edje_edit_state_rel2_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the 'rel2 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get 'rel2 offset Y' (not including the state value).
value The state value.
Returns
The 'rel2 offset Y' value of the part state.
edje_edit_state_rel1_offset_x_set()
EAPI Eina_Bool edje_edit_state_rel1_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, int x)
Sets the 'rel1 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 offset X' (not including the state value).
value The state value.
x The new 'rel1 offset X' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_offset_y_set()
EAPI Eina_Bool edje_edit_state_rel1_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, int y)
Sets the 'rel1 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel1 offset Y' (not including the state value).
value The state value.
y The new 'rel1 offset Y' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_offset_x_set()
EAPI Eina_Bool edje_edit_state_rel2_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, int x)
Sets the 'rel2 offset X' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 offset X' (not including the state value).
value The state value.
x The new 'rel2 offset X' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_offset_y_set()
EAPI Eina_Bool edje_edit_state_rel2_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, int y)
Sets the 'rel2 offset Y' value of state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set 'rel2 offset Y' (not including the state value).
value The state value.
y The new 'rel2 offset Y' value to set'.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_to_x_get()
EAPI const char* edje_edit_state_rel1_to_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part name rel1x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel1x is relative to (not including the state value).
value The state value.
Returns
The part name rel1x is relative to, or NULL if the part is relative to the whole interface.
edje_edit_state_rel1_to_y_get()
EAPI const char* edje_edit_state_rel1_to_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part name rel1y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel1y is relative to (not including the state value).
value The state value.
Returns
The part name rel1y is relative to, or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_to_x_get()
EAPI const char* edje_edit_state_rel2_to_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part name rel2x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel2x is relative to (not including the state value).
value The state value.
Returns
The part name rel2x is relative to, or NULL if the part is relative to the whole interface.
edje_edit_state_rel2_to_y_get()
EAPI const char* edje_edit_state_rel2_to_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part name rel2y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The state that contain which the part name rel2y is relative to (not including the state value).
value The state value.
Returns
The part name rel2y is relative to, or NULL if the part is relative to the whole interface.
edje_edit_state_rel1_to_x_set()
EAPI Eina_Bool edje_edit_state_rel1_to_x_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Sets the part rel1x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel1x is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel1_to_y_set()
EAPI Eina_Bool edje_edit_state_rel1_to_y_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Sets the part rel1y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel1y is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_to_x_set()
EAPI Eina_Bool edje_edit_state_rel2_to_x_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Sets the part rel2x is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel2x is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_rel2_to_y_set()
EAPI Eina_Bool edje_edit_state_rel2_to_y_set (Evas_Object * obj, const char * part, const char * state, double value, const char * rel_to)
Sets the part rel2y is relative to.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set rel2y is relative to (not including the state value).
value The state value.
rel_to The name of the part that is used as container/parent (NULL make the part relative to the whole interface).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_color_get()
EAPI void edje_edit_state_color_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Gets the color of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
edje_edit_state_color2_get()
EAPI void edje_edit_state_color2_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Gets the color2 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
edje_edit_state_color3_get()
EAPI void edje_edit_state_color3_get (Evas_Object * obj, const char * part, const char * state, double value, int * r, int * g, int * b, int * a)
Gets the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color (not including the state value).
value The state value.
r A pointer to store the red value.
g A pointer to store the green value.
b A pointer to store the blue value.
a A pointer to store the alpha value.
References EDJE_PART_TYPE_TEXT, and EDJE_PART_TYPE_TEXTBLOCK.
edje_edit_state_color_set()
EAPI Eina_Bool edje_edit_state_color_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Sets the color of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_color2_set()
EAPI Eina_Bool edje_edit_state_color2_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Sets the color2 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_color3_set()
EAPI Eina_Bool edje_edit_state_color3_set (Evas_Object * obj, const char * part, const char * state, double value, int r, int g, int b, int a)
Sets the color3 of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color (not including the state value).
value The state value.
r The red value of the color.
g The green value of the color.
b The blue value of the color.
a The alpha value of the color.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_align_x_get()
EAPI double edje_edit_state_align_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
Returns
The horizontal align value for the given state
edje_edit_state_align_y_get()
EAPI double edje_edit_state_align_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
Returns
The vertical align value for the given state
edje_edit_state_align_x_set()
EAPI Eina_Bool edje_edit_state_align_x_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Sets the horizontal align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get horizontal align (not including the state value).
value The state value.
align The new vertical align value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_align_y_set()
EAPI Eina_Bool edje_edit_state_align_y_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Sets the vertical align value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get vertical align (not including the state value).
value The state value.
align The new vertical align value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_min_w_get()
EAPI int edje_edit_state_min_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the minimum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum width (not including the state value).
value The state value.
Returns
The minimum width value.
edje_edit_state_min_w_set()
EAPI Eina_Bool edje_edit_state_min_w_set (Evas_Object * obj, const char * part, const char * state, double value, int min_w)
Sets the minimum width value of a part state.
The minimum width should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum width (not including the state value).
value The state value.
min_w Minimum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_min_h_get()
EAPI int edje_edit_state_min_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the minimum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum height (not including the state value).
value The state value.
Returns
The minimum height value.
edje_edit_state_min_h_set()
EAPI Eina_Bool edje_edit_state_min_h_set (Evas_Object * obj, const char * part, const char * state, double value, int min_h)
Sets the minimum height value of a part state.
The minimum height should be greater than 0.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum height (not including the state value).
value The state value.
min_h Minimum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_max_w_get()
EAPI int edje_edit_state_max_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the maximum width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum width (not including the state value).
value The state value.
Returns
The maximum width value.
edje_edit_state_max_w_set()
EAPI Eina_Bool edje_edit_state_max_w_set (Evas_Object * obj, const char * part, const char * state, double value, int max_w)
Sets the maximum width value of a part state.
The maximum width should be greater than -1. The value -1 means that state doesn't have any boundaries on width direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum width (not including the state value).
value The state value.
max_w Maximum width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_max_h_get()
EAPI int edje_edit_state_max_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the maximum height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum height (not including the state value).
value The state value.
Returns
The maximum height value.
edje_edit_state_max_h_set()
EAPI Eina_Bool edje_edit_state_max_h_set (Evas_Object * obj, const char * part, const char * state, double value, int max_h)
Sets the maximum height value of a part state.
The maximum height should be greater than -1. The value -1 means that state doesn't have any boundaries on height direction. (it can be any size that is bigger than it's min)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum height (not including the state value).
value The state value.
max_h Maximum height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_minmul_w_get()
EAPI double edje_edit_state_minmul_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the multiplier (minmul) width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get multiplier width (not including the state value).
value The state value.
Returns
The maximum width value.
Since
1.11
edje_edit_state_minmul_w_set()
EAPI Eina_Bool edje_edit_state_minmul_w_set (Evas_Object * obj, const char * part, const char * state, double value, double minmul_w)
Sets the multiplier (minmul) width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set multiplier width (not including the state value).
value The state value.
minmul_w Multiplier width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_minmul_h_get()
EAPI double edje_edit_state_minmul_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the multiplier (minmul) height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get multiplier height (not including the state value).
value The state value.
Returns
The maximum height value.
Since
1.11
edje_edit_state_minmul_h_set()
EAPI Eina_Bool edje_edit_state_minmul_h_set (Evas_Object * obj, const char * part, const char * state, double value, double minmul_h)
Sets the multiplier (minmul) height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set multiplier height (not including the state value).
value The state value.
minmul_h Multiplier height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_fixed_w_get()
EAPI Eina_Bool edje_edit_state_fixed_w_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fixed width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fixed width value (not including the state value).
value The state value.
Returns
The fixed width value.
edje_edit_state_fixed_w_set()
EAPI Eina_Bool edje_edit_state_fixed_w_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fixed)
Sets the fixed width value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fixed width value (not including the state value).
value The state value.
fixed Fixed width value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_fixed_h_get()
EAPI Eina_Bool edje_edit_state_fixed_h_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fixed height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fixed height value (not including the state value).
value The state value.
Returns
The fixed height value.
edje_edit_state_fixed_h_set()
EAPI Eina_Bool edje_edit_state_fixed_h_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fixed)
Sets the fixed height value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum height (not including the state value).
value The state value.
fixed Fixed height value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_aspect_min_get()
EAPI double edje_edit_state_aspect_min_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the minimum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get minimum aspect (not including the state value).
value The state value.
Returns
The minimum aspect
edje_edit_state_aspect_max_get()
EAPI double edje_edit_state_aspect_max_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the maximum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get maximum aspect (not including the state value).
value The state value.
Returns
The maximum aspect
edje_edit_state_aspect_min_set()
EAPI Eina_Bool edje_edit_state_aspect_min_set (Evas_Object * obj, const char * part, const char * state, double value, double aspect)
Sets the minimum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set minimum aspect (not including the state value).
value The state value.
aspect Minimum aspect value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_aspect_max_set()
EAPI Eina_Bool edje_edit_state_aspect_max_set (Evas_Object * obj, const char * part, const char * state, double value, double aspect)
Sets the maximum aspect value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set maximum aspect (not including the state value).
value The state value.
aspect Maximum aspect value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_aspect_pref_get()
EAPI unsigned char edje_edit_state_aspect_pref_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the aspect preference of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get aspect preference (not including the state value).
value The state value.
Returns
The aspect preference (0 = None, 1 = Vertical, 2 = Horizontal, 3 = Both)
edje_edit_state_aspect_pref_set()
EAPI Eina_Bool edje_edit_state_aspect_pref_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char pref)
Sets the aspect preference of a part state.
The available values of aspect preference are:
0 - None
1 - Vertical
2 - Horizontal
3 - Both
4 - Source
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set aspect preference (not including the state value).
value The state value.
pref The aspect preference to be set
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_fill_smooth_get()
EAPI Eina_Bool edje_edit_state_fill_smooth_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the smooth property for given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the fill horizontal origin relative to area (not including the state value).
value The state value.
Returns
The smooth value.
References EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_PROXY, and EINA_FALSE.
edje_edit_state_fill_smooth_set()
EAPI Eina_Bool edje_edit_state_fill_smooth_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool smooth)
Sets the smooth property for given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal origin relative to area (not including the state value).
value The state value.
smooth The smooth value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_PROXY, EINA_FALSE, and EINA_TRUE.
edje_edit_state_fill_type_get()
EAPI unsigned char edje_edit_state_fill_type_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill type property for given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
Returns
The value that represents fill type: 0 for SCALE or 1 for TILE. In case of error (for example, if part type does not match) returns 2.
See also
edje_edit_state_fill_type_set()
Since
1.11
References EDJE_PART_TYPE_IMAGE, and EDJE_PART_TYPE_PROXY.
edje_edit_state_fill_type_set()
EAPI Eina_Bool edje_edit_state_fill_type_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char fill_type)
Sets the fill type property for given part state.
Sets the image fill type. The available types are:
SCALE
image will be scaled accordingly to the 'relative' and 'offset' params values from 'origin' and 'size' blocks.
TILE
image will be tiled accordingly to the 'relative' and 'offset' params values from 'origin' and 'size' blocks.
Important: the part parameter 'min' must be set, it's size of tiled image. If parameter 'max' is set tiled area will be resized accordingly to the 'max' values of part. The default value of fill type is SCALE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
fill_type The value that represents fill type: 0 for SCALE or 1 for TILE.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_state_fill_type_get()
Since
1.11
References EDJE_PART_TYPE_IMAGE, EDJE_PART_TYPE_PROXY, EINA_FALSE, and EINA_TRUE.
edje_edit_state_fill_origin_relative_x_get()
EAPI double edje_edit_state_fill_origin_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the fill horizontal origin relative to area (not including the state value).
value The state value.
Returns
The fill horizontal origin relative to area.
edje_edit_state_fill_origin_relative_y_get()
EAPI double edje_edit_state_fill_origin_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill vertical origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical origin relative to area (not including the state value).
value The state value.
Returns
The fill vertical origin relative to area.
edje_edit_state_fill_origin_offset_x_get()
EAPI int edje_edit_state_fill_origin_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill horizontal origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal origin offset relative to area (not including the state value).
value The state value.
Returns
The fill horizontal origin offset relative to area.
edje_edit_state_fill_origin_offset_y_get()
EAPI int edje_edit_state_fill_origin_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill vertical origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical origin offset relative to area (not including the state value).
value The state value.
Returns
The fill vertical origin offset value.
edje_edit_state_fill_origin_relative_x_set()
EAPI Eina_Bool edje_edit_state_fill_origin_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal origin relative to area (not including the state value).
value The state value.
x The fill horizontal origin value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_origin_relative_y_set()
EAPI Eina_Bool edje_edit_state_fill_origin_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets the fill horizontal origin relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical origin relative to area (not including the state value).
value The state value.
y The fill vertical origin value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_origin_offset_x_set()
EAPI Eina_Bool edje_edit_state_fill_origin_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the fill horizontal origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal origin offset relative to area (not including the state value).
value The state value.
x The fill horizontal origin offset value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_origin_offset_y_set()
EAPI Eina_Bool edje_edit_state_fill_origin_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets the fill vertical origin offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical origin offset relative to area (not including the state value).
value The state value.
y The fill vertical origin offset value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_size_relative_x_get()
EAPI double edje_edit_state_fill_size_relative_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill horizontal size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal size relative to area (not including the state value).
value The state value.
Returns
The fill horizontal size relative to area.
edje_edit_state_fill_size_relative_y_get()
EAPI double edje_edit_state_fill_size_relative_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill vertical size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical size relative to area (not including the state value).
value The state value.
Returns
The fill vertical size relative to area.
edje_edit_state_fill_size_offset_x_get()
EAPI int edje_edit_state_fill_size_offset_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill horizontal size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill horizontal size offset relative to area (not including the state value).
value The state value.
Returns
The fill horizontal size offset relative to area.
edje_edit_state_fill_size_offset_y_get()
EAPI int edje_edit_state_fill_size_offset_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the fill vertical size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get fill vertical size offset relative to area (not including the state value).
value The state value.
Returns
The fill vertical size offset relative to area.
edje_edit_state_fill_size_relative_x_set()
EAPI Eina_Bool edje_edit_state_fill_size_relative_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the fill horizontal size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size relative value (not including the state value).
value The state value.
x The horizontal size relative value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_size_relative_y_set()
EAPI Eina_Bool edje_edit_state_fill_size_relative_y_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the fill vertical size relative value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical size relative value (not including the state value).
value The state value.
x The vertical size relative value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_size_offset_x_set()
EAPI Eina_Bool edje_edit_state_fill_size_offset_x_set (Evas_Object * obj, const char * part, const char * state, double value, double x)
Sets the fill horizontal size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size offset relative value (not including the state value).
value The state value.
x The horizontal size offset value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_fill_size_offset_y_set()
EAPI Eina_Bool edje_edit_state_fill_size_offset_y_set (Evas_Object * obj, const char * part, const char * state, double value, double y)
Sets the fill vertical size offset value of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill vertical size offset relative value (not including the state value).
value The state value.
y The vertical size offset value.
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
edje_edit_state_visible_get()
EAPI Eina_Bool edje_edit_state_visible_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get visibility (not including the state value).
value The state value.
Returns
EINA_TRUE if the state is visible, EINA_FALSE otherwise.
References EINA_FALSE.
edje_edit_state_visible_set()
EAPI Eina_Bool edje_edit_state_visible_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool visible)
Sets the visibility of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set visibility (not including the state value).
value The state value.
visible To set state visible (EINA_TRUE if the state is visible, EINA_FALSE otherwise)
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_color_class_get()
EAPI const char* edje_edit_state_color_class_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the color class of the given part state.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get color class (not including the state value).
value The state value.
Returns
The current color class.
References eina_stringshare_add().
edje_edit_state_color_class_set()
EAPI Eina_Bool edje_edit_state_color_class_set (Evas_Object * obj, const char * part, const char * state, double value, const char * color_class)
Sets the color class of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set color class (not including the state value).
value The state value.
color_class The color class to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EINA_FALSE, EINA_LIST_FOREACH, eina_stringshare_add(), and EINA_TRUE.
edje_edit_state_external_params_list_get()
EAPI const Eina_List* edje_edit_state_external_params_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the list of parameters for an external part.
DO NOT FREE THE LIST!
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get list of Edje_External_Param (not including the state value).
value The state value.
Returns
The list of Edje_External_Param.
References EDJE_PART_TYPE_EXTERNAL.
edje_edit_state_external_param_get()
EAPI Eina_Bool edje_edit_state_external_param_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type * type, void ** val)
Gets the external parameter type and value.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the parameter to look for.
type The type of the parameter will be stored here.
val Pointer to value will be stored here - DO NOT FREE IT!
Returns
EINA_TRUE if the parameter was found, EINA_FALSE otherwise.
References EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, EINA_TRUE, and ERR.
edje_edit_state_external_param_int_get()
EAPI Eina_Bool edje_edit_state_external_param_int_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int * val)
Gets external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the parameter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_state_external_param_bool_get()
EAPI Eina_Bool edje_edit_state_external_param_bool_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool * val)
Gets external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the parameter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_state_external_param_double_get()
EAPI Eina_Bool edje_edit_state_external_param_double_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double * val)
Gets external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the parameter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_state_external_param_string_get()
EAPI Eina_Bool edje_edit_state_external_param_string_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Gets external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the parameter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_STRING, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_state_external_param_choice_get()
EAPI Eina_Bool edje_edit_state_external_param_choice_get (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char ** val)
Gets external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the parameter.
val The value of the parameter.
Returns
EINA_TRUE if successful. EINA_FALSE if not found or is of different type.
References EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_state_external_param_set()
EAPI Eina_Bool edje_edit_state_external_param_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Edje_External_Param_Type type, ...)
Sets the external parameter type and value, adding it if it didn't exist before.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter (not including the state value).
value The state value.
param The name of the parameter set.
type The type of the parameter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise. Arguments should have proper sized values matching their types:
EDJE_EXTERNAL_PARAM_TYPE_INT: int
EDJE_EXTERNAL_PARAM_TYPE_BOOL: int
EDJE_EXTERNAL_PARAM_TYPE_DOUBLE: double
EDJE_EXTERNAL_PARAM_TYPE_STRING: char*
EDJE_EXTERNAL_PARAM_TYPE_CHOICE: char*
Note
: The validation of the parameter will occur only if the part is in the same state as the one being modified.
References edje_edit_part_selected_state_get(), EDJE_EXTERNAL_PARAM_TYPE_BOOL, EDJE_EXTERNAL_PARAM_TYPE_CHOICE, EDJE_EXTERNAL_PARAM_TYPE_DOUBLE, EDJE_EXTERNAL_PARAM_TYPE_INT, EDJE_EXTERNAL_PARAM_TYPE_STRING, edje_object_part_external_param_set(), EDJE_PART_TYPE_EXTERNAL, EINA_FALSE, eina_list_append(), EINA_LIST_FOREACH, eina_stringshare_add(), eina_stringshare_del(), EINA_TRUE, and ERR.
Referenced by edje_edit_state_external_param_bool_set(), edje_edit_state_external_param_choice_set(), edje_edit_state_external_param_double_set(), edje_edit_state_external_param_int_set(), and edje_edit_state_external_param_string_set().
edje_edit_state_external_param_int_set()
EAPI Eina_Bool edje_edit_state_external_param_int_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, int val)
Sets external parameter of type INT.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type INT (not including the state value).
value The state value.
param The name of the parameter.
val Value will be stored here.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_INT.
edje_edit_state_external_param_bool_set()
EAPI Eina_Bool edje_edit_state_external_param_bool_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, Eina_Bool val)
Sets external parameter of type BOOL.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type BOOL (not including the state value).
value The state value.
param The name of the parameter.
val Value will be stored here.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_BOOL.
edje_edit_state_external_param_double_set()
EAPI Eina_Bool edje_edit_state_external_param_double_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, double val)
Sets external parameter of type DOUBLE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type DOUBLE (not including the state value).
value The state value.
param The name of the parameter.
val Value will be stored here.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_DOUBLE.
edje_edit_state_external_param_string_set()
EAPI Eina_Bool edje_edit_state_external_param_string_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Sets external parameter of type STRING.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type STRING (not including the state value).
value The state value.
param The name of the parameter.
val Value will be stored here.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_STRING.
edje_edit_state_external_param_choice_set()
EAPI Eina_Bool edje_edit_state_external_param_choice_set (Evas_Object * obj, const char * part, const char * state, double value, const char * param, const char * val)
Sets external parameter of type CHOICE.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get external parameter of type CHOICE (not including the state value).
value The state value.
param The name of the parameter.
val Value will be stored here.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_edit_state_external_param_set(), and EDJE_EXTERNAL_PARAM_TYPE_CHOICE.
edje_edit_state_step_set()
EAPI Eina_Bool edje_edit_state_step_set (Evas_Object * obj, const char * part, const char * state, double value, int step_x, int step_y)
Sets the states step parameter values.
Step parameter restricts resizing of each dimension to values divisible by its value. This causes the part to jump from value to value while resizing. The default value is "0 0" disabling stepping.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size relative value (not including the state value).
value The state value.
step_x The horizontal step value.
step_y The vertical step value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_state_step_get()
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_step_get()
EAPI Eina_Bool edje_edit_state_step_get (Evas_Object * obj, const char * part, const char * state, double value, int * step_x, int * step_y)
Gets the states step values.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set fill horizontal size relative value (not including the state value).
value The state value.
step_x The pointer to the variable where horizontal step value should be written.
step_y The pointer to the variable where vertical step value should be written.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_state_step_set()
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_limit_set()
EAPI Eina_Bool edje_edit_state_limit_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char limit)
Sets the states limit parameter value.
Set limit causes the emission of signals when the size of part changes from zero or to a zero size in corresponding to the limit value. For example, the signals emitted on width changing are 'limit,width,over' and 'limit,width,zero' The available values are:
NONE - 0 (the default value)
WIDTH - 1
HEIGHT - 2
BOTH - 3
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
limit The value that represents the states limit value in case of success.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_state_limit_get()
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_limit_get()
EAPI unsigned char edje_edit_state_limit_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the states limit value.
Returns value that represents the states limit value:
NONE - 0 (the default value)
WIDTH - 1
HEIGHT - 2
BOTH - 3
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
Returns
The value that represents the states limit value in case of success, otherwise returns 4.
See also
edje_edit_state_limit_set()
Since
1.11
edje_edit_state_map_on_get()
EAPI Eina_Bool edje_edit_state_map_on_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the flag which enables mapping for the part.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
EINA_TRUE in case if mapping allowed or EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_on_set()
EAPI Eina_Bool edje_edit_state_map_on_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool on)
Enables mapping for the part.
Default is 0.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
on The flag which allow mapping for the part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_perspective_get()
EAPI const char* edje_edit_state_map_perspective_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part's name that is used as the 'perspective point'.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state to get perspective (not including the state value).
value The state value.
Returns
The name of the source part that is used as 'perspective point'.
Since
1.11
References eina_stringshare_add().
edje_edit_state_map_perspective_set()
EAPI Eina_Bool edje_edit_state_map_perspective_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source_part)
Sets the part's name that is used as the 'perspective point'.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state to get perspective (not including the state value).
value The state value.
source_part The source part's name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_light_get()
EAPI const char* edje_edit_state_map_light_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part's name that is used as the 'light' for calculating the brightness.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
The name of the source part that is used as 'light'.
Since
1.11
References eina_stringshare_add().
edje_edit_state_map_light_set()
EAPI Eina_Bool edje_edit_state_map_light_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source_part)
Sets the part that is used as the 'light'.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
source_part The source part's name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_backface_cull_get()
EAPI Eina_Bool edje_edit_state_map_backface_cull_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets backface_cull value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
backface_cull value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_backface_cull_set()
EAPI Eina_Bool edje_edit_state_map_backface_cull_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool backface_cull)
Sets backface_cull value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
backface_cull New backface_cull value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_map_perspective_on_get()
EAPI Eina_Bool edje_edit_state_map_perspective_on_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets perspective_on value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
perspective_on value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_perspective_on_set()
EAPI Eina_Bool edje_edit_state_map_perspective_on_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool perspective_on)
Sets perspective_on value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
perspective_on New perspective_on value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_map_alpha_get()
EAPI Eina_Bool edje_edit_state_map_alpha_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets map.alpha value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
map.alpha value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_alpha_set()
EAPI Eina_Bool edje_edit_state_map_alpha_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool alpha)
Sets map.alpha value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
alpha New map.alpha value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_map_smooth_get()
EAPI Eina_Bool edje_edit_state_map_smooth_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets map.smooth value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
map.smooth value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_smooth_set()
EAPI Eina_Bool edje_edit_state_map_smooth_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool smooth)
Sets map.smooth value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
smooth New map.smooth value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_state_map_rotation_get()
EAPI Eina_Bool edje_edit_state_map_rotation_get (Evas_Object * obj, const char * part, const char * state, double value, double * x, double * y, double * z)
Gets map.rotation of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
x x-rotation.
y x-rotation.
z z-rotation.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_rotation_set()
EAPI Eina_Bool edje_edit_state_map_rotation_set (Evas_Object * obj, const char * part, const char * state, double value, double x, double y, double z)
Sets map.rotation of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
x x-rotation.
y x-rotation.
z z-rotation.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_perspective_focal_get()
EAPI int edje_edit_state_map_perspective_focal_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets map.perspective.focal value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
map.perspective.focal value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_perspective_focal_set()
EAPI Eina_Bool edje_edit_state_map_perspective_focal_set (Evas_Object * obj, const char * part, const char * state, double value, int focal)
Sets map.perspective.focal value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
focal New map.perspective.focal value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_perspective_zplane_get()
EAPI int edje_edit_state_map_perspective_zplane_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets map.perspective.zplane value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
map.perspective.zplane value of given part state.
Since
1.11
References EINA_FALSE.
edje_edit_state_map_perspective_zplane_set()
EAPI Eina_Bool edje_edit_state_map_perspective_zplane_set (Evas_Object * obj, const char * part, const char * state, double value, int zplane)
Sets map.perspective.zplane value of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
zplane New map.perspective.zplane value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_rotation_center_get()
EAPI const char* edje_edit_state_map_rotation_center_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the part's name that is used as the center rotation.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
Returns
The name of the source part that is used as center rotation.
Since
1.11
References eina_stringshare_add().
edje_edit_state_map_zoom_set()
EAPI Eina_Bool edje_edit_state_map_zoom_set (Evas_Object * obj, const char * part, const char * state, double value, double x, double y)
Sets map.zoom (x and y) values of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
x value of x
y value of y
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.19
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_zoom_get()
EAPI Eina_Bool edje_edit_state_map_zoom_get (Evas_Object * obj, const char * part, const char * state, double value, double * x, double * y)
Gets map.zoom (x and y) values of given part state.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
x variable to store value of x
y variable to store value of y
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.19
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_rotation_center_set()
EAPI Eina_Bool edje_edit_state_map_rotation_center_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source_part)
Sets the part that is used as the center of rotation when rotating the part with this description.
If no center is given, the parts original center itself is used for the rotation center.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
source_part The source part's name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References edje_object_calc_force(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_point_color_set()
EAPI Eina_Bool edje_edit_state_map_point_color_set (Evas_Object * obj, const char * part, const char * state, double value, int idx, int r, int g, int b, int a)
Sets the color for vertex/point of the current part.
For more detailed information please
See also
evas_map_point_color_set().
In edje there is (currently) only 4 main point:
Top-Left (0), Top-Right (1), Bottom-Right (2), Bottom-Left (3).
Default value is 255 255 255 255 for every point.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
idx The index of point.
r The red value to set.
g The green color value to set.
b The blue color value to set.
a The alpha color value to set.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_map_point_color_get()
EAPI Eina_Bool edje_edit_state_map_point_color_get (Evas_Object * obj, const char * part, const char * state, double value, int idx, int * r, int * g, int * b, int * a)
Gets the color of given vertex/point of the current part.
For more detailed information please
See also
evas_map_point_color_set().
In edje there is (currently) only 4 main point:
Top-Left (0), Top-Right (1), Bottom-Right (2), Bottom-Left (3).
Default value is 255 255 255 255 for every point.
Parameters
obj Object being edited.
part The name of the part.
state The name of the state (not including the state value).
value The state value.
idx The index of point.
r The red value to get.
g The green color value to get.
b The blue color value to get.
a The alpha color value to get.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_proxy_source_set()
EAPI Eina_Bool edje_edit_state_proxy_source_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source_name)
Sets the source part for given part state.
Set another part content as the content of this part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
source_name The name of part to be set as source. If NULL is passed, the source will be unset.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_state_proxy_source_get()
Since
1.11
References EDJE_PART_TYPE_PROXY, EINA_FALSE, and EINA_TRUE.
edje_edit_state_proxy_source_get()
EAPI Eina_Stringshare* edje_edit_state_proxy_source_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the source name for given state of part.
Note
The returned string should be freed with eina_stringshare_del().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
Returns
The name of the source part in case of success. Otherwise returns NULL.
See also
edje_edit_state_proxy_source_set()
Since
1.11
References EDJE_PART_TYPE_PROXY, and eina_stringshare_add().
edje_edit_state_proxy_source_clip_set()
EAPI Eina_Bool edje_edit_state_proxy_source_clip_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool clip)
Sets the source clip for given PROXY part state.
The source clipper is ignored or used when rendering the proxy part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
clip Value to set if ignore or use source cliper.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_PROXY, EINA_FALSE, and EINA_TRUE.
edje_edit_state_proxy_source_clip_get()
EAPI Eina_Bool edje_edit_state_proxy_source_clip_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the source clip for given PROXY part state.
The source clipper is ignored or used when rendering the proxy part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
Returns
EINA_TRUE in case if source clipper is used, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_PROXY, and EINA_FALSE.
edje_edit_state_proxy_source_visible_set()
EAPI Eina_Bool edje_edit_state_proxy_source_visible_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool visibility)
Sets the source visibility for given PROXY part state.
Defines if both the proxy and its source object will be visible or not. In case of false flag, the source object will not be visible at all while proxy will still show source object.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
visibility Value to set if source object is visible or not.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_PROXY, EINA_FALSE, and EINA_TRUE.
edje_edit_state_proxy_source_visible_get()
EAPI Eina_Bool edje_edit_state_proxy_source_visible_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the source visibility for given PROXY part state.
Defines if both the proxy and its source object will be visible or not. In case of false flag, the source object will not be visible at all while proxy will still show source object.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state.
value The state value.
Returns
EINA_TRUE in case when source object visibility is set to true, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_PROXY, and EINA_FALSE.
edje_edit_state_text_get()
EAPI const char* edje_edit_state_text_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text of a part state.
Remember to free the returned string with edje_edit_string_free().
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text (not including the state value).
value The state value.
Returns
A newly allocated string containing the text for the given state.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_set()
EAPI Eina_Bool edje_edit_state_text_set (Evas_Object * obj, const char * part, const char * state, double value, const char * text)
Sets the text of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text (not including the state value).
value The state value.
text The new text to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_font_get()
EAPI const char* edje_edit_state_font_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets font name for a given part state.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
part The name of the part to get the font of.
state The state of the part to get the font of.
value Value of the state.
Returns
Font used by the part or NULL if error or nothing is set.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_font_set()
EAPI Eina_Bool edje_edit_state_font_set (Evas_Object * obj, const char * part, const char * state, double value, const char * font)
Sets font name for a given part state.
Font name can be any alias of an internal font in the Edje file and, if it doesn't match any, Edje will look for a font with the given name in the system fonts.
Parameters
obj Object being edited.
part Part to set the font of.
state State in which the font is set.
value Value of the state.
font The font name to use.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_text_size_get()
EAPI int edje_edit_state_text_size_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text size (not including the state value).
value The state value.
Returns
The text size or -1 on errors.
References EDJE_PART_TYPE_TEXT, and EDJE_PART_TYPE_TEXTBLOCK.
edje_edit_state_text_size_set()
EAPI Eina_Bool edje_edit_state_text_size_set (Evas_Object * obj, const char * part, const char * state, double value, int size)
Sets the text size of a part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text size (not including the state value).
value The state value.
size The new font size to set (in pixel)
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_text_align_x_get()
EAPI double edje_edit_state_text_align_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text horizontal align of a part state.
The value range is from 0.0(right) to 1.0(left) If the value is between -1.0 and 0.0 then it uses align automatically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text horizontal align (not including the state value).
value The state value.
Returns
The text horizontal align value
edje_edit_state_text_align_y_get()
EAPI double edje_edit_state_text_align_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text vertical align of a part state.
The value range is from 0.0(top) to 1.0(bottom)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text vertical align (not including the state value).
value The state value.
Returns
The text horizontal align value
edje_edit_state_text_align_x_set()
EAPI Eina_Bool edje_edit_state_text_align_x_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Sets the text horizontal align of a part state.
The value range is from 0.0(right) to 1.0(left) If the value is between -1.0 and 0.0 then it uses align automatically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text horizontal align (not including the state value).
value The state value.
align The new text horizontal align value
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_align_y_set()
EAPI Eina_Bool edje_edit_state_text_align_y_set (Evas_Object * obj, const char * part, const char * state, double value, double align)
Sets the text vertical align of a part state.
The value range is from 0.0(top) to 1.0(bottom)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text vertical align (not including the state value).
value The state value.
align The new text vertical align value
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_elipsis_get()
EAPI double edje_edit_state_text_elipsis_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text elipsis of a part state.
The value range is from 0.0(right) to 1.0(left), and -1.0 (if disabled)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the text elipsis value (not including the state value).
value The state value.
Returns
The text elipsis value
edje_edit_state_text_elipsis_set()
EAPI Eina_Bool edje_edit_state_text_elipsis_set (Evas_Object * obj, const char * part, const char * state, double value, double balance)
Sets the text vertical align of a part state.
The value range is from 0.0(right) to 1.0(left) If the value is in range from -1.0 to 0.0 then ellipsis is disabled.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the text elipsis value (not including the state value).
value The state value.
balance The position where to cut the string
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_fit_x_get()
EAPI Eina_Bool edje_edit_state_text_fit_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part fit it's container horizontally.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the if the text part fit it's container horizontally (not including the state value).
value The state value.
Returns
EINA_TRUE If the part fit it's container horizontally, EINA_FALSE otherwise.
edje_edit_state_text_fit_x_set()
EAPI Eina_Bool edje_edit_state_text_fit_x_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fit)
Sets if the text part should fit it's container horizontally.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the if the text part fit it's container horizontally (not including the state value).
value The state value.
fit EINA_TRUE to make the text fit it's container horizontally, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_fit_y_get()
EAPI Eina_Bool edje_edit_state_text_fit_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part fit it's container vertically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the if the text part fit it's container vertically (not including the state value).
value The state value.
Returns
EINA_TRUE If the part fit it's container vertically, EINA_FALSE otherwise.
edje_edit_state_text_fit_y_set()
EAPI Eina_Bool edje_edit_state_text_fit_y_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool fit)
Sets if the text part should fit it's container vertically.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the if the text part fit it's container vertically (not including the state value).
value The state value.
fit EINA_TRUE to make the text fit it's container vertically, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_min_x_get()
EAPI Eina_Bool edje_edit_state_text_min_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part forces the minimum horizontal size of the container to be equal to the minimum horizontal size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the minimum horizontal size of the container to be equal (not including the state value).
value The state value.
Returns
EINA_TRUE If the part forces container's minimum horizontal size, EINA_FALSE otherwise.
edje_edit_state_text_max_x_get()
EAPI Eina_Bool edje_edit_state_text_max_x_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part forces the maximum horizontal size of the container to be equal to the maximum horizontal size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the minimum horizontal size of the container to be equal (not including the state value).
value The state value.
Returns
EINA_TRUE If the part forces container's maximum horizontal size, EINA_FALSE otherwise.
edje_edit_state_text_min_y_get()
EAPI Eina_Bool edje_edit_state_text_min_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part forces the minimum vertical size of the container to be equal to the minimum vertical size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the minimum vertical size of the container to be equal (not including the state value).
value The state value.
Returns
EINA_TRUE If the part forces container's minimum vertical size, EINA_FALSE otherwise.
edje_edit_state_text_max_y_get()
EAPI Eina_Bool edje_edit_state_text_max_y_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the text part forces the maximum vertical size of the container to be equal to the maximum vertical size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the maximum vertical size of the container to be equal (not including the state value).
value The state value.
Returns
EINA_TRUE If the part forces container's maximum vertical size, EINA_FALSE otherwise.
edje_edit_state_text_min_x_set()
EAPI Eina_Bool edje_edit_state_text_min_x_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool v)
Sets if the text part forces the minimum horizontal size of the container to be equal to the minimum horizontal size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the minimum horizontal size of the container to be equal (not including the state value).
value The state value.
v EINA_TRUE to make the text force it's forces container's minimum horizontal size, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_max_x_set()
EAPI Eina_Bool edje_edit_state_text_max_x_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool v)
Sets if the text part forces the maximum horizontal size of the container to be equal to the maximum horizontal size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum horizontal size of the container to be equal (not including the state value).
value The state value.
v EINA_TRUE to make the text force it's forces container's maximum horizontal size, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_min_y_set()
EAPI Eina_Bool edje_edit_state_text_min_y_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool v)
Sets if the text part forces the minimum vertical size of the container to be equal to the minimum vertical size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the minimum vertical size of the container to be equal (not including the state value).
value The state value.
v EINA_TRUE to make the text force it's forces container's minimum vertical size, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_max_y_set()
EAPI Eina_Bool edje_edit_state_text_max_y_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool v)
Sets if the text part forces the maximum vertical size of the container to be equal to the maximum vertical size of the text part.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum vertical size of the container to be equal (not including the state value).
value The state value.
v EINA_TRUE to make the text force it's forces container's maximum vertical size, EINA_FALSE otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_state_text_style_get()
EAPI const char* edje_edit_state_text_style_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets style name for a given part state.
Parameters
obj Object being edited.
part The name of the part to get the style of.
state The state of the part to get the style of.
value Value of the state.
Returns
Style used by the part, or NULL if error or nothing is set.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_style_set()
EAPI Eina_Bool edje_edit_state_text_style_set (Evas_Object * obj, const char * part, const char * state, double value, const char * style)
Sets style name for a given part state.
Causes the part to use the default style and tags defined in the "style" block with the specified name.
Parameters
obj Object being edited.
part Part to set the style of.
state State in which the style is set.
value Value of the state.
style The style name to use. In case when NULL style will removed from textblock part description.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_text_text_source_get()
EAPI const char* edje_edit_state_text_text_source_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets part name, which used as text source.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum vertical size of the container to be equal (not including the state value).
value Value of the state.
Returns
The name of part or NULL, if text_source param not a setted.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_text_source_set()
EAPI Eina_Bool edje_edit_state_text_text_source_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source)
Sets the source text part for a given part.
Causes the part to display the content text of another part and update them as they change.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum vertical size of the container to be equal (not including the state value).
value Value of the state.
source The text source part name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_state_text_source_get()
EAPI const char* edje_edit_state_text_source_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets part name, which used as style text source.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum vertical size of
value Value of the state. The container to be equal (not including the state value).
Returns
The name of part or NULL, if text_source param not a setted.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_source_set()
EAPI Eina_Bool edje_edit_state_text_source_set (Evas_Object * obj, const char * part, const char * state, double value, const char * source)
Sets the source part which would be used as style for text for a given part.
Causes the part to use the text properties (like font and size) of another part and update them as they change.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the maximum vertical size of the container to be equal (not including the state value).
value Value of the state.
source The text source part name.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_state_text_class_get()
EAPI const char* edje_edit_state_text_class_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the text class of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get text class (not including the state value).
value The state value.
Returns
The current text class.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_class_set()
EAPI Eina_Bool edje_edit_state_text_class_set (Evas_Object * obj, const char * part, const char * state, double value, const char * text_class)
Sets the text class of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set text class (not including the state value).
value The state value.
text_class The text class to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_state_text_repch_get()
EAPI const char* edje_edit_state_text_repch_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the replacement character string of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get replacement character (not including the state value).
value The state value.
Returns
The current replacement character.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, and eina_stringshare_add().
edje_edit_state_text_repch_set()
EAPI Eina_Bool edje_edit_state_text_repch_set (Evas_Object * obj, const char * part, const char * state, double value, const char * repch)
Sets the replacement character string of the given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get replacement character (not including the state value).
value The state value.
repch The replacement character string to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_text_size_range_min_max_get()
EAPI Eina_Bool edje_edit_state_text_size_range_min_max_get (Evas_Object * obj, const char * part, const char * state, double value, int * min, int * max)
Gets the min and max font size allowed for the text part.
Parameters
obj Object being edited.
part Part that contain state.
state State in which the part is set.
value Value of the state.
min Minimal value of the font size in points (pt).
max Maximum value of the font size in points (pt).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_state_text_size_range_min_max_set()
EAPI Eina_Bool edje_edit_state_text_size_range_min_max_set (Evas_Object * obj, const char * part, const char * state, double value, int min, int max)
Sets the min and max font size allowed for the text part.
Parameters
obj Object being edited.
part Part that contain state.
state State in which the part is set.
value Value of the state.
min Minimal value of the font size in points (pt).
max Maximum value of the font size in points (pt).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_TEXT, EDJE_PART_TYPE_TEXTBLOCK, EINA_FALSE, and EINA_TRUE.
edje_edit_fonts_list_get()
EAPI Eina_List* edje_edit_fonts_list_get (Evas_Object * obj)
Gets the list of all the fonts in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A list containing all the fonts names found in the edje file.
References eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_list_append(), and eina_stringshare_add().
edje_edit_font_add()
EAPI Eina_Bool edje_edit_font_add (Evas_Object * obj, const char * path, const char * alias)
Adds a new font to the edje file.
The newly created font will be available to all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
path The file path to load the font from.
alias The alias for file, or NULL to use filename
Returns
EINA_TRUE if font cat be loaded, EINA_FALSE otherwise.
edje_edit_font_del()
EAPI Eina_Bool edje_edit_font_del (Evas_Object * obj, const char * alias)
Deletes font from the edje file.
The font will be removed from all the groups in the edje, not only the current one.
Parameters
obj Object being edited.
alias The font alias
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.(including the case when the alias is not valid).
References EINA_FALSE, eina_hash_find(), INF, and WRN.
edje_edit_font_path_get()
EAPI const char* edje_edit_font_path_get (Evas_Object * obj, const char * alias)
Gets font path for a given font alias.
Remember to free the string with edje_edit_string_free()
Parameters
obj Object being edited.
alias The font alias.
Returns
The path of the given font alias.
References eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), and eina_stringshare_add().
edje_edit_image_set_exists()
EAPI Eina_Bool edje_edit_image_set_exists (Evas_Object * obj, const char * image)
Checks if given image name is set of images or not.
Parameters
obj Object being edited.
image a name to check if it is set or not.
Returns
EINA_TRUE in case when given name is set, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, and EINA_TRUE.
edje_edit_image_set_id_get()
EAPI int edje_edit_image_set_id_get (Evas_Object * obj, const char * name)
Gets id of image set.
Parameters
obj Object being edited.
name image set's name.
Returns
The id of the given image name.
Since
1.18
Referenced by edje_edit_image_set_rename(), and edje_edit_set_usage_list_get().
edje_edit_image_set_rename()
EAPI Eina_Bool edje_edit_image_set_rename (Evas_Object * obj, const char * set, const char * new_set)
Renames image set.
Parameters
obj Object being edited.
set image set's name.
new_set new name of image set.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References edje_edit_image_set_id_get(), EINA_FALSE, and EINA_TRUE.
edje_edit_image_set_list_get()
EAPI Eina_List* edje_edit_image_set_list_get (Evas_Object * obj)
Gets the list of all the image sets in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all image sets names found in the edje file.
Since
1.18
References eina_list_append(), and eina_stringshare_add().
edje_edit_set_usage_list_get()
EAPI Eina_List* edje_edit_set_usage_list_get (Evas_Object * obj, const char * name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given set is used.
Use edje_edit_image_usage_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
name The name of the image.
first_only If EINA_TRUE, return only one triplet.
Returns
Eina_List containing Edje_Part_Image_Use if successful, NULL otherwise
References edje_edit_image_set_id_get(), EDJE_PART_TYPE_IMAGE, eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, and eina_iterator_free().
Referenced by edje_edit_image_set_del().
edje_edit_image_set_add()
EAPI Eina_Bool edje_edit_image_set_add (Evas_Object * obj, const char * name)
Adds new image set.
Parameters
obj Object being edited.
name image set's name.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, and EINA_TRUE.
edje_edit_image_set_del()
EAPI Eina_Bool edje_edit_image_set_del (Evas_Object * obj, const char * name)
Deletes image set.
Can't delete set if it is used by any part.
Parameters
obj Object being edited.
name image set's name.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References edje_edit_image_usage_list_free(), edje_edit_set_usage_list_get(), EDJE_PART_TYPE_IMAGE, EET_FILE_MODE_READ_WRITE, EINA_FALSE, eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), EINA_LIST_FREE, EINA_TRUE, and WRN.
edje_edit_image_set_images_list_get()
EAPI Eina_List* edje_edit_image_set_images_list_get (Evas_Object * obj, const char * name)
Gets the list of all images inside of given set in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
name name of image set.
Returns
A List containing all images found inside of given set in the edje file.
Since
1.18
References eina_list_append(), EINA_LIST_FOREACH, and eina_stringshare_add().
edje_edit_image_set_image_add()
EAPI Eina_Bool edje_edit_image_set_image_add (Evas_Object * obj, const char * set_name, const char * name)
Adds image to set.
Add image to given set. If image is not exist inside of edje collection then function
See also
edje_edit_image_add should be used to get image added to edje collection. This function uses only already added functions
Parameters
obj Object being edited.
set_name name of image set.
name image set's name.
Returns
EINA_TRUE on success, EINA_FALSE otherwise (and when image is not exist).
Since
1.18
References edje_edit_image_id_get(), EINA_FALSE, eina_list_append(), and EINA_TRUE.
edje_edit_image_set_image_del()
EAPI Eina_Bool edje_edit_image_set_image_del (Evas_Object * obj, const char * set_name, unsigned int place)
Deletes image on current position from set.
Remove image from given set. To be sure what kind of image will be deleted, firstly check it's position via
See also
edje_edit_image_set_images_list_get function.
Parameters
obj Object being edited.
set_name name of image set.
place position of image to be deleted.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_nth(), eina_list_nth_list(), eina_list_remove_list(), and EINA_TRUE.
edje_edit_image_set_image_min_get()
EAPI Eina_Bool edje_edit_image_set_image_min_get (Evas_Object * obj, const char * set_name, unsigned int place, int * w, int * h)
Gets min size of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
w Where to store the width min value.
h Where to store the height min value.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
edje_edit_image_set_image_min_set()
EAPI Eina_Bool edje_edit_image_set_image_min_set (Evas_Object * obj, const char * set_name, unsigned int place, int w, int h)
Sets min size of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
w New value of picture's min width.
h New value of picture's min height.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
edje_edit_image_set_image_max_get()
EAPI Eina_Bool edje_edit_image_set_image_max_get (Evas_Object * obj, const char * set_name, unsigned int place, int * w, int * h)
Gets max size of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
w Where to store the width max value.
h Where to store the height max value.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
edje_edit_image_set_image_max_set()
EAPI Eina_Bool edje_edit_image_set_image_max_set (Evas_Object * obj, const char * set_name, unsigned int place, int w, int h)
Sets max size of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
w New value of picture's max width.
h New value of picture's max height.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
edje_edit_image_set_image_border_get()
EAPI Eina_Bool edje_edit_image_set_image_border_get (Evas_Object * obj, const char * set_name, unsigned int place, int * l, int * r, int * b, int * t)
Gets border of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
l Where to store the left border value.
r Where to store the right border value.
b Where to store the bottom border value.
t Where to store the top border value.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_nth(), and EINA_TRUE.
edje_edit_image_set_image_border_set()
EAPI Eina_Bool edje_edit_image_set_image_border_set (Evas_Object * obj, const char * set_name, unsigned int place, int l, int r, int b, int t)
Sets border of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
l New value of left border value.
r New value of right border value.
b New value of bottom border value.
t New value of top border value.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_nth(), and EINA_TRUE.
edje_edit_image_set_image_border_scale_get()
EAPI double edje_edit_image_set_image_border_scale_get (Evas_Object * obj, const char * set_name, unsigned int place)
Gets border scale of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
Returns
border scale value on success, -1 otherwise.
Since
1.18
References eina_list_nth().
edje_edit_image_set_image_border_scale_set()
EAPI Eina_Bool edje_edit_image_set_image_border_scale_set (Evas_Object * obj, const char * set_name, unsigned int place, double scale_by)
Sets border scale of set's image.
Parameters
obj Object being edited.
set_name name of image set.
place position of image.
scale_by New border scale.
Returns
EINA_TRUE on success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_nth(), and EINA_TRUE.
edje_edit_images_list_get()
EAPI Eina_List* edje_edit_images_list_get (Evas_Object * obj)
Gets the list of all the images in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all images names found in the edje file.
References eina_list_append(), and eina_stringshare_add().
edje_edit_image_add()
EAPI Eina_Bool edje_edit_image_add (Evas_Object * obj, const char * path)
Adds an new image to the image collection.
This function add the given image inside the edje. Don't add a new image part but only put the image inside the edje file. It actually write directly to the file so you don't have to save. After you have to create a new image_part that use this image. Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
The format of the image files that can be loaded depend on the evas engine on your system
Parameters
obj Object being edited.
path The name of the image file to include in the edje.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References ecore_file_file_get(), EINA_FALSE, eina_stringshare_add(), eina_stringshare_del(), and EINA_TRUE.
edje_edit_image_del()
EAPI Eina_Bool edje_edit_image_del (Evas_Object * obj, const char * name)
Deletes an image from the image collection.
It actually write directly to the file so you don't have to save. Can't delete image if it is used by any part.
Parameters
obj Object being edited.
name The name of the image file to include in the edje.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.(including the case when the name is not valid or image is in use).
References edje_edit_image_usage_list_free(), edje_edit_image_usage_list_get(), EINA_FALSE, EINA_TRUE, and WRN.
edje_edit_image_replace()
EAPI Eina_Bool edje_edit_image_replace (Evas_Object * obj, const char * name, const char * new_name)
Replaces one image in all descriptions.
Parameters
obj Object being edited.
name The name of the image to replace.
new_name The new_name of the image to replace with.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.(including the case when one of the names is not valid)
References edje_edit_image_id_get(), EDJE_PART_TYPE_IMAGE, EET_FILE_MODE_READ_WRITE, EINA_FALSE, eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), and EINA_TRUE.
edje_edit_image_rename()
EAPI Eina_Bool edje_edit_image_rename (Evas_Object * obj, const char * name, const char * new_name)
Renames image.
Parameters
obj Object being edited.
name The name of the image to be renamed.
new_name The new_name of the image.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.(including the case when one of the names is not valid)
Since
1.13
References edje_edit_image_id_get(), EINA_FALSE, and EINA_TRUE.
edje_edit_image_usage_list_get()
EAPI Eina_List* edje_edit_image_usage_list_get (Evas_Object * obj, const char * name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given image is used.
Important! Image can also be used inside of set and plenty of times, so for each use inside of set triplet would set "set's" name into group name, and it's state value would be -1. Every other fields will be 0.
Use edje_edit_image_usage_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
name The name of the image.
first_only If EINA_TRUE, return only one triplet.
Returns
Eina_List containing Edje_Part_Image_Use if successful, NULL otherwise
References edje_edit_image_compression_type_get(), and edje_edit_image_id_get().
Referenced by edje_edit_image_del().
edje_edit_image_usage_list_free()
EAPI void edje_edit_image_usage_list_free (Eina_List * lst)
Frees an Eina_List of (Edje_Part_Image_Use *) allocated by an edje_edit_image_usage_list_get() or an edje_edit_vector_usage_list_get() function.
Parameters
lst List of strings to free.
References EINA_LIST_FREE, eina_stringshare_del(), _Edje_Part_Image_Use::group, _Edje_Part_Image_Use::name, _Edje_Part_Image_Use::part, and _Edje_Part_Image_Use::state.
Referenced by edje_edit_image_del(), edje_edit_image_set_del(), and edje_edit_vector_del().
edje_edit_image_data_add()
EAPI Eina_Bool edje_edit_image_data_add (Evas_Object * obj, const char * name, int id)
Adds an image entry to the image collection.
This function adds the given image entry to the edje image collection. The image needs to be inside the eet already, with key name "images/id". After you have to create a new image_part that use this image, referring to it as "name". Note that all the parts in the edje share the same image collection, thus you can/must use the same image for different part.
Parameters
obj Object being edited.
name The image entry name.
id The image id.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_state_image_get()
EAPI const char* edje_edit_state_image_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets normal image name for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name that is being used (not including the state value).
value The state value.
Returns
The name of the image used by state.
References EDJE_PART_TYPE_IMAGE, and eina_stringshare_add().
edje_edit_state_image_set()
EAPI Eina_Bool edje_edit_state_image_set (Evas_Object * obj, const char * part, const char * state, double value, const char * image)
Sets normal image for a given part state.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image that will be used (not including the state value).
value The state value.
image The name of the image (must be an image contained in the edje file).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, eina_error_set(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_vector_get()
EAPI const char* edje_edit_state_vector_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets normal vector name for a given part state.
Part should be of type VECTOR
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the name that is being used (not including the state value).
value The state value.
Returns
The name of the vector used by state.
Since
1.19
References EDJE_PART_TYPE_VECTOR, and eina_stringshare_add().
edje_edit_state_vector_set()
EAPI Eina_Bool edje_edit_state_vector_set (Evas_Object * obj, const char * part, const char * state, double value, const char * image)
Sets normal vector name for a given part state.
Part should be of type VECTOR
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the vector that will be used (not including the state value).
value The state value.
image The name of the vector (must be contained in the edje file).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.19
References edje_object_calc_force(), EDJE_PART_TYPE_VECTOR, eina_error_set(), EINA_FALSE, and EINA_TRUE.
edje_edit_image_id_get()
EAPI int edje_edit_image_id_get (Evas_Object * obj, const char * image_name)
Gets image id for a given image name.
Parameters
obj Object being edited.
image_name The image name.
Returns
The id of the given image name.
Referenced by edje_edit_image_rename(), edje_edit_image_replace(), edje_edit_image_set_image_add(), and edje_edit_image_usage_list_get().
edje_edit_image_compression_type_get()
EAPI Edje_Edit_Image_Comp edje_edit_image_compression_type_get (Evas_Object * obj, const char * image)
Gets compression type for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
One of Image Compression types. (EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY[_ETC1]).
Referenced by edje_edit_image_usage_list_get().
edje_edit_image_compression_type_set()
EAPI Eina_Bool edje_edit_image_compression_type_set (Evas_Object * obj, const char * image, Edje_Edit_Image_Comp ic)
Sets compression type for the given image.
Parameters
obj Object being edited.
image The name of the image.
ic Edje_Edit_Image_Comp. (EDJE_EDIT_IMAGE_COMP_RAW, EDJE_EDIT_IMAGE_COMP_USER, EDJE_EDIT_IMAGE_COMP_COMP, EDJE_EDIT_IMAGE_COMP_LOSSY[_ETC1]).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE.
edje_edit_image_compression_rate_get()
EAPI int edje_edit_image_compression_rate_get (Evas_Object * obj, const char * image)
Gets compression rate for the given image.
Parameters
obj Object being edited.
image The name of the image.
Returns
The compression rate (if the image is EDJE_EDIT_IMAGE_COMP_LOSSY[_ETC1]) or < 0, on errors.
edje_edit_state_image_border_get()
EAPI void edje_edit_state_image_border_get (Evas_Object * obj, const char * part, const char * state, double value, int * l, int * r, int * t, int * b)
Gets the image border of a part state.
Pass NULL to any of [r,g,b,a] to get only the others.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border (not including the state value).
value The state value.
l A pointer to store the left value
r A pointer to store the right value
t A pointer to store the top value
b A pointer to store the bottom value
References EDJE_PART_TYPE_IMAGE.
edje_edit_state_image_border_set()
EAPI Eina_Bool edje_edit_state_image_border_set (Evas_Object * obj, const char * part, const char * state, double value, int l, int r, int t, int b)
Sets the image border of a part state.
Pass -1 to any of [l,r,t,b] to leave the value untouched.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border (not including the state value).
value The state value.
l Left border value (or -1).
r Right border value (or -1).
t Top border value (or -1).
b Bottom border value (or -1).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, eina_error_set(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_image_border_scale_get()
EAPI Eina_Bool edje_edit_state_image_border_scale_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the border scale value of a part state.
This value tells Edje if the border should be scaled by the object/global edje scale factors
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border scale (not including the state value).
value The state value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_IMAGE, and EINA_FALSE.
edje_edit_state_image_border_scale_set()
EAPI Eina_Bool edje_edit_state_image_border_scale_set (Evas_Object * obj, const char * part, const char * state, double value, Eina_Bool scale)
Sets the border scale value of a part state.
This value tells Edje if the border should be scaled by the object/global edje scale factors
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border scale (not including the state value).
value The state value.
scale New image border scale value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_IMAGE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_image_border_scale_by_get()
EAPI double edje_edit_state_image_border_scale_by_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the border scale by value of a part state.
Valid values are: 0.0 or bigger (0.0 or 1.0 to turn it off)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border scale by (not including the state value).
value The state value.
Returns
border scaling value.
Since
1.18
References EDJE_PART_TYPE_IMAGE, and EINA_FALSE.
edje_edit_state_image_border_scale_by_set()
EAPI Eina_Bool edje_edit_state_image_border_scale_by_set (Evas_Object * obj, const char * part, const char * state, double value, double scale)
Sets the border scale by value of a part state.
Valid values are: 0.0 or bigger (0.0 or 1.0 to turn it off)
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border scale by (not including the state value).
value The state value.
scale New image border scale value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EDJE_PART_TYPE_IMAGE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_image_border_fill_get()
EAPI unsigned char edje_edit_state_image_border_fill_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets if the image center should be draw.
1 or 2 means to draw the center, 0 to don't draw it. If 1 - then the center will apply alpha channel. If 2 (SOLID mode) - then the center of an image wont have alpha channel (Just black color).
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the image border fill (not including the state value).
value The state value.
Returns
2 if the center of the bordered image is draw without alpha, 1 drawing with alpha and 0 not drawing the center.
References EDJE_PART_TYPE_IMAGE.
edje_edit_state_image_border_fill_set()
EAPI Eina_Bool edje_edit_state_image_border_fill_set (Evas_Object * obj, const char * part, const char * state, double value, unsigned char fill)
Sets if the image center should be draw.
1 or 2 means to draw the center, 0 to don't draw it. If 1 - then the center will apply alpha channel. If 2 (SOLID mode) - then the center of an image wont have alpha channel (Just black color).
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to set the image border fill (not including the state value).
value The state value.
fill Fill to be set. 1 or 2 if the center of the bordered image is draw, 0 otherwise.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References edje_object_calc_force(), EDJE_PART_TYPE_IMAGE, eina_error_set(), EINA_FALSE, and EINA_TRUE.
edje_edit_state_tweens_list_get()
EAPI Eina_List* edje_edit_state_tweens_list_get (Evas_Object * obj, const char * part, const char * state, double value)
Gets the list of all the tweens images in the given part state.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to get the list of all the tweens images (not including the state value).
value The state value.
Returns
A string list containing all the image name that form a tween animation in the given part state.
References EDJE_PART_TYPE_IMAGE, eina_list_append(), and eina_stringshare_add().
edje_edit_state_tween_add()
EAPI Eina_Bool edje_edit_state_tween_add (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Adds a new tween frame to the given part state.
The tween param must be the name of an existing image.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to add a new tween frame (not including the state value).
value The state value.
tween The name of the image to add.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_tween_insert_at()
EAPI Eina_Bool edje_edit_state_tween_insert_at (Evas_Object * obj, const char * part, const char * state, double value, const char * tween, int place)
Inserts a new tween frame to the given part state into a specific place.
The tween param must be the name of an existing image.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to add a new tween frame (not including the state value).
value The state value.
tween The name of the image to add.
place Place to be added. It can't be less than 0 or more than current size of tweens.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, EINA_FALSE, and EINA_TRUE.
edje_edit_state_tween_del()
EAPI Eina_Bool edje_edit_state_tween_del (Evas_Object * obj, const char * part, const char * state, double value, const char * tween)
Removes the first tween with the given name.
The image is not removed from the edje.
Parameters
obj Object being edited.
part Part that contain state.
state The name of the state to delete the tween (not including the state value).
value The state value.
tween The name of the image to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_PART_TYPE_IMAGE, EINA_FALSE, and EINA_TRUE.
edje_edit_vector_id_get()
EAPI int edje_edit_vector_id_get (Evas_Object * obj, const char * vector_name)
Gets vector id for a given vector name.
Parameters
obj Object being edited.
vector_name The vector name.
Returns
The id of the given vector name.
Since
1.19
Referenced by edje_edit_vector_usage_list_get().
edje_edit_vectors_list_get()
EAPI Eina_List* edje_edit_vectors_list_get (Evas_Object * obj)
Gets the list of all the vectors in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all vector names found in the edje file.
Since
1.19
References eina_list_append(), and eina_stringshare_add().
edje_edit_vector_del()
EAPI Eina_Bool edje_edit_vector_del (Evas_Object * obj, const char * name)
Deletes vector from the vector collection.
It actually write directly to the file so you don't have to save. Can't delete vector if it is used by any part.
Parameters
obj Object being edited.
name The name of the vector file.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise (including the case when the name is not valid or vector is in use).
Since
1.19
References edje_edit_image_usage_list_free(), edje_edit_vector_usage_list_get(), EINA_FALSE, EINA_TRUE, and WRN.
edje_edit_vector_usage_list_get()
EAPI Eina_List* edje_edit_vector_usage_list_get (Evas_Object * obj, const char * name, Eina_Bool first_only)
Gets list of (Edje_Part_Image_Use *) - group-part-state triplets where given vector is used.
Use edje_edit_image_usage_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
name The name of the vector.
first_only If EINA_TRUE, return only one triplet.
Returns
Eina_List containing Edje_Part_Image_Use if successful, NULL otherwise
Since
1.19
References edje_edit_vector_id_get(), EDJE_PART_TYPE_VECTOR, eina_hash_iterator_data_new(), EINA_ITERATOR_FOREACH, and eina_iterator_free().
Referenced by edje_edit_vector_del().
edje_edit_sound_samples_list_get()
EAPI Eina_List* edje_edit_sound_samples_list_get (Evas_Object * obj)
Gets the list of all the sounds samples in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all sounds samples names found in the edje file.
Since
1.11
References eina_list_append(), and eina_stringshare_add().
edje_edit_sound_tones_list_get()
EAPI Eina_List* edje_edit_sound_tones_list_get (Evas_Object * obj)
Gets the list of all the sounds tones in the given edje.
Use edje_edit_string_list_free() when you don't need the list anymore.
Parameters
obj Object being edited.
Returns
A List containing all sounds tones names found in the edje file.
Since
1.11
References eina_list_append(), and eina_stringshare_add().
edje_edit_sound_sample_add()
EAPI Eina_Bool edje_edit_sound_sample_add (Evas_Object * obj, const char * name, const char * snd_src)
Adds new sound sample to samples collection.
This function adds the given sound file to the edje collection. The added sound sample could be used by PLAY_SAMPLE action in any program of any group that is in the current collection. The quality of added sound by default is uncompressed (RAW).
The available formats list of the sound files that can be loaded depends on the evas engine on your system.
Parameters
obj Object being edited.
name The name that will identify sample.
snd_src The name of the sound file to add.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_sound_sample_del()
Since
1.11
References EINA_FALSE.
edje_edit_sound_sample_del()
EAPI Eina_Bool edje_edit_sound_sample_del (Evas_Object * obj, const char * name)
Deletes sound sample from the collection.
Deletes sound sample from collection by its name. After successful deletion all PLAY_SAMPLE actions in all programs of all groups of current collection that use deleted sound will be deleted.
Parameters
obj Object being edited.
name The name of the sound to be deleted from the edje.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_sound_sample_add()
Since
1.11
References EINA_FALSE, and WRN.
edje_edit_sound_tone_add()
EAPI Eina_Bool edje_edit_sound_tone_add (Evas_Object * obj, const char * name, int frequency)
Adds new tone to the collection.
This function adds new tone with given frequency to the edje collection. The added sound sample could be used by PLAY_TONE action in any program of any group that is in the current collection.
Parameters
obj Object being edited.
name The name that will identify tone.
frequency Frequency of added tone. This value should be in range of 20 to 20000 inclusive.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_sound_tone_del()
Since
1.11
References EINA_FALSE, eina_stringshare_add(), EINA_TRUE, and WRN.
edje_edit_sound_tone_del()
EAPI Eina_Bool edje_edit_sound_tone_del (Evas_Object * obj, const char * name)
Deletes tone from the collection.
Deletes tone from collection by its name. After successful deletion all PLAY_TONE actions in all programs of all groups of current collection that use deleted sound will be deleted.
Parameters
obj Object being edited.
name The name of the tone to be deleted from the edje.
Returns
EINA_TRUE if successful, EINA_FALSE otherwise.
See also
edje_edit_sound_tone_add()
Since
1.11
References EDJE_ACTION_TYPE_SOUND_TONE, EET_FILE_MODE_READ_WRITE, EINA_FALSE, EINA_TRUE, and WRN.
edje_edit_sound_compression_rate_get()
EAPI double edje_edit_sound_compression_rate_get (Evas_Object * obj, const char * sound)
Gets the sound quality compression.
Parameters
obj Object being edited.
sound The name of the sample.
Returns
Quality of the compression of the sample sound.
Since
1.11
edje_edit_sound_compression_rate_set()
EAPI Eina_Bool edje_edit_sound_compression_rate_set (Evas_Object * obj, const char * sound, double rate)
Sets the sound quality compression.
Parameters
obj Object being edited.
sound The name of the sample.
rate Quality of the compression.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_sound_tone_frequency_set()
EAPI Eina_Bool edje_edit_sound_tone_frequency_set (Evas_Object * obj, const char * name, int frequency)
Sets the frequency of tone.
Parameters
obj Object being edited.
name The name of the tone.
frequency The value of frequency of tone. This value has to be in range of 20 to 20000 inclusive.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
See also
edje_edit_sound_tone_frequency_get()
Since
1.11
References EINA_FALSE, and EINA_TRUE.
edje_edit_sound_tone_frequency_get()
EAPI int edje_edit_sound_tone_frequency_get (Evas_Object * obj, const char * name)
Gets the frequency of tone.
Parameters
obj Object being edited.
name The name of the tone.
Returns
The frequency of tone if successful, otherwise returns -1.
See also
edje_edit_sound_tone_frequency_set()
Since
1.11
edje_edit_sound_compression_type_get()
EAPI Edje_Edit_Sound_Comp edje_edit_sound_compression_type_get (Evas_Object * obj, const char * name)
Gets the sound type compression.
Parameters
obj Object being edited.
name The name of the sample.
Returns
Compression type of the sample sound.
Since
1.11
edje_edit_sound_compression_type_set()
EAPI Eina_Bool edje_edit_sound_compression_type_set (Evas_Object * obj, const char * name, Edje_Edit_Sound_Comp sc)
Sets the sound type compression.
Parameters
obj Object being edited.
name The name of the sample.
sc Edje_Edit_Sound_Comp (EDJE_EDIT_SOUND_COMP_RAW, EDJE_EDIT_SOUND_COMP_COMP, EDJE_EDIT_SOUND_COMP_LOSSY, EDJE_EDIT_SOUND_COMP_AS_IS).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.11
edje_edit_sound_samplebuffer_get()
EAPI Eina_Binbuf* edje_edit_sound_samplebuffer_get (Evas_Object * obj, const char * sample_name)
Gets the certain sound data from the edje object.
Parameters
obj Object being edited.
sample_name The name of the sound.
Returns
buf The buffer that contains data of the sound. To free the resources use eina_binbuf_free().
Since
1.11
edje_edit_sound_samplesource_get()
EAPI const char* edje_edit_sound_samplesource_get (Evas_Object * obj, const char * sample_name)
Gets the name of sample source.
Parameters
obj Object being edited.
sample_name The name of the sample.
Returns
snd_src The sample source name.
Since
1.11
References eina_stringshare_add(), and ERR.
edje_edit_spectrum_list_get()
EAPI Eina_List* edje_edit_spectrum_list_get (Evas_Object * obj)
Gets the list of all the spectrum in the given edje object.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
Returns
A list containing all the spectra names.
edje_edit_spectra_add()
EAPI Eina_Bool edje_edit_spectra_add (Evas_Object * obj, const char * name)
Adds a new spectra in the given edje object.
Parameters
obj Object being edited.
name The name of the spectra to include in the edje.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_spectra_del()
EAPI Eina_Bool edje_edit_spectra_del (Evas_Object * obj, const char * spectra)
Deletes the given spectra from the edje object.
Parameters
obj Object being edited.
spectra The name of the spectra to delete.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_spectra_name_set()
EAPI Eina_Bool edje_edit_spectra_name_set (Evas_Object * obj, const char * spectra, const char * name)
Changes the name of the given spectra.
Parameters
obj Object being edited.
spectra The name of the current spectra.
name The new name to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_spectra_stop_num_get()
EAPI int edje_edit_spectra_stop_num_get (Evas_Object * obj, const char * spectra)
Gets the number of stops in the given spectra.
Parameters
obj Object being edited.
spectra The name of the spectra.
Returns
The number of stops (or 0 on errors).
edje_edit_spectra_stop_num_set()
EAPI Eina_Bool edje_edit_spectra_stop_num_set (Evas_Object * obj, const char * spectra, int num)
Sets the number of stops in the given spectra.
Parameters
obj Object being edited.
spectra The name of the spectra.
num The number of stops you want
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_spectra_stop_color_get()
EAPI Eina_Bool edje_edit_spectra_stop_color_get (Evas_Object * obj, const char * spectra, int stop_number, int * r, int * g, int * b, int * a, int * d)
Gets the colors of the given stop.
Parameters
obj Object being edited.
spectra The name of the spectra.
stop_number The number of the stop,
r Where to store the red color value,
g Where to store the green color value,
b Where to store the blue color value,
a Where to store the alpha color value,
d Where to store the delta stop value,
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_spectra_stop_color_set()
EAPI Eina_Bool edje_edit_spectra_stop_color_set (Evas_Object * obj, const char * spectra, int stop_number, int r, int g, int b, int a, int d)
Sets the colors of the given stop.
Parameters
obj Object being edited.
spectra The name of the spectra.
stop_number The number of the stops,
r The red color value to set,
g The green color value to set,
b The blue color value to set,
a The alpha color value to set,
d The delta stop value to set,
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_programs_list_get()
EAPI Eina_List* edje_edit_programs_list_get (Evas_Object * obj)
Gets the list of all the programs in the given edje object.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
Returns
A list containing all the program names.
References eina_list_append(), and eina_stringshare_add().
edje_edit_program_add()
EAPI Eina_Bool edje_edit_program_add (Evas_Object * obj, const char * name)
Adds a new program to the edje file.
If a program with the same name just exist the function will fail.
Parameters
obj Object being edited.
name The name of the new program.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_CHANNEL_EFFECT, EINA_FALSE, eina_stringshare_add(), and EINA_TRUE.
edje_edit_program_del()
EAPI Eina_Bool edje_edit_program_del (Evas_Object * obj, const char * prog)
Removes the given program from the edje file.
Parameters
obj Object being edited.
prog The name of the program to remove.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_ACTION_TYPE_ACTION_STOP, EINA_FALSE, eina_hash_add(), eina_hash_find(), EINA_LIST_FOREACH_SAFE, EINA_LIST_FREE, eina_list_remove_list(), and EINA_TRUE.
edje_edit_program_exist()
EAPI Eina_Bool edje_edit_program_exist (Evas_Object * obj, const char * prog)
Checks if a program with the given name exist in the edje object.
Parameters
obj Object being edited.
prog The prog of the program that will be searched.
Returns
EINA_TRUE if the program exist, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_run()
EAPI Eina_Bool edje_edit_program_run (Evas_Object * obj, const char * prog)
Runs the given program.
Parameters
obj Object being edited.
prog The name of the program to execute.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_stop_all()
EAPI Eina_Bool edje_edit_program_stop_all (Evas_Object * obj)
Stops all running programs.
Parameters
obj Object being edited.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH_SAFE, and EINA_TRUE.
edje_edit_program_transition_state_set()
EAPI Eina_Bool edje_edit_program_transition_state_set (Evas_Object * obj, const char * prog, double pos)
Sets parts into intermediate state of programs transition.
Parameters
obj Object being edited.
prog The name of the program to use. Program should have action STATE_SET.
pos State of transition to be setted. Value from 0.0 to 1.0. 0.0 represents the start state, 1.0 - the final state. Other values will set parts to an intermediate state taking into account programs transition type.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_ACTION_TYPE_STATE_SET, EINA_FALSE, EINA_LIST_FOREACH, and EINA_TRUE.
edje_edit_program_name_set()
EAPI Eina_Bool edje_edit_program_name_set (Evas_Object * obj, const char * prog, const char * new_name)
Sets a new name for the given program.
Parameters
obj Object being edited.
prog The current program name.
new_name The new name to assign.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_source_get()
EAPI const char* edje_edit_program_source_get (Evas_Object * obj, const char * prog)
Gets source of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get source.
Returns
The source value per program.
References eina_stringshare_add().
edje_edit_program_source_set()
EAPI Eina_Bool edje_edit_program_source_set (Evas_Object * obj, const char * prog, const char * source)
Sets source of the given program.
Parameters
obj Object being edited.
prog The name of the program to set source.
source The new source value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_signal_get()
EAPI const char* edje_edit_program_signal_get (Evas_Object * obj, const char * prog)
Gets signal of a given program.
Remember to free the returned string using edje_edit_string_free().
Parameters
obj Object being edited.
prog The name of the program to get the signal.
Returns
The signal value for program.
References eina_stringshare_add().
edje_edit_program_signal_set()
EAPI Eina_Bool edje_edit_program_signal_set (Evas_Object * obj, const char * prog, const char * signal)
Sets signal of the given program.
Parameters
obj Object being edited.
prog The name of the program to set the signal.
signal The new signal value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_in_from_get()
EAPI double edje_edit_program_in_from_get (Evas_Object * obj, const char * prog)
Gets in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the delay.
Returns
The delay.
edje_edit_program_in_from_set()
EAPI Eina_Bool edje_edit_program_in_from_set (Evas_Object * obj, const char * prog, double seconds)
Sets in.from of a given program.
Parameters
obj Object being edited.
prog The name of the program to set the delay.
seconds Number of seconds to delay the program execution
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_in_range_get()
EAPI double edje_edit_program_in_range_get (Evas_Object * obj, const char * prog)
Gets in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to get random delay.
Returns
The delay random.
edje_edit_program_in_range_set()
EAPI Eina_Bool edje_edit_program_in_range_set (Evas_Object * obj, const char * prog, double seconds)
Sets in.range of a given program.
Parameters
obj Object being edited.
prog The name of the program to set random delay.
seconds Max random number of seconds to delay.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_action_get()
EAPI Edje_Action_Type edje_edit_program_action_get (Evas_Object * obj, const char * prog)
Gets the action of a given program.
Parameters
obj Object being edited.
prog The name of the program to get the action.
Returns
The action type, or -1 on errors. Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
edje_edit_program_action_set()
EAPI Eina_Bool edje_edit_program_action_set (Evas_Object * obj, const char * prog, Edje_Action_Type action)
Sets the action of a given program.
Action can be one of EDJE_ACTION_TYPE_NONE, _STATE_SET, ACTION_STOP, SIGNAL_EMIT, DRAG_VAL_SET, _DRAG_VAL_STEP, _DRAG_VAL_PAGE, _SCRIPT
Parameters
obj Object being edited.
prog The name of the program to set the action.
action The new action type.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_ACTION_TYPE_ACTION_STOP, EDJE_ACTION_TYPE_DRAG_VAL_PAGE, EDJE_ACTION_TYPE_DRAG_VAL_SET, EDJE_ACTION_TYPE_DRAG_VAL_STEP, EDJE_ACTION_TYPE_FOCUS_OBJECT, EDJE_ACTION_TYPE_FOCUS_SET, EDJE_ACTION_TYPE_LAST, EDJE_ACTION_TYPE_PHYSICS_FORCES_CLEAR, EDJE_ACTION_TYPE_PHYSICS_ROT_SET, EDJE_ACTION_TYPE_PHYSICS_STOP, EDJE_ACTION_TYPE_SCRIPT, EDJE_ACTION_TYPE_SIGNAL_EMIT, EDJE_ACTION_TYPE_STATE_SET, edje_edit_program_targets_clear(), EINA_FALSE, eina_hash_find(), eina_hash_set(), and EINA_TRUE.
edje_edit_program_targets_get()
EAPI Eina_List* edje_edit_program_targets_get (Evas_Object * obj, const char * prog)
Gets the list of the targets for the given program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the program to get the list of the targets.
Returns
A list with all the targets names, or NULL on error.
edje_edit_program_target_add()
EAPI Eina_Bool edje_edit_program_target_add (Evas_Object * obj, const char * prog, const char * target)
Adds a new target program to the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP, then 'target' must be an existing program name. If it's EDJE_ACTION_TYPE_STATE_SET, then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to add a new target.
target The name of the new target itself.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_append(), and EINA_TRUE.
edje_edit_program_target_insert_at()
EAPI Eina_Bool edje_edit_program_target_insert_at (Evas_Object * obj, const char * prog, const char * target, int place)
Adds a new target program to certain place in list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP, then 'target' must be an existing program name. If it's EDJE_ACTION_TYPE_STATE_SET, then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to add a new target.
target The name of the new target itself.
place Specific play for target to be inserted into.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_append(), eina_list_count(), eina_list_nth_list(), eina_list_prepend_relative_list(), and EINA_TRUE.
edje_edit_program_target_del()
EAPI Eina_Bool edje_edit_program_target_del (Evas_Object * obj, const char * prog, const char * target)
Deletes a target from the list of 'targets' in the given program.
If program action is EDJE_ACTION_TYPE_ACTION_STOP then 'target' must be an existing program name. If action is EDJE_ACTION_TYPE_STATE_SET then 'target' must be an existing part name.
Parameters
obj Object being edited.
prog The name of the program to del a target from the list of targets.
target The name of another program or another part.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, eina_list_remove_list(), and EINA_TRUE.
edje_edit_program_targets_clear()
EAPI Eina_Bool edje_edit_program_targets_clear (Evas_Object * obj, const char * prog)
Clears the 'targets' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to clear the 'targets' list.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_data_get(), eina_list_remove_list(), and EINA_TRUE.
Referenced by edje_edit_program_action_set().
edje_edit_program_afters_get()
EAPI Eina_List* edje_edit_program_afters_get (Evas_Object * obj, const char * prog)
Gets the list of action that will be run after the give program.
Use edje_edit_string_list_free() when you don't need it anymore.
Parameters
obj Object being edited.
prog The name of the program to get the list of actions
Returns
A list with all program names, or NULL on error.
edje_edit_program_after_add()
EAPI Eina_Bool edje_edit_program_after_add (Evas_Object * obj, const char * prog, const char * after)
Adds a new program name to the list of 'afters' in the given program.
All the programs listed in 'afters' will be executed after program execution.
Parameters
obj Object being edited.
prog The name of the program that contains the list of afters
after The name of another program to add to the afters list
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_append(), and EINA_TRUE.
edje_edit_program_after_insert_at()
EAPI Eina_Bool edje_edit_program_after_insert_at (Evas_Object * obj, const char * prog, const char * after, int place)
Adds a new program name into specific place in list of 'afters' in the given program.
All the programs listed in 'afters' will be executed after program execution.
Parameters
obj Object being edited.
prog The name of the program that contains the list of afters
after The name of another program to add to the afters list
place Specific place for after to be inserted into. Note that if place is greater than total number of afters then it would append to the end of list
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
Since
1.18
References EINA_FALSE, eina_list_append(), eina_list_count(), eina_list_nth_list(), eina_list_prepend_relative_list(), and EINA_TRUE.
edje_edit_program_after_del()
EAPI Eina_Bool edje_edit_program_after_del (Evas_Object * obj, const char * prog, const char * after)
Deletes the given program from the list of 'afters' of the program.
Parameters
obj Object being edited.
prog The name of the program from where to remove the after.
after The name of the program to remove from the list of afters.
Returns
EINA_TRUE is successful or not in the list, EINA_FALSE otherwise.
References EINA_FALSE, EINA_LIST_FOREACH, eina_list_remove_list(), and EINA_TRUE.
edje_edit_program_afters_clear()
EAPI Eina_Bool edje_edit_program_afters_clear (Evas_Object * obj, const char * prog)
Clears the 'afters' list of the given program.
Parameters
obj Object being edited.
prog The name of the program to clear the 'afters' list.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, eina_list_data_get(), eina_list_remove_list(), and EINA_TRUE.
edje_edit_program_state_get()
EAPI const char* edje_edit_program_state_get (Evas_Object * obj, const char * prog)
Get the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to get the state.
Returns
The name of the state.
References eina_stringshare_add().
edje_edit_program_api_name_get()
EAPI const char* edje_edit_program_api_name_get (Evas_Object * obj, const char * prog)
Gets api's name of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
Name of the api if successful, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_api_description_get()
EAPI const char* edje_edit_program_api_description_get (Evas_Object * obj, const char * prog)
Gets api's description of a program.
Parameters
obj Object being edited.
prog Name of program.
Returns
Description of the api if successful, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_api_name_set()
EAPI Eina_Bool edje_edit_program_api_name_set (Evas_Object * obj, const char * prog, const char * name)
Sets api's name of a program.
Parameters
obj Object being edited.
prog Name of the part.
name New name for the api property.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_api_description_set()
EAPI Eina_Bool edje_edit_program_api_description_set (Evas_Object * obj, const char * prog, const char * description)
Sets api's description of a program.
Parameters
obj Object being edited.
prog Name of the program.
description New description for the api property.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_state_set()
EAPI Eina_Bool edje_edit_program_state_set (Evas_Object * obj, const char * prog, const char * state)
Sets the state for the given program.
In a STATE_SET action this is the name of state to set. In a SIGNAL_EMIT action is the name of the signal to emit.
Parameters
obj Object being edited.
prog The name of the program to set a state.
state The name of the state to set (not including the state value)
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_value_get()
EAPI double edje_edit_program_value_get (Evas_Object * obj, const char * prog)
Gets the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to get the value of state.
Returns
The value of state for the program.
edje_edit_program_value_set()
EAPI Eina_Bool edje_edit_program_value_set (Evas_Object * obj, const char * prog, double value)
Sets the value of state for the given program.
In a STATE_SET action this is the value of state to set. Not used on SIGNAL_EMIT action.
Parameters
obj Object being edited.
prog The name of the program to set the value of state.
value The vale to set.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_state2_get()
EAPI const char* edje_edit_program_state2_get (Evas_Object * obj, const char * prog)
Gets the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to get the state2.
Returns
The source to emit for the program.
References eina_stringshare_add().
edje_edit_program_state2_set()
EAPI Eina_Bool edje_edit_program_state2_set (Evas_Object * obj, const char * prog, const char * state2)
Sets the state2 for the given program.
In a STATE_SET action is not used In a SIGNAL_EMIT action is the source of the emitted signal.
Parameters
obj Object being edited.
prog The name of the program to set the state2.
state2 The name of the state to set.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_value2_get()
EAPI double edje_edit_program_value2_get (Evas_Object * obj, const char * prog)
Gets the value of state2 for the given program.
Parameters
obj Object being edited.
prog The name of the program to get the state2 value.
Returns
The vale of the state2 for the program.
edje_edit_program_value2_set()
EAPI Eina_Bool edje_edit_program_value2_set (Evas_Object * obj, const char * prog, double value)
Sets the value2 of state for the given program.
This is used in DRAG_ACTION
Parameters
obj Object being edited.
prog The name of the program to set the state2 value.
value The value of the state2 to set.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_transition_get()
EAPI Edje_Tween_Mode edje_edit_program_transition_get (Evas_Object * obj, const char * prog)
Gets the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to get the transition.
Returns
The type of transition used by program.
edje_edit_program_transition_set()
EAPI Eina_Bool edje_edit_program_transition_set (Evas_Object * obj, const char * prog, Edje_Tween_Mode transition)
Sets the type of transition to use when apply animations.
Can be one of: EDJE_TWEEN_MODE_NONE, EDJE_TWEEN_MODE_LINEAR, EDJE_TWEEN_MODE_SINUSOIDAL, EDJE_TWEEN_MODE_ACCELERATE or EDJE_TWEEN_MODE_DECELERATE.
Parameters
obj Object being edited.
prog The name of the program to set the transition.
transition The transition type to set
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_transition_value1_get()
EAPI double edje_edit_program_transition_value1_get (Evas_Object * obj, const char * prog)
Gets the interpolation value 1 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_ACCELERATE_FACTOR, EDJE_TWEEN_MODE_DECELERATE_FACTOR, EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR, EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_BOUNCE or EDJE_TWEEN_MODE_SPRING.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 1.
Returns
Interpolation value 1.
edje_edit_program_transition_value1_set()
EAPI Eina_Bool edje_edit_program_transition_value1_set (Evas_Object * obj, const char * prog, double value)
Sets the interpolation value 1 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_ACCELERATE_FACTOR, EDJE_TWEEN_MODE_DECELERATE_FACTOR, EDJE_TWEEN_MODE_SINUSOIDAL_FACTOR, EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_BOUNCE or EDJE_TWEEN_MODE_SPRING.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 1.
value The interpolation value 1 for the transition.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_program_transition_value2_get()
EAPI double edje_edit_program_transition_value2_get (Evas_Object * obj, const char * prog)
Gets the interpolation value 2 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_BOUNCE or EDJE_TWEEN_MODE_SPRING.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 2.
Returns
Interpolation value 2.
edje_edit_program_transition_value2_set()
EAPI Eina_Bool edje_edit_program_transition_value2_set (Evas_Object * obj, const char * prog, double value)
Sets the interpolation value 2 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_DIVISOR_INTERP, EDJE_TWEEN_MODE_BOUNCE or EDJE_TWEEN_MODE_SPRING.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 2.
value The interpolation value 2 for the transition.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_program_transition_value3_get()
EAPI double edje_edit_program_transition_value3_get (Evas_Object * obj, const char * prog)
Gets the interpolation value 3 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_CUBIC_BEZIER.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 3.
Returns
Interpolation value 3.
edje_edit_program_transition_value3_set()
EAPI Eina_Bool edje_edit_program_transition_value3_set (Evas_Object * obj, const char * prog, double value)
Sets the interpolation value 3 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_CUBIC_BEZIER.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 3.
value The interpolation value 3 for the transition.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_program_transition_value4_get()
EAPI double edje_edit_program_transition_value4_get (Evas_Object * obj, const char * prog)
Gets the interpolation value 4 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_CUBIC_BEZIER.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 4.
Returns
Interpolation value 4.
edje_edit_program_transition_value4_set()
EAPI Eina_Bool edje_edit_program_transition_value4_set (Evas_Object * obj, const char * prog, double value)
Sets the interpolation value 4 of the transition.
Can be used with one of transition type: EDJE_TWEEN_MODE_CUBIC_BEZIER.
Parameters
obj Object being edited.
prog The name of the program to get the interpolation value 4.
value The interpolation value 4 for the transition.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
edje_edit_program_transition_time_get()
EAPI double edje_edit_program_transition_time_get (Evas_Object * obj, const char * prog)
Gets the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to get the transition time.
Returns
The duration of the transition.
edje_edit_program_transition_time_set()
EAPI Eina_Bool edje_edit_program_transition_time_set (Evas_Object * obj, const char * prog, double seconds)
Sets the duration of the transition in seconds.
Parameters
obj Object being edited.
prog The name of the program to set the transition time.
seconds The duration of the transition (in seconds).
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_sample_name_get()
EAPI const char* edje_edit_program_sample_name_get (Evas_Object * obj, const char * prog)
Gets sample name of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
const char* sample_name on success, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_sample_name_set()
EAPI Eina_Bool edje_edit_program_sample_name_set (Evas_Object * obj, const char * prog, const char * name)
Sets sample name of the program.
Parameters
obj Object being edited.
prog The name of the program.
name The name of the sample.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_tone_name_get()
EAPI const char* edje_edit_program_tone_name_get (Evas_Object * obj, const char * prog)
Gets tone name of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
const char* tone_name on success, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_tone_name_set()
EAPI Eina_Bool edje_edit_program_tone_name_set (Evas_Object * obj, const char * prog, const char * name)
Sets tone name of the program.
Parameters
obj Object being edited.
prog The name of the program.
name The name of the tone.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_sample_speed_get()
EAPI double edje_edit_program_sample_speed_get (Evas_Object * obj, const char * prog)
Gets sample speed of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
Double speed on success, -1 otherwise.
edje_edit_program_sample_speed_set()
EAPI Eina_Bool edje_edit_program_sample_speed_set (Evas_Object * obj, const char * prog, double speed)
Sets sample speed of the program.
Parameters
obj Object being edited.
prog The name of the program.
speed New speed value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_tone_duration_get()
EAPI double edje_edit_program_tone_duration_get (Evas_Object * obj, const char * prog)
Gets tone duration of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
Double duration on success, -1 otherwise.
edje_edit_program_tone_duration_set()
EAPI Eina_Bool edje_edit_program_tone_duration_set (Evas_Object * obj, const char * prog, double duration)
Sets tone duration of the program.
Parameters
obj Object being edited.
prog The name of the program.
duration New duration value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_channel_get()
EAPI unsigned char edje_edit_program_channel_get (Evas_Object * obj, const char * prog)
Gets sample channel of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
Channel on success, 0 otherwise.
edje_edit_program_channel_set()
EAPI Eina_Bool edje_edit_program_channel_set (Evas_Object * obj, const char * prog, Edje_Channel channel)
Sets sample channel of the program.
Parameters
obj Object being edited.
prog The name of the program.
channel New channel value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_filter_part_get()
EAPI const char* edje_edit_program_filter_part_get (Evas_Object * obj, const char * prog)
Gets filter part name of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
const char* part_name on success, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_filter_part_set()
EAPI Eina_Bool edje_edit_program_filter_part_set (Evas_Object * obj, const char * prog, const char * filter_part)
Sets filter part name of the program.
Parameters
obj Object being edited.
prog The name of the program.
filter_part The name of the part to be set as filter.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_program_filter_state_get()
EAPI const char* edje_edit_program_filter_state_get (Evas_Object * obj, const char * prog)
Gets filter state of the program.
Parameters
obj Object being edited.
prog The name of the program.
Returns
const char* state_name on success, NULL otherwise.
References eina_stringshare_add().
edje_edit_program_filter_state_set()
EAPI Eina_Bool edje_edit_program_filter_state_set (Evas_Object * obj, const char * prog, const char * filter_state)
Sets filter state of the program.
Parameters
obj Object being edited.
prog The name of the program.
filter_state New filter state value.
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_script_get()
EAPI char* edje_edit_script_get (Evas_Object * obj)
Gets the Embryo script for the group of the given object.
Get the shared script for the group under edition. Shared script means the script {} block for the group, not counting what's in each program. It returns a malloc'd duplicate of the code, so users are free to modify the contents directly and they should remember to free() it when done. NULL will be returned if there's no script or an error occurred.
Parameters
obj Object being edited.
Returns
The shared script code for this group.
edje_edit_script_set()
EAPI Eina_Bool edje_edit_script_set (Evas_Object * obj, const char * code)
Sets the code for the group script.
Set the Embryo source code for the shared script of the edited group. Note that changing the code itself will not update the running VM, you need to call
See also
edje_edit_script_compile() for it to get updated.
Parameters
obj The object being edited
code The Embryo source
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_script_program_get()
EAPI char* edje_edit_script_program_get (Evas_Object * obj, const char * prog)
Gets the Embryo script for the given program.
Get the script code for the given program. Like the group script, this function returns a duplicate of the code that the user can modify at will and must free when done using it. NULL will be returned if the program doesn't exist, doesn't have any script or is not of type script.
Parameters
obj Object being edited
prog Program name
Returns
The program script code
References EDJE_ACTION_TYPE_SCRIPT, and eina_hash_find().
edje_edit_script_program_set()
EAPI Eina_Bool edje_edit_script_program_set (Evas_Object * obj, const char * prog, const char * code)
Sets the Embryo script for the given program.
Set the Embryo source code for the program prog. It must be an existing program of type EDJE_ACTION_TYPE_SCRIPT, or the function will fail and do nothing. Note that changing the code itself will not update the running VM, you need to call
See also
edje_edit_script_compile() for it to get updated.
Parameters
obj The object being edited
prog The program name
code The Embryo source
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EDJE_ACTION_TYPE_SCRIPT, EINA_FALSE, eina_hash_find(), and EINA_TRUE.
edje_edit_script_compile()
EAPI Eina_Bool edje_edit_script_compile (Evas_Object * obj)
Compiles the Embryo script for the given object.
If required, this function will process all script code for the group and build the bytecode, updating the running Embryo VM Program if the build is successful.
Parameters
obj The object being edited
Returns
EINA_TRUE in case of success, EINA_FALSE otherwise.
References EINA_FALSE, and EINA_TRUE.
edje_edit_script_error_list_get()
EAPI const Eina_List* edje_edit_script_error_list_get (Evas_Object * obj)
Gets the list of errors resulting from the last script build.
Get the list of errors that resulted from the last attempt to rebuild the Embryo script for the edited group. This will be a standard Eina_List with Edje_Edit_Script_Error pointers as its data. The user should not do anything else but read the contents of this list. These errors can be the output of the embryo compiler, or internal errors generated by Edje_Edit if the preprocessing of the scripts failed.
Parameters
obj The object being edited
Returns
A constant list of Edje_Edit_Script_Error, or NULL if there are none
edje_edit_source_generate()
EAPI const char* edje_edit_source_generate (Evas_Object * obj)
Returns source code of the current edje edit object.
Remember to free the string with edje_edit_string_free().
This function will return source code of the whole group, loaded previously. This function also will collect all possible resources that is required and mentioned in description blocks. For example: all images, fonts, data, styles, and color_classes.
Parameters
obj The object being edited
Returns
Source code containing all resources required by the object.
References EINA_FALSE.
edje_edit_object_source_generate()
EAPI const char* edje_edit_object_source_generate (Evas_Object * obj)
Returns source code of the current edje edit object.
Remember to free the string with edje_edit_string_free().
This function will return source code of the whole group, loaded previously. This function also will collect all possible resources that is required and mentioned in description blocks. For example: all images, fonts, styles and color_classes.
Note
A source code will be top block 'collection'.
Parameters
obj The object being edited
Returns
Source code containing all resources required by the object.
References EINA_TRUE.
edje_edit_full_source_generate()
EAPI char* edje_edit_full_source_generate (Evas_Object * obj)
Returns source code of all collections.
Remember to free the string with free().
This function will generate and return source code of all collections and other top level blocks.
Parameters
obj The object being edited
Returns
Source code as char *.
References eina_strbuf_free(), and eina_strbuf_string_steal().
edje_edit_data_source_generate()
EAPI const char* edje_edit_data_source_generate (Evas_Object * obj)
Returns source code of global block data.
Remember to free the string with edje_edit_string_free().
Parameters
obj The object being edited
Returns
Source code of global block data.
References eina_hash_find(), eina_hash_iterator_key_new(), EINA_ITERATOR_FOREACH, eina_iterator_free(), eina_str_escape(), eina_strbuf_free(), eina_strbuf_new(), eina_strbuf_string_get(), eina_stringshare_add(), and EINA_TRUE.
edje_edit_object_color_class_list_get()
EAPI Eina_List* edje_edit_object_color_class_list_get (Evas_Object * obj)
Gets a list of color classes which given object use.
Parameters
obj The object being edited
Returns
The color classes list
References eina_hash_find().
edje_edit_color_classes_source_generate()
EAPI const char* edje_edit_color_classes_source_generate (Evas_Object * obj, Eina_List * color_classes)
Gets the source code for given color classes.
Parameters
obj The object being edited
color_classes The list of color classes for generate code
Returns
The color classes source code
References EINA_LIST_FOREACH, eina_strbuf_free(), eina_strbuf_new(), eina_strbuf_string_get(), eina_stringshare_add(), and EINA_TRUE.