Ecore Application functions
Ecore Application functions
Ecore
Functions
void ecore_app_args_set (int argc, const char **argv)
Sets up the programs command-line arguments.
void ecore_app_args_get (int *argc, char ***argv)
Returns the programs stored command-line arguments.
void ecore_app_restart (void)
Restarts the program executable with the command-line arguments stored.
void ecore_app_no_system_modules (void)
Do not load system modules for this application.
Detailed Description
Function Documentation
ecore_app_args_set()
void ecore_app_args_set (int argc, const char ** argv)
Sets up the programs command-line arguments.
Parameters
argc The same as passed as argc to the programs main() function
argv The same as passed as argv to the programs main() function
A call to this function will store the programs command-line arguments for later use by ecore_app_restart() or ecore_app_args_get().
References EINA_MAIN_LOOP_CHECK_RETURN.
Referenced by ecore_init_ex(), and elm_quicklaunch_fork().
ecore_app_args_get()
void ecore_app_args_get (int * argc, char *** argv)
Returns the programs stored command-line arguments.
Parameters
argc A pointer to the return value to hold argc
argv A pointer to the return value to hold argv
When called, this function returns the arguments for the program stored by ecore_app_args_set(). The integer pointed to by argc will be filled, if the pointer is not NULL, and the string array pointer argv will be filled also if the pointer is not NULL. The values they are filled with will be the same set by ecore_app_args_set().
References EINA_MAIN_LOOP_CHECK_RETURN.
Referenced by ecore_getopt_parse(), and ecore_getopt_parse_positional().
ecore_app_restart()
void ecore_app_restart (void)
Restarts the program executable with the command-line arguments stored.
This function will restart & re-execute this program in place of itself using the command-line arguments stored by ecore_app_args_set(). This is an easy way for a program to restart itself for cleanup purposes, configuration reasons or in the event of a crash.
References EINA_MAIN_LOOP_CHECK_RETURN.
ecore_app_no_system_modules()
void ecore_app_no_system_modules (void)
Do not load system modules for this application.
Ecore will now load platform-specific system modules such as power-management, time and locate monitors.
Whenever this function is called before ecore_init(), ecore won't load such modules.
This may be useful to some command-line utilities, hardly will be useful for end-user applications.
The environment variable ECORE_NO_SYSTEM_MODULES=1 may be used to temporarily disable system modules, often useful for debug.
Since
1.8
References EINA_TRUE.