Library Init and Shutdown functions
Library Init and Shutdown functions
Functions that start and shutdown the Elput library.
Functions
EAPI int elput_init (void)
Initialize the Elput library.
EAPI int elput_shutdown (void)
Shutdown the Elput library.
Detailed Description
Functions that start and shutdown the Elput library.
Function Documentation
elput_init()
EAPI int elput_init (void)
Initialize the Elput library.
Returns
The number of times the library has been initialized without being shutdown. 0 is returned if an error occurs.
Since
1.18
References ecore_event_init(), ecore_init(), eeze_init(), eina_init(), eina_log_domain_register(), and EINA_LOG_ERR.
Referenced by ecore_drm2_init().
elput_shutdown()
EAPI int elput_shutdown (void)
Shutdown the Elput library.
Returns
The number of times the library has been initialized without being shutdown. 0 is returned if an error occurs.
Since
1.18
References ecore_event_type_flush.