Drm library Init and Shutdown functions
Drm library Init and Shutdown functions
Functions that start and shutdown the Ecore_Drm2 library.
Functions
EAPI int ecore_drm2_init (void)
Initialize the Ecore_Drm2 library.
EAPI int ecore_drm2_shutdown (void)
Shutdown the Ecore_Drm2 library.
Detailed Description
Functions that start and shutdown the Ecore_Drm2 library.
Function Documentation
ecore_drm2_init()
EAPI int ecore_drm2_init (void)
Initialize the Ecore_Drm2 library.
Returns
The number of times the library has been initialized without being shut down. 0 is returned if an error occurs.
Since
1.18
References ecore_init(), eeze_init(), eina_init(), eina_log_domain_register(), EINA_LOG_ERR, and elput_init().
ecore_drm2_shutdown()
EAPI int ecore_drm2_shutdown (void)
Shutdown the Ecore_Drm2 library.
Returns
The number of times the library has been initialized without being shutdown. 0 is returned if an error occurs.
Since
1.18
References ERR.